### ISSUE TITLE
Radbyte vid ny mening i koden

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#10]
För att få läsbar kod och vettiga diffar efter några ändringar i texten är det bättre att skriva varje mening på egen rad, och bryta meningen efter ca 80 tecken om den skulle vara längre. LaTeX översätter radbyte till ett mellanslag.

Till exempel skulle stycket
```tex
Varje signal, som inte är sinusformad, är sammansatt av flera sinussvängningar.↩️
Det är signalens grundton samt dess harmoniska övertoner, vilka kan ha 2, 3↩️
o.s.v. gånger högre frekvens än grundtonen. Den inbördes styrkan på grundton↩️
och övertoner avgör signalens form. Om signalen ligger inom det hörbara↩️
området, kan man märka hur den ändrar karaktär beroende på övertonshalten. Man↩️
kan säga att övertonerna modulerar grundtonen.↩️
```

skrivas som
```tex
Varje signal, som inte är sinusformad, är sammansatt av flera sinussvängningar.↩️
Det är signalens grundton samt dess harmoniska övertoner, vilka kan ha 2, 3↩️
o.s.v. gånger högre frekvens än grundtonen.↩️
Den inbördes styrkan på grundton och övertoner avgör signalens form.↩️
Om signalen ligger inom det hörbara området, kan man märka hur den ändrar↩️
karaktär beroende på övertonshalten.↩️
Man kan säga att övertonerna modulerar grundtonen.↩️
```

**Comment by fnadde42** [comment]
Det låter rimligt. Jag röstar för detta förslag.

**Comment by sa0mad** [comment]
Tja vars, så kan man göra. Det blir en del jobb att göra den commiten, och jag tycker att man kanske skall prioritera annat. Om någon är motiverad att göra jobbet så visst. Så länge som det fortfarande är hyfsat läsbart i tex format så.

**Comment by sikvall** [comment]
Jag föreslår man gör det när man ändå håller på med ett särskilt stycke men i övrigt prioriterar det lågt. 

Sedan är jag i övrigt av den uppfattningen att om det är svårt att följa ett stycke i koden kanske det är så att stycket ändå borde delas upp bättre. 

Allt för långa stycken gagnar varken läsbarhet eller förståelse - i synnerhet om man har komplicerade meningsbyggnader med ett antal bisatser i följd. Det kan vara mer värt att lägga en liten stund på att formulera om stycket så det blir mer lättläst och lättbegripligt.

**Comment by sa0mad** [comment]
Det har nu kommit en bunt med pull-requests från Lominean, som jag mergat in i omgångar. En del riktigt omfattande. Kvarstår det här som en öppen issue?

**Comment by Lominean** [comment]
Jag noterar att de stycken som lagts till nyligen inte följer denna princip. Bara redaktionsgruppen är överens om en kodstil så blir det nog bra.

**Comment by sa0mad** [comment]
Jag har uppdaterat radbrytningsregeln i texifiering.md till att följa denna princip.
Det är nu del av regelsystemet, och jag anser att denna issue är åtgärdad.
