### ISSUE TITLE
Tryck-storlek på bok

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#114]
Storlek på bok behöver beslutas så att layout kan göras med det som mål.

Nuvarande förslag är B5 format

**Comment by Lominean** [comment]
Vilket format var det på första tryckningen?

**Comment by sa0mad** [comment]
Jag tror det är B5, men jag har inte mätt. B5 är något större än A5.
Vemsom är först att applicera linjal kan jämföra med måtten här:
https://en.wikipedia.org/wiki/Paper_size#Overview:_ISO_paper_sizes

**Comment by sa0mad** [comment]
Vid en snabb mätning verkar det vara något mindre än B5 om jag skall tro mitt 5 m stålmåttband, men jag tror nog B5 blir ett bra val.

**Comment by sikvall** [comment]
B5 är det geometriska snittet mellan A5 och A4. Jag antar att det i och med detta sätter ett bra format tillräckligt likt den gamla som fungerade bra, tillräckligt stort för man kan köra den existerande sidlayouten utan att det blir för smått.

**Comment by sa0mad** [comment]
Jag anser att vi beslutar B5 formatet.
Jag anser att vi beslutar om ringpärm. Det är inte en så stor kostnadsfråga och det verkar vara väldigt populärt.

**Comment by sa0mad** [comment]
Jag har satt b5paper som storlek i koncept-tryck.tex som med 'make koncept-tryck.pdf' genererar ett tryckorginal. Justeringar för storlek för tryckorginal sker alltså i koncept-tryck.tex.

**Comment by sm5phu** [comment]
Första upplagan var på 371 sidor.
Andra upplagan är just nu uppe i 601 sidor.

Blir en sådan bok för tjock?

**Comment by sa0mad** [comment]
Det är visserligen mer infformation i den, men inte med nära dubbla mängden.
@tfritzon kanske har något att säga om layout.
Jag strippade 16 sidor igår. Det borde gå att trimma bort en del annat som vi kanske inte behöver. Sen kan det vara en layoutfråga om hur vl man utnyttjat sidan mm.

**Comment by fnadde42** [comment]
Det kan ju finnas en poäng att dela upp den i en teknikdel och en reglementesdel för en bok bör inte vara otymplig att ha att göra med. När Table of Contents är mer än 15 sidor så är det en för tjock bok.

**Comment by sa0mad** [comment]
Det finns gott om material som inte behövs för kursen. Att dela upp det har redan diskuterats sedan länge, det övriga borde kunna få bli en referensbok. Det är den uppdelningen som de inte gjorde i orginal.

**Comment by sm5phu** [comment]
Men referensboken blir inte tunnare för att man plockar ut ett koncentrat ur den och gör till kursbok. . Referensboken måste fortfarande innehålla allt, även om vi väljer att filtrera ut ett subset till en tunnare kursbok.

**Comment by sa0mad** [comment]
Om du har en kursbok och en referensbok som utpekat par så är det inga problem att ha det uppdelat. Det är bara del 1 och del 2. Inget märkligt. Jag har redan gjort sådana bygg-protoyper.

**Comment by fnadde42** [comment]
Referensboken behöver inte innehålla bitar som förklarar hur saker fungerar utan fungerar som en bok man vänder sig till för att ställa frågan *vad?* istället för *hur?*. Alltså kan allt pedagogiskt jox tas bort och kvar blir ren information som man kan ta till sig om man redan är kunnig.

**Comment by sa0mad** [comment]
Det är ganska enkelt inledningsvis. Allt som är HAREC-krav skall vara i lärobok, det som inte är HAREC krav på kan läggas i referensbok. Sen på det som finns som HAREC-krav kan man sedan gå igenom och se om man kan ta delar och flytta över till referensbok för att göra läroboksdelen lättillgängligare. Framförallt får man titta på hur mycket tunnare läroboksdelen blir av första grov-sållningen. Jag har funderat på att göra makron som gör att det visas i enbart lärobok, enbart refbok, bägge samt att allt skall vissas, för totalbygget.

**Comment by sa0mad** [comment]
Refboken innehåller ju fördjupningar och extramaterial. Jag ser det som att när vi väl satt yxan mellan dem, så kan vi friare utveckla referensboksdelen utan att vara lika rädda att tappa bort läroboksdelen.

**Comment by sm5phu** [comment]
OK, då är den bok som vi jobbar med just nu varken kursbok eller referensbok?
Jag har hela tiden betraktat den som referensbok, vilket den första upplagan av KonCEPT var i förhållande till kursboken "Bli Sändaramatör".

Hursomhelst är målet med den här boken är att få ut en tryckt pappersbok som kan ersätta första upplagan av KonCEPT. Denna tryckta bok måste gå att hålla i handen och bläddra i. En bok som blir lika tjock som bred uppfyller inte självklart det kravet.

I ett senare skede vill jag ha ytterligare en bok (eller onlinekurs), som ska vara ett mera lättsmält kursmaterial.

Jag vill inte ha en tredje bok som referensbok.

**Comment by sa0mad** [comment]
Eftersom nuvarande är den som uppfyller HAREC, som explicit mål, så har de delarna övertagit i allt större grad läroboksdelen. Däri finns kompleterande delar som är mer referensboksmaterial. Att vi måste hitta ett sätt att banta sidorna är vi ense om, men det är bara konstatera att det som är det totala bygget är lite bägge och av lärobok och referensbok. Vi måste få ut en bok som är HAREC-komplett, och just nu är det anda upplagan på Koncept som är det. För att vara brutalt ärlig ser jag allt mindre behov av själva Bli Sändaramatör, men jag ser däremot behov av att göra en tydligare separation mellan läroboksmaterialet och annat extra.

Det går dessutom att stänga av figur och tabel-listningarna, vilket ger några sidors bantning. Jag ser ingen poäng med dem. Där gick vi från 601 till 589 sidor, dvs. ytterligare 12 tlll de 16 jag sparade in igår.

**Comment by sm5phu** [comment]
Och jag ser inget behov av en referensbok som går djupare eller bredare än det material vi jobbar med nu.

**Comment by fnadde42** [comment]
Jag tycker inte heller att det finns något större behöv av Bli Sändaramatör efter att vi har gjort ett ordentligt släpp av KonCEPT Lärobok. Bättre att ta de bitarna som är bra ur Bli Sändaramatör och dra in den i KonCEPT och sedan pensionera den då den inte är ens i närheten av HAREC kompatibel.

Vi kan ju släppa RC1 med hela boken på nästan 600 sidor så att folk kan börja granska den och börja med arbetet att dela upp den i två böcker så att vi kan praktiskt trycka den. Det känns som onödigt att förvirra folk genom att dela upp den på något annat sätt än referensbok/lärobok för att sedan göra en "ordentlig" uppdelning. Bättre att göra jobbet nu, även fast det kanske inte blir helt prefekt.

Hans hade ju en mycket bra plan över hur en lärobok skulle se ut men det är något vi kan sikta på att göra framöver. Ser hellre att vi bara gör uppdelningen så att böckerna går att trycka. Att materialet kommer i en bra pedagogisk ordning är givetvis eftersträvansvärt men inte prioriterat tycker jag.

**Comment by sm5phu** [comment]
"Bli Sändaramatör" är på 160 sidor. OK att den gamla inte täcker hela HAREC-bredden. Men är den verkligen så långt ifrån HAREC, att man måste utöka omfånget med 375% (ytterligare 440 sidor) för att nå dit?

**Comment by fnadde42** [comment]
Nej men förmodligen något mellan 200 och 300 baserat på vad jag har läst om HAREC och vad jag lärde mig av Bli Sändaramatör. Missförstå mig rätt; Det var en jättebra bok (minus några bitar om nödsignalering, ERP/EIRP/PEP osv som saknades) men när jag läste HAREC konstaterade jag att det bara var en del av vad HAREC krävde. Dessutom upplevde jag att bokens kapitel inte hade en logisk ordning [så som den som Hans SM0UTY föreslog](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/hans-disp.tex).

Jag upplever att det är lättare att ta ifrån Bli Sändaramatör till KonCEPT lärobok än tvärt om.

**Comment by sa0mad** [comment]
Jag gjorde en analys av vad de bägge böckerna täckte av HAREC, finns som spreadsheet som jag kan gräva fram. Jag gav snabbt upp på Bli sändaramatör för det var enormt många punkter som saknades, medans det gick rätt fort att identifiera stora grupper av HAREC punkter, och det som saknades var rätt uppenbart det som var nytt. Det var det som resulterade i att vi började med Koncept och inte med Bli Sändaramatör, helt enkelt för att det var så stor skillnad i hur mycket det var. Sen kan jag hålla med om att en del av Koncept var/är omständligt skriven bitvis, men det får vi åtgärda. Det var också så att det är överförenklat i Bli sändaramatör för vissa saker. Jag kan säga att vissa saker tyckte jag inte var bra skrivna i Bli sändaramatör, andra saknades. Koncept när den skrev blev för mycket "bra extra" utöver kursmateriialet, och det är nog bra att ha sådant, men det är en bok som bygger på en äldre upplaga av HAREC, och det märks då kapitelindelningen är oerhört välmatchande mot HAREC-detaljkraven.

Dock, ska man fort som attan få till det som var Hans upplägg, så behöver vi skriva en del nya saker, men grundbulten av jobbet är redan gjort. Jag har redan förberett ett sådant bygge. Jag har medvetet underhållit de även när jag bytt namn på filer så att det inte skall vara jättestort jobb att få ordning på det snabbt.

**Comment by sikvall** [comment]
En stor anledning att det blir fler sidor är att vi medvetet har satt den här versionen luftigt. Det gör det mer lättläst på bekostnad av att den blir lite mer otymplig. Men vi har mer marginaler och ett annat sidformat. I trycksammanhang är det antalet blad som är viktigt. 

Jag skrev en bok i A4-format för ett par år sedan på 300 sidor dvs ca 150 blad. Det gick utmärkt att hantera. B5 i 300 blad bör inte vara något problem men det måste man förståss kolla med tryckeri hur de ser på saken. Kan finnas begränsningar i processen de har.

Fantasygenren av böcker har ju annars en del tegelstenar i liknande format som kan vara på över 400 blad. Det är dock inte spiralbundna särskilt ofta utan limmade som regel men ändock.

**Comment by sa0mad** [comment]
Tryckstorleken på boken blev fastslaget till A4, och därmed blev den här issuen avklarad och icke-blockande för layout-jobbet. Dock glömde vi att uppdatera och stänga.
