### ISSUE TITLE
Undvik hänvisning till Wikipedia

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#116]
I delen "Bestämma magnetiska fältriktningen" finns en hänvisning mitt i texten till en Wikipediaartikel på ämnet men den innehåller inte mycket mer än vad som står i boken. Jag är av den åsikten att det är bättre att komplettera högerhandsreglen så den blir komplett istället för att hänvisa till en Wikipediaartikel som inte innehåller något mycket mer.

Jag har problem med att hänvisa till Wikipedia då det kan redigeras av vem som helst. Jag älskar Wikipedia men jag tycker att artikeln där bör hänvisa *till* vår bok och inte tvärt om.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/dee986a1067e6b1b0a36155d16e168e9c5ee8c01/koncept/chapter1-4.tex#L86-L99

----

Samma sak om MOSFET. Alla vet att man kan slå upp saker på Wikipedia och att praktiskt taget alltid stämmer men Wikipedia bör inte vara en källa. Här kan man antingen utvidga eller länka till något pålitligt verk som ARRLs bok.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/dee986a1067e6b1b0a36155d16e168e9c5ee8c01/koncept/chapter2-6.tex#L203-L211

----

NATO bokstaveringen kan man hänvisa till... NATO -> http://nato.int/cps/en/natohq/declassified_136216.htm/ (gärna på ett [mer akademiskt sätt](https://en.wikipedia.org/wiki/APA_style) med BibTeX där man undviker direktlänkar eftersom dom förändras då och då) 

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/dee986a1067e6b1b0a36155d16e168e9c5ee8c01/koncept/chapter11-1.tex#L31-L41

**Comment by Lominean** [comment]
Instämmer! Och om man nu tvunget ska referera till Wikipedia så bör man länka till en bestämd version av artikeln (motsvarande att skriva "Hämtad…" till en icke-versionshanterad resurs i en referenslista.)

**Comment by sa0mad** [comment]
åtgärdat. Har bara kommenterat bort länkarna. Det borde finnas gott om bra verk att referera till.
