### ISSUE TITLE
Störningar på analog TV är inte längre relevant

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#119]
punkt 30 i #49 
koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}
Det finns fortfarande gott om fastighetsnät med analoga signaler. NTJ.

**Comment by SM7NTJ** [comment]
Fixade bort % TODO texten och kommentaren från filen. Stänger #119
