### ISSUE TITLE
Granskning kapitel 1 Ellära

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#130]
Kapitel 1 Ellära skall granskas före 2.0.0-RC1.
Delkapitel 1.8 Modulation och 1.10 Digital Signal Processing innehåller nyskrivna delar, granska de extra noga.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by sa0mad** [comment]
Issue #63 samt #65 behöver åtgärdas för att denna skall kunna slutgranskas.

**Comment by sa0mad** [comment]
Illustrationer av brus inkluderade. Lade till lite kompleterande text.

**Comment by SM7NTJ** [comment]
granskat 1.4 frågor om ändringar skickade till MAD
granskat 1.5 Småfix. kan inte se om grader tecken är ok i 1.5.2 och 1.5.4 ljusvågor.
glömde skriva xx 130 i commit

**Comment by sa0mad** [comment]
Granskad
