### ISSUE TITLE
Granskning kapitel 7 Antennsystem

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#136]
Kapitel 7 Antennsystem skall granskas före 2.0.0-RC1.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by sa0mad** [comment]
Det kan nog gå att indexera upp lite mer termer, men annars är det nog bättre nu. @SM7NTJ take it away!

**Comment by sa0mad** [comment]
Yagi-antenn tas upp på flera ställen. Känns som att man kanske kan göra något. Lika dant med GP-antenn t.ex.

**Comment by SM7NTJ** [comment]
Kapitel 7 nu granskat och justerat. Några bilder ligger placerade en bit från tillhörande textavsnitt.
Till exempel tabell 7.1 ligger 2 sidor fel.
