### ISSUE TITLE
Granskning kapitel 12 Elsäkerhet

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#141]
Kapitel 12 Elsäkerhet skall granskas före 2.0.0-RC1.
Kapitel 12 Elsäkerhet innehåller nyskrivna delar, granska de extra noga.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by SM7NTJ** [comment]
Granskat elsäkerhetsavsnittet.

**Comment by sa0mad** [comment]
Granskad.
