### ISSUE TITLE
Granskning kapitel 13 Trafikreglemente

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#142]
Kapitel 13 Trafikreglemente skall granskas före 2.0.0-RC1.
Delkapitel 13.5, 13.9, 13.10, 13.11 samt 13.12 innehåller nyskrivna delar, granska de extra noga.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by SM7NTJ** [comment]
mindre justering av formulering i 13.8 som jag snavade över

**Comment by sa0mad** [comment]
Tips: Om du anger #<nummer> i ditt commit-meddelande så kommer incheckningen automatiskt synas här när du pushar.

**Comment by sa0mad** [comment]
Granskad och klar.

**Comment by sm5phu** [comment]
Uppdatera 13.4.2 med 2182 kHz.

**Comment by SM7NTJ** [comment]
Vi kan skriva något liknande nedanstående och lägga in det som en ny punkt efter 13.4.2 om vi anser att det behövs.

2182 kHz är inte längre en primär frekvens för nöd och säkerhetstrafik och det finns inte längre krav på att den ska passas av fartyg. (TSFS 2009:95 § 22 vakthållning)
Svenska kustradion slutade vakthållning på 2182kHz 1 februari 2005, US-coastgard slutade sin vakthållning av frekvensen 1 augusti 2013.
Frekvensen 2182 kHz är fortfarande reserverad för ”distress and safety communications for the Global
Maritime Distress and Safety System (GMDSS)”och radiopliktiga fartyg som trafikerar vatten i och utanför kustnära områden ska ha radioutrustning för frekvensen.

**Comment by sa0mad** [comment]
Jag tror man vill kanske uttrycka sig något i den här stilen:

En äldre nödfrekvens är 2182 kHz, men det är ej längre en primär frekvens för nöd och säkerhetstrafik och det finns inte längre krav på att den ska passas av fartyg. (TSFS 2009:95 § 22 vakthållning)
Svenska kustradion slutade vakthållning på 2182kHz 1 februari 2005, US-coastgard slutade sin vakthållning av frekvensen 1 augusti 2013. Det är därför olämpligt att fokusera sina kontaktförsök på denna frekvens om 

Frekvensen 2182 kHz är fortfarande reserverad för ”distress and safety communications for the Global
Maritime Distress and Safety System (GMDSS)”och radiopliktiga fartyg som trafikerar vatten i och utanför kustnära områden ska ha radioutrustning för frekvensen.

**Comment by sa0mad** [comment]
Jag tycker vi kan stänga den här nu. Dessutom är det bättre att öppna nya issues för specifika frågor, såå går det att hitta diskusionen sen.
