### ISSUE TITLE
Granskning bilaga D Beskrivningskod för sändningsslag

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#150]
Bilaga D Beskrivningskod för sändningsslag skall granskas före 2.0.0-RC1.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by SM7NTJ** [comment]
Granskat bilaga D beskrivningskod för sändningsslag
