### ISSUE TITLE
Granskning index

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#158]
Index skall granskas före 2.0.0-RC1.
Index innehåller nyskrivna delar, granska de extra noga.
Innehåll, illustrationer, tabeller, nyckelfraser, index, korsreferenser, referenser, formulering mm skall granskas.

**Comment by sa0mad** [comment]
symbol som datasymbol behöver separeras från symbol som lista av symboler. Två olika begrepp.

**Comment by sm5phu** [comment]
Fortfarande stor begynnelsebokstav på SI-enheter i rubriker, exempelvis "1.1.5 Elektrisk spänning - Enheten Volt", bör stå "1.1.5 Elektrisk spänning - Enheten volt".

Det verkar vara korrekt på de flesta ställena i löpande text, men fortfarande står "Joule" i stället för "joule" här och var.

**Comment by sa0mad** [comment]
Granskad
