### ISSUE TITLE
Automatisk versionshantering tar inte hänsyn till brancher när Git-hash infogas i bok

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#159]
https://github.com/SverigesSandareamatorer/SSA-Akademin/issues/43#issuecomment-328371461

Lösningen bör vara godtycklig och hämta Git-hash ifrån HEAD. Det finns lite olika idéer på hur det kan genomföras.

### Hämta ifrån Git-kommando 
`git rev-parse --short HEAD` ger förkortad hash ifrån HEAD (nuvarade branch). Fördelen är att det här är simpelt. Nackdelen är att man måste köra ett kommando.

### Hämta ifrån `.git`
`cat .git/HEAD` returnerar strängen `ref: refs/heads/master` som anger vilken branch som är i working tree. Tar man bort `ref: ` så att sökvägen `refs/heads/master` är kvar kan man hämta innehållet ur den filen (i `.git` mappen) vilket är den aktuella hash:en. Fördelen är att det hämtas direkt ifrån filsystemet. Nackdelen är att det är lite mer komplicerat och involverar strängbehandling.

_Refererar till #43_

**Comment by sa0mad** [comment]
Att hämta från .git är inte ogörligt.

**Comment by sa0mad** [comment]
Redan idag hämtas från .git/refs/heads/master:
`% Prepare for version handling
\usepackage{xstring}
\usepackage{catchfile}
\CatchFileDef{\HEAD}{.git/refs/heads/master}{}
\newcommand{\gitrevision}{%
  \StrLeft{\HEAD}{7}%
}
\CatchFileDef{\VERSION}{VERSION.txt}{}
\newcommand{\revision}{%
  \VERSION \gitrevision%
}`

**Comment by fnadde42** [comment]
Den borde vara godtyckligt och ta ifrån den branch som är utcheckad och för att göra det behöver man först ta reda på vilken branch som är aktiv genom att läsa innehållet i filen `.git/HEAD` och därifrån hämta sökvägen till branch-filen i `.git` och sedan hämta hash:en. Just nu tar den alltid ifrån master även fast vi kan vilja bygga ifrån någon annan branch.

**Comment by hin** [comment]
FWIW: Jag har löst detta i andra projekt med hjälp av kommandot 'git describe' med diverse flaggor (kolla dokumentationen). Det tror jag ska funka på alla platformar - det enda som krävs är att git finns installerat, och det funkar med brancher, taggar, m.m.

**Comment by sa0mad** [comment]
Jag var tvungen att hacka ihop något för att lösa problemet då jag aldrig kunde få någon färdig lösning som gjorde det på ett bättre sätt. På det sättet fick vi i alla fall githash på alla sidor. Om man kan lösa det med att läsa flera filer och följa det hela så är det väl en rätt OK lösning. Att behöva ropa på omgivningen riskerar vara mer problematiskt att få att fungera på fler miljöer, men om det bevisligen fungerar så kan det förstås vara ett alternativ. Fungerar .git/HEAD läsning för alla brancher, så är den vägen kanske den enklaste. Tar en titt.

**Comment by sa0mad** [comment]
Jag har försökt, men inte nått hela vägen, för den lyckas inte läsa \BRANCHFILENAME, men annars funkar den här:
\usepackage{xstring}
\usepackage{catchfile}
\CatchFileDef{\HEAD}{.git/HEAD}{}
\newcommand{\BRANCHFILENAME}{.git/\StrGobbleLeft{\HEAD}{5}}
\CatchFileDef{\BRANCHHEAD}{\BRANCHFILENAME}{}
\newcommand{\gitrevision}{%
  \StrLeft{\BRANCHHEAD}{7}%
}
\CatchFileDef{\VERSION}{VERSION.txt}{}
\newcommand{\revision}{%
  \VERSION \gitrevision%
}

Får jag bara hjälp att få den mellersta \CatchFileDef att köra med \BRANCHFILENAME så har jag en fungerande lösning att trycka in.

**Comment by fnadde42** [comment]
@kyrias skrev i [en kommentar](https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/449#issuecomment-423841120) att han har löst problemet med att Git-hash:en alltid plockas ifrån master även fast man är på andra brancher. Om det inte vore för mycket att be så skulle jag vilja se en Pull Request med det @kyrias för det skulle möjliggöra ett arbetssätt med flera brancher.

**Comment by phieri** [comment]
I byggsystemet med GitHub Actions som började användas i december 2021 infogas hash från den aktuella grenen. Stänger denna.
