### ISSUE TITLE
Listor är inte listor

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#178]
På flera ställen är listor uppdelade på flera rader (med `\\`) men inte uppmärkt som LaTeX-lista, med tillhörande layout.

**Comment by sa0mad** [comment]
Peka på några exempel.

**Comment by Lominean** [comment]
De har inte varit så lätt att hitta igen men två ändras med #183

**Comment by sa0mad** [comment]
En del listningar skall inte list-formateras. Jag har avformaterat några där det inte var en fördel med listformatet.

**Comment by Lominean** [comment]
Bra! Ja, det är en avvägning när det är pedagogiskt motiverat.

**Comment by sa0mad** [comment]
Absolut. Jag försöker städa bort det där uppräkningen snarare gör läsningen onödigt jobbig. Gamla layouten hade onödigt många, och det var inte konsekvent genomfört. Jag prioriterar lättläst över att försöka banka in det som till synes godtyckligt var lätt att lista.

**Comment by SM7NTJ** [comment]
Avklarat efter diskussion
