### ISSUE TITLE
Filstorlekarna på PDFer har minskat drastiskt de senaste byggena

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#185]
Filerna på [filservern](http://ssaakademin.fn42.se/) har alltid varit 11MB men de senaste byggena har det gått ner drastiskt. 

![tmp_22807-screenshot_20171001-2127322073362296](https://user-images.githubusercontent.com/1107419/31058257-1f04fb0a-a6f1-11e7-9c27-84b65d00123a.png)

**Comment by sa0mad** [comment]
Du får titta på dem. Mitt bygge blir fortfarande 11 MB.

**Comment by fnadde42** [comment]
Jag har tyvärr inte möjlighet att kolla på det just nu (är ute i min stuga som inte har el) men nu verkar det ju som att det som var ett eventuellt problem inte är det längre. Stänger denna tills vidare.

**Comment by Lominean** [comment]
Bygget avbröts då det inte hänt något på 10 min, dvs filöverföringen inte blev klar på 10 min.
