### ISSUE TITLE
Kolla att Supplement Teknik täcks

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#194]
http://www.ssa.se/download/sektioner/utbildning/Supplement-till-SSA-Utbildningsmaterial-161005-Teknikdel.pdf

**Comment by sa0mad** [comment]
Jag har gjort en mappning mellan de olika delarna och delkapitel för det mesta. Jag skall göra en mer detaljerad granskning för att försäkra mig att allt är med, även om det mesta ser ut att vara täckt.

**Comment by sa0mad** [comment]
Översiktsanalys
Faror - 12.1 och 12.1 täcker det väl
Risker med olika spänningar - 12.3.2 täcker det, bortsett från primärbatteri/ackumulator
CE-märkning - 12.2.1 täcker det mer än väl,, men CE-märket saknas.
Fi-märkning - 12.2.3 täcker det. Möjligtvis kan symbolen göras tydligare
Vad får man göra själv? - 12.2 inledning täcker det.
Radioamatören och självbyggen - 12.2.1 innehåller med aktuella regler
Säkring - 12.2.10 täcker det, men kan kanske kompleteras en aning
Jordfelsbrytare - 12.2.7 med aktuell skrivning
Att tänka på... - 12.3.6 sammanfattar det och för en del andra delar
Koncept-referenser hoppas här
PSK31 - 1.8.19
FSK - 1.8.16
APRS - saknas
QAM - 1.8.16
DTMF - saknas
Tonöppning - saknas
CTCSS - saknas
Subton - 6.2.4 omnämner det
PLL - 3.7.4 täcker det väl
Duplexfilter - 3.2.10 nämner det
ARQ - 1.8.18
AGC - 5.8
AFC - 3.5.3
Blockering - 10.2.1
Interferrens - 10.2.2
Intermodulation - 10.2.3, 5.9.6, 5.9.7
LF-detektering - 10.2.4
Operationsförstärkare - 2.10, 2.10.1 samt 2.10.2
DSP Digital signalbehandling - 1.13
ADC/DAC - 1.13.1
Sampling - 1.13.1
Vikningsdistorsion - 1.13.4
Induktiv reaktans - 2.3.7
Kapacitiv reaktans - 2.2.7
Gränsfrekvens - 3.2.2
Periodtid - 1.6.8
Frekvens - 1.6.9
Våglängd - 7.1
Fekvens - borde kanske finnas i 7.1
Spännng topvärde - finns lite spriitt, flera olika delämnen
Omsättning transformator - bägge finns i 2.4.4
Enhetsprefix - Bilaga A.1
Formler för Ohms lag och effekt - finns i 1.1.16 och däromkring
Dämplnng koaxkablar - saknas

**Comment by sa0mad** [comment]
@SM7NTJ och @sm5phu borde kolla min analys och därefter kan vi försöka åtgärda utestående punkter.

**Comment by sa0mad** [comment]
Översiktsanalys
Risker med olika spänningar - 12.3.2 täcker det, bortsett från primärbatteri/ackumulator
CE-märkning - 12.2.1 åtgärdat, själva CE-märket visas inte grafiskt.
Fi-märkning - 12.2.3 täcker det. Möjligtvis kan symbolen göras tydligare
Säkring - 12.2.10 täcker det, men kan kanske kompleteras en aning
APRS - saknas
DTMF - saknas
Tonöppning - saknas
CTCSS - saknas
Subton - 6.2.4 omnämner det
Duplexfilter - 3.2.10 nämner det
Frekvens - borde kanske finnas i 7.1
Dämplnng koaxkablar - åtgärdad i 7.6.10

**Comment by sa0mad** [comment]
Översiktsanalys
Risker med olika spänningar - 12.3.2 täcker det, bortsett från primärbatteri/ackumulator
CE-märkning - 12.2.1 åtgärdat, själva CE-märket visas inte grafiskt.
Fi-märkning - 12.2.3 täcker det. Möjligtvis kan symbolen göras tydligare
Säkring - 12.2.10 täcker det, men kan kanske kompleteras en aning
APRS - 1.8.19
DTMF - 5.8.9
Tonöppning - 5.8.7
CTCSS - 5.8.8
Subton - 5.8.8
Duplexfilter - 3.2.10 nämner det
Frekvens - borde kanske finnas i 7.1
Dämplnng koaxkablar - åtgärdad i 7.6.10

**Comment by sa0mad** [comment]
Stänger.
