### ISSUE TITLE
Ersätt "signal" med "anropssignal" där tillämpligt

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#195]
Exempel Kapitel 14.1: "Det är viktigt för att koordinera användning av spektrum och signalerna i det."
Vilka signaler? Elektriska signaler? Analoga signaler? Anropssignaler?

**Comment by fnadde42** [comment]
Jag håller helt och hållet med. Det ska vara glasklart vad som syftas.

**Comment by sa0mad** [comment]
895 ställen finns det på. En hel del jobb att hitta alla ställen.
