### ISSUE TITLE
Vad betyder skeds

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#196]
Jag har läst och begrundat men förstår inte vad "skeds" betyder. Texten kommer från första upplagan.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/a40d3888297ab7cf83bf5e59b4b57528c0705af6/koncept/chapter8-6.tex#L115

**Comment by sa0mad** [comment]
"Scheduled QSO", dvs. tidigare överenskommen radiokontakt.

**Comment by sa0mad** [comment]
Kan nog vara bra att förtydliga vad det är!
