### ISSUE TITLE
Kapitel-nummer i PDF TOC

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#197]
Den genererade PDFen har en TOC som visar kapitel och del-kapiitel. Det vore bra om det fanns nummer så man kan navigera på nummer utöver titel.

**Comment by fnadde42** [comment]
DuckDuckGo:ade snabbt fram det här: https://tex.stackexchange.com/a/11969

> Changing "A chapter" to "1 A chapter" on bookmarks:
>
>     \usepackage[numbered]{bookmark}

**Comment by sa0mad** [comment]
Lösningen fungerar, åtgärd commitad. Stänger.
