### ISSUE TITLE
Saknat försättsblad kap 11

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#200]
Alla kapitel har ett försättsblad där bara kapitelnummer och titel står, utom kapitel 11 Elektromagnetiska fält.

**Comment by sa0mad** [comment]
Frågan är hur vi vill göra. Jag har tyckt att det kanske blir bättre utan, men det är inte därför som kapitel 11 är utan, utan det har bara blivit så. Buggen är snarare att det är olika, men sen kan vi diskutera vilket som är bäst. Jag tror faktiskt på att det är snyggast utan försättsblad.

**Comment by sa0mad** [comment]
Nöjda?

**Comment by sa0mad** [comment]
Med det förslaget har vi gått från 617 till 601 sdor.

**Comment by sm5phu** [comment]
Jag gillar det nuvarande, utan försättsblad.

**Comment by sa0mad** [comment]
OK, då stänger jag den här.
