### ISSUE TITLE
Författare

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#201]
Jag har lite huvudbry över hur vi anger författare för denna andra upplaga.

Å ena sidan ska inte Wiberg fråntas äran av sitt arbete. Å andra sidan vet vi inte om han skulle velat sätta sitt namn på de förändringar vi gjort.

Jag har försökt titta på andra - mer kända - exempel.

Som författare till Rothammels Antennenbuch anges numera inte Karl Rothammel, utan Alois Krischke. Å andra sidan hette boken bara "Antennenbuch" från början, när Rothammel själv skrev. Nu har man ändrat titeln till "Rothammels Anntennenbuch" med författare Krischke, så gamle Karl får vara med på ett hörn ändå.

Ett annat exempel är Karlebo handbok. I min bokhylla står nionde upplagan, där Selim Karlebo själv är författare. Femtonde upplagan anger Eva Bonde-Wiiburg som redaktör. Sextonde upplagan har hela fyra redaktörer, Björklund, Gustavsson, Hågeryd och Rundqvist. 

Bonde-Wiiburg finns inte angiven som medredaktör till sextonde upplagan, även om den borde bygga på hennes femtonde.

Jag tror att endast Föreningen Sveriges Sändareamatörer bör anges som författare till den andra omarbetade upplagan. I förordet kan vi sedan ge cred till Lennart Wiberg.

**Comment by sm5phu** [comment]
Vill inte kompilera pdf efter att jag ändrade common.tex, frontpage.tex, tryckkort.tex.
Verkar inte bygga på Petters server heller.
Trött, går och lägger mig.

**Comment by fnadde42** [comment]
> Jag tror att endast Föreningen Sveriges Sändareamatörer bör anges som författare till den andra omarbetade upplagan. I förordet kan vi sedan ge cred till Lennart Wiberg.

Håller med.

**Comment by sa0mad** [comment]
Åtgärdad
