### ISSUE TITLE
Feedback-formulär till KonCEPT

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#204]
Vad behöver ett feedbackformulär ha för fält för att vi ska kunna få den information vi behöver till rättning?

Här är en länk till formuläret

https://drive.google.com/open?id=1s-_1OaMrJTiB_2ET3zWivwirj_yESuutCDapBNh-ndw

**Comment by sa0mad** [comment]
"För att vi skall kunna följa upp dina kommentarer vänligen lämna email-address och gärna även telefonnummer."

**Comment by sa0mad** [comment]
"Den publicerade PDF av KonCEPT 2.0.0-RC1 visar bokens text efter signifikant uppdatering och intern granskning, men dock innan layout för tryck har gjorts. Därför är antalet sidor, bilders placering mm. ej representativt för slutresultatet. Vi uppskattar dock de synpunkter som gäller innehållet med avseende på fakta, läsbarhet och korrekthet."

**Comment by sa0mad** [comment]
Börjar bli dags att få styrfart på det här. Jag har bidragit med några förslag till text-stycken. Börjar bli dags att få detta på plats.

**Comment by sm5phu** [comment]
Jag tycker detta är tillräckligt (https://goo.gl/forms/h1et2PUo7HSNEZou1)
Testa gärna. (Ska jag skapa ett formulär för återkoppling på formuläret?)

**Comment by sa0mad** [comment]
Var hamnar svaret?

**Comment by sm5phu** [comment]
Länk till inkomna kommentarer:
https://docs.google.com/forms/d/1s-_1OaMrJTiB_2ET3zWivwirj_yESuutCDapBNh-ndw/edit#responses

**Comment by sa0mad** [comment]
Länka direkt till http://akademin.ssa.se/files/koncept-pdf/koncept.pdf ?

**Comment by sa0mad** [comment]
Jag ser inget hinder kvar. Stänger.

**Comment by fnadde42** [comment]
Bara en snabbis. Regexen ser ut så här:

    ^[a-z0-9]{7,}$

Men hashen är bara hexadecimal vilket gör att de enda bokstäverna som ska användas är `a-f`. Så borde den inte vara som den nedan?

    ^[a-f0-9]{7,}$

**Comment by sa0mad** [comment]
Åtgärdad
