### ISSUE TITLE
Innehållsförteckningen borde inte vara expanderad som standard så inte användaren måste scrolla så mycket

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#208]
Detta bör lösas men någon post processing och JavaScript

**Comment by sikvall** [comment]
Man kan köra in en `\setcounter{tocdepth}{n}` där n är vanligtvis 1-2 för att minska ner den i händelse av att man bygger just för web.

**Comment by fnadde42** [comment]
Det kan vara en bra temp-lösning men jag funderade på att använda mig av JavaScript som gör det till en expandable/collapsable lista som typ den här:

http://code.stephenmorley.org/javascript/collapsible-lists/

**Comment by sikvall** [comment]
Det kanske går att få systemet sätta in en metatag som i post kan processas så rätt javasnurra stoppas in. Är dock inte helt vän av sånt i alla sammanhang (av olika skäl som kompatibilitet och för folk med skärmläsare pga diverse handikapp osv) men här kan det väl vara ok.

**Comment by sikvall** [comment]
Är detta fortfarande aktuellt och för vilka versioner av konceptboken? 
Webversion gissar jag?
