### ISSUE TITLE
Decimalkomma i math mode

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#213]
Kommatecken i math mode tolkas felaktigt som annan avgränsare än decimaltecken, med resultatet att det blir ett mellanrum efter kommatecknet.

**Comment by fnadde42** [comment]
Fixed by https://github.com/SverigesSandareamatorer/SSA-Akademin/commit/fdc77ef8ce7537fb9c5391d38c77328fa7efd5bb
