### ISSUE TITLE
Peka om så att byggda filer hamnar på SSAs server

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#214]
Göra lite flytt av filer och sedan peka om `.travis.yml`

**Comment by sa0mad** [comment]
Hur går det? Borde inte vara så svårt att åtgärda. Ska jag?

**Comment by sa0mad** [comment]
Åtgärdad och klar.

**Comment by sm5phu** [comment]
http://akademin.ssa.se/files/koncept-pdf/
