### ISSUE TITLE
Flera tecken och teckenföljder blir feltolkade

### ISSUE THREAD

**Issue by SM7NTJ** [SverigesSandareamatorer/SSA-Akademin#223]
I den byggda PDF så syns å, ä och ö med sina prickar.
Gör man sökning efter ord som innehåller å, ä eller ö så får man inga träffar i dokumentet.
Till exempel ordet "radioamatör" ger det noll träffar i dokumentet. 
Detta gäller även § tecknet som syns i PDF men inte är sökbart.

Vid kopiering och inklistring i ordbehandlare av text ur Koncept så finns prickarna med i vissa fall.
Teckenkombinationerna fi som i finns och fl  som i flera försvinner om text kopieras från koncept och ersätts men en liten hake respektive någon variant av citattecken,

**Comment by fnadde42** [comment]
Jag testade kolla på PDF:en ifrån det senaste körda bygget (samt byggde lokalt på maskin) och kunde inte återskapa felet förutom att jag testade söka på § men fick inte fram några resultat. Jag kikade dock på flera ställen i dokumentet och kunde kopiera och söka efter unicode-tecken. Använde samma version på filen från servern som den jag byggde lokalt (`da92721`).

Kan du beskriva hur man återskapar problemet?

**Comment by SM7NTJ** [comment]
![koncept da92721 skarmklipp_radioamator](https://user-images.githubusercontent.com/25039270/31814561-56617b3a-b58a-11e7-8580-88e08c4c2b87.JPG)
[Koncept da92721 inkopierad i notepad.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/1401420/Koncept.da92721.inkopierad.i.notepad.txt)
[Koncept da92721 inkopierad i word.docx](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/1401421/Koncept.da92721.inkopierad.i.word.docx)

Jag har testat med flera olika webläsare och flera versioner av Acrobat Reader och gjort
sökningar och kopiering/inklistring.
Ord som innehåller ö som till exempel "radioamatör" hittas inte vid sökning i Koncept PDF.
Söker man bara på "ö" så får man träffar på alla o och ö.

Söker man på "från" så får man träff på Frankrike och från.

Hittade vid sökningen även ett FRÅN som saknar ring över Å.

**Comment by fnadde42** [comment]
Så här ser det ut för mig när jag öppnar med [xreader](https://github.com/linuxmint/xreader) `koncept.2.0.0-RC0+b0361.da92721.pdf` (ifrån byggservern)

![screenshot from 2017-10-20 11-54-29](https://user-images.githubusercontent.com/1107419/31815648-9364568a-b58d-11e7-806c-5e16f90523e3.png)

**Comment by Lominean** [comment]
Det här verkar relaterat: 
https://en.m.wikipedia.org/wiki/Unicode_equivalence

**Comment by fnadde42** [comment]
@SM7NTJ kan du se om du kan återskapa felet som jag visade i mitt förra inlägg?

**Comment by fnadde42** [comment]
Jag får dock samma problem som du när jag kopierar ur text men det lustiga är att det precis som du säger inte är alla specialtecken utan verkar lite då och då leda till knasiga tecken men inte alltid.

**Comment by Lominean** [comment]
![scrndmp_koncept](https://user-images.githubusercontent.com/12006381/31850986-345ebb8c-b65d-11e7-8182-8ecf7a3e4c51.png)
Sökning och kopiering av ÅÄÖ fungerar för mig på macOS men paragraftecken kommer inte med vid kopiering från Förhandsvisning till LibreOffice.

**Comment by sa0mad** [comment]
Christer Jonsson rapporterade in samma problem, så därmed är problemet replikerat på annan maskin.

**Comment by fnadde42** [comment]
Infoga gärna också följande information för felsökning:

- Vilket operativsystem?
- Vilken version av PDF?
- Byggdes program lokalt eller hämtades ifrån byggserver?
- Vilket PDF-läsarprogram?
- Var problemet att söka efter `å,ä,ö` eller kopiera ut dessa tecken?

**Comment by sa0mad** [comment]
Windows. Senaste publika bygge från byggservern. Acrobat reader. Söka efter ord med åäö.

Jag skickar inte runt egna byggen längre när vi har ett publikt bygge, bättre att bara peka dit för alla nu.

**Comment by fnadde42** [comment]
> Windows [...] Acrobat reader

Det låter för mig som att Acrobat Reader har problem. Kan @SM7NTJ och Christer Jonsson testa ladda ner och köra Evince och se om det är någon skillnad? Denna har jag använt på Linux Mint länge och har inte de problem som dom beskriver.

https://wiki.gnome.org/Apps/Evince/Downloads

**Comment by sikvall** [comment]
Trasig inputenc kan ge denna typ av problem om man har flera olika sätt att koda tecken på. Det finns också problem med ligaturer av typen ff och fi som gör att vissa sökmotorer som inte är unicodeanpassade inte förstår att ligaturen fi är samma sat som bokstäverna f och i efter varandra i en söksträng.

I nästan alla dessa fall är det som TeX gör tekniskt korrekt men man har börjar skapa ett moras kring hur man faktiskt får saker att fungera i andra sammanhang och det kan vara ett riktigt hårigt bekymmer att lösa på ett bra sätt. Unicode är bra men när alla har en egen tolkning av standarden blir det alltid lite läskigt känner jag.

Anyways, i fordom har jag haft framgång med att byta till en uppdaterad fontkodare, motsvarande  `\usepackage[T1]{fontenc}\usepackage{lmodern}` för den brukar åtminstone lösa ligaturproblematiken och det är säkert något liknande som skapar de övriga problemen.

Man kan också testa om följande har någon effekt:

```
\input{glyphtounicode}
\pdfgentounicode=1 
```

Detta bör se till att det är god och vacker Unicode som flödar både in och ut ur textprocessorn likväl som typsnittskodaren och tillika pdfgeneratorn som då bör embedda allt som behövs. Bör. Det här är håriga tassemarker vill jag medge.

**Comment by SM7NTJ** [comment]
Jag kanske uttryckte mig otydligt.
Jag testade i två olika datorer. den ena med w10 den andra med W7. en med Firefox och en med IE. Båda med Acrobat reader DC.
Jag sökte i båda maskinerna och gjorde klipp och klistra i båda med samma resultat och testerna gjordes med samma travisbyggda PDF enligt ovan.

Nu testade jag att ladda ner och installera Evince.
Här med W10, firefox, senaste PDF 7c63d9b så hittas ord med åäö. 
Däremot hittas inte "finns" om man söker på finns, bara "Finns" 
Paragraf § hittas inte.
Med Acrobat reader DC och samma bygge hittas oförändrat inte ord med åäö.

När vi pratade i måndags om saken kom vi fram till att vi inte kunde lägga in det paket som troligen fixar problemet på grund av att bygge med travis inte fungerar då. Eller minns jag fel?

**Comment by SM7NTJ** [comment]
[nordiskateckentest.pdf](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/1424021/nordiskateckentest.pdf)
[nordiska tecken test.docx](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/1424022/nordiska.tecken.test.docx)
Jag har nu kört en rad tester men en testfil för att se hur nordiska tecken byggs och hur fi och fl samt § beter sig vid copy/paste.
\usepackage{lmodern} verkar lösa problemen både i kodning med UTF-8 och med ISO-8859-1.
Det får även \usepackage{ae} att fungera.
§ tecken blir sökbart och läsbart
 \S som paragraftecken blir inte sökbart men läsbart dock med nackdelen att mellanslaget efter paragraftecknet försvinner.

Så testar någon att bygga hela KonCEPT med \usepackage{lmodern} inlagt i common.tex?

p.s med evince som läsare blir testtexten i flera fall utspridd på flera sidor vid copy/paste då de nordiska tecknen verkar tolkas som radbrytning.

Här är testfilen

\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
%\usepackage[latin1]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[swedish]{babel}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{ae}
\usepackage{units}
\usepackage{icomma}
\setlength{\parindent}{0cm}
\setlength{\parskip}{2mm}
\usepackage{lmodern}

\begin{document}
Test av hur de nordiska tecknen byggs och hur det fungerar med copy och paste
med fi och fl.

Den finske radioamatören åke ärlig övade Flitigt på sin saxofon flera gånger om
dagen.
Hans grannar började tröttna på musiken och undrade en kväll försynt om det inte
finns någon § i huslagen som kunde få Åke att Öva mer på att köra radio i stället.

Tyvärr finns det ingen sådan \S i huslagen sa hyresvärden.
\end{document}

**Comment by sa0mad** [comment]
Gör en PR med det, så ser vi när den testbygger om det ställer till det eller inte.

**Comment by SM7NTJ** [comment]
\usepackage{lmodern} är nu implementerad i koncept.
Första synbara skillnaden är att läsbarheten ökade markant då svärtan i tecknen okade.
Tecknen verkar även ha blivit en liten aning större.

Teckengenereringen fungerar, ord med fi och fl i början återges korrekt och är sökbara och radioamatör är nu ett sökbart ord.
§ tecken är nu sökbart och ger träff på både § och \S vid sökning.

copy och paste fungerar utan teckentapp till notepad och TeXstudio.
Vid copy och paste till word i Office 2010 så försvinner prickarna över å, ä och ö.

Stänger issuen då ord med nordiska tecken nu blivit sökbara i PDF filen.
