### ISSUE TITLE
Konsekvent markering av fördjupningsmaterial

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#226]
För det material som ingår i HAREC-cert så är det markerat som HAREC.
Det vore önskvärt att ha en enhetlig taggning av material som inte ingår i certkravställningen, utan är någon form av extra-material/fördjuppning.

I 1.1.1 har jag på prov lagt in en tag som heter FÖRDJUPNING, men det är bara ett test och inte konsekvent genomfört.

**Comment by sa0mad** [comment]
Tagging eller annan typografisk separation. Det skall vara tydligt helt enkelt. Någonstans i förordet bör vi nog beskriva vad som skall läsas för certkurs och vad som är extra-material, vilket är brukligt.

**Comment by sikvall** [comment]
I bokformen är det lätt att margera stycken med en \marginnote vad som är fördjupning. Men å andra sidan borde det vara det mesta som inte är HAREC-krav?

Om vi inte mäktar med att markera det i resten av boken föreslår jag vi tar bor markeringarna (kommentera ut dem tills vidare) i kapitel 1 eftersom det annars blir lite förvirrad då de inte finns i efterföljande kapitel.

**Comment by sa0mad** [comment]
Jag säger att vi skall ha en konsekvent markering. Det jag gjorde på prov i kapitel 1 var för att vi skulle tar reda på vad som fungerar. Ingen markering kan också vara konsekvent, utom när ett underkapitel eller så går längre än HAREC rimligen kräver men det annars är rätt ställe att ge fördjupningen på.

**Comment by sa0mad** [comment]
@SM7NTJ bröt loss delar av spektrumanalysator texten till ett separat fördjupningsunderkapitel. Det löser problemet för de delar som krävs av HAREC men där vi går djuppare än vad som kan behövas för själva certet.

**Comment by sa0mad** [comment]
Det är bara att konstatera att vi inte orkade med att genomföra detta till första tryckningen på andra upplagan. Tar bort taggen.

**Comment by Lominean** [comment]
Om det fortfarande är relevant att göra så återöppna och lägg den på någon av de framtida _milestone_ så vi har koll på den.

**Comment by sikvall** [comment]
En fråga: Bör vi inte markera det som krävs för certifikatprovet så det är
enkelt att veta vilka delar i det rätt voluminösa materialet vi nu har som
man skall fokusera på för att klara certprov? HAREC är ju en mycket bra
början men har jag fel om jag tror svenska proven i dag inte fullt matchar
HAREC i den mån det kan finnas saker som kanske inte krävs av HAREC liksom
det kan finnas HAREC-krav som inte är med i provfrågorna?

/Anders

mån 15 okt. 2018 kl 13:26 skrev Petter Karkea <notifications@github.com>:

**Comment by sa0mad** [comment]
Det finns en viss risk att provfrågebanken utökas till att inkludera mer av HAREC. Därför är HAREC den begränsning som finns. Det finns ingen explicit uttolkning av hur HAREC skall tolkas i svensk kontext, och det inkluderar sådant som att svensk bokstavering sker helt utan referens "enligt tradition". Motsvarande gäller t.ex. delar av elsäkerhet mm. Det finns en del övrigt att önska. Det enda som egentligen står att finna är att man skall uppfylla HAREC.

**Comment by sikvall** [comment]
Svårt att bevaka en sådan drift på ett effektivt sätt, vi kan ju inte
heller alltid hänga med.

Man får alltså försöka hitta svaren i koncept när man börjat göra frågorna
men det gör det inte lättare för självstudier om man inte har en klubb som
utbildar.

/Anders

**Comment by fnadde42** [comment]
Det är nog bättre att låta boken vara neutral gentemot vilka kunskaper som krävs av provet och istället i så fall ha ett material som hänvisar vilka delar i boken som ska pluggas. På så sätt får man en mer tidlös bok som stämmer även fast provet förändras. Ett mindre häfte som beskriver vad som ska läras är lättare och mindre kostsamt att byta ut (går att skriva ut själv) än en tjock dyrare bok.

**Comment by sa0mad** [comment]
Det är precis det här som är den kursplan som jag pratat om, som i en form av lektionstillfälle-struktur beskriver vilka delar som skall gås igenom med referens in i bokens olika delkapitel. Det vi kan göra i själva boken är att kanske tydligare visa vad som tillhör själva HAREC-uppfyllandet och vad som är extra-material.

**Comment by sikvall** [comment]
Bra, det svarar mot min uppfattning också.

/Anders

tis 16 okt. 2018 kl 08:41 skrev Magnus Danielson <notifications@github.com>:
