### ISSUE TITLE
Grafisk layout av HAREC krav

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#227]
Dagens taggning av HAREC krav kan diskuteras i sin implementationsform.
Ett försök till makro har påbörjats.

Dock, egenskaper som skall behållas:
label skall sättas så att HAREC-bilagan kan länka till platsen
ref skall sättas så att det finns en länk till HAREC-bilagan
Flera referenser skall gå till rätt ställen.

Däremot kan det kanske göras på lite olika sätt layout-mässigt.

För bokstavering och Q-koder har dock många länkar till i stor sett samma plats, det borde kunna komprimeras utan att tappa utpekning, dvs. detaljerna skall finnas, men den presenterade länken kan ta mindre grafiskt utrymme genom att bara ge en \ref{}.

**Comment by sikvall** [comment]
Egentligen skulle jag föredra en marginalanteckning, fotnot eller liknande snarare än en fetstilssättning som nu vilket liknar en underrubrik mer än en referens. Själv känner jag att det står ivägen lite för läsflödet om jag nu inte specifikt just letar efter HAREC-referenserna.

Vad tänker ni andra / du MAD om det?

**Comment by tfritzon** [comment]
Det är något sådant jag tänkt med. Det förutsätter dock att vi har plats för marginalanteckningar vilket kan vara ett problem med tanke på att vi också vill minska antalet sidor.

**Comment by sa0mad** [comment]
Jag har inget emot att flytta dem åt sidan, jag vill bara inte tappa bort dem. Hyfsat öppen med hur vi löser det rent layout-mässigt. Även storlek på font kan lekas med osv. Jag gjorde dem feta mest för att särskilja dem. Jag är mer mån om att behålla dubbel-länk egenskapen och att man ser att det här ingår i HAREC-kraven. Vissa kommer sedan även ingå i CEPT Entry level och CEPT Novice, vilket vi nog kommer behöva tagga för i framtiden. Då kommer man ha HAREC, HAREC+Novice, HAREC+Novice+Entrylevel samt Extra

**Comment by sikvall** [comment]
Jag har satt dem i marginalen i tufte eftersom den är perfekt för sådant. Enda ändringen är att \textbf byts till en \marginnote vilket är enkelt att hantera. Kändes inte som ett macro behöve skrivas för detta.

**Comment by sa0mad** [comment]
Vi skall nog fundera på hur vi gör inför framtiden med web och sådant också, då kanske behöver blir lite annorlunda. Att använda marginnote rent formateringsmässigt är nog inte fel för layouten dock.

**Comment by sikvall** [comment]
För tryckningen blir det finemang. Hur det fungerar mot web har jag ingen
aning om men man kan ju enkelt definiera om makrot marginnote till att göra
något annat i webversionen.

mån 6 nov. 2017 kl 01:09 skrev Magnus Danielson <notifications@github.com>:

**Comment by sa0mad** [comment]
HAREC tagningen syns nu inte i tryckningen, men finns kvar i gransknings-PDF.
