### ISSUE TITLE
Lathund för pull requests

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#228]
Kan någon förse mig för en lathund för hur jag nu ska jobba med pull requests?
Jag har git installerat lokalt här och hittills har jag jobbat i CLI enligt följande:

git pull
<jobba med filerna>
git add fil.tex
git commit -m "#xxx"
git push

Vad är motsvarande procedur nu?

**Comment by sa0mad** [comment]
Förberedande steg för att skaffa sig en egen fork:
1) På huvudreporots sida, dvs. https://github.com/SverigesSandareamatorer/SSA-Akademin
    trycker man i Fork-rutan uppe till höger
2) Välj ens eget konto
3) Vänta tills forken är klar
4) Gör en klon av det nya repot med
    git clone https://github.com/<konto>/SSA-Akademin
    där länken kan tas direkt från websidan eller den gröna "Clone or Download" knappen

5) Gör förändringar på normalt sätt och checka in dem med

    git add fii.tex
    git commit -m "Någon vettig text som berättar vad man gjort #xxx"
    git push

6) Uppdatera sidan för din egen fork
7) Välj knappen "New pullrequest"
8) Tryck på "Create pullrequest"

**Comment by sm5phu** [comment]
3,5. Håll koll på var du står i ditt lokala filträd innan du clonar! Notera också att om du redan har en lokal kopia, måste du ta bort den först, alternativt lägga den nya kopian någon annanstans.

**Comment by sm5phu** [comment]
5. push efter commit funkar inte. "Permission denied".

**Comment by fnadde42** [comment]
Kan jag ringa dig så kan jag hjälpa dig (och samtidigt göra en lathund)? Mitt nummer hittar du i SM call book.

**Comment by sa0mad** [comment]
Jag körde igenom en ändring på prov genom den processen. Det gick bra. Däremot kanske jag inte var helt uppmärksam på de sista handtagen, men jag var febertrött.

Vi borde inkludera den trimmade processen i någon av våra dokument, README.md t.ex. Är det något du @fnadde42 känner för att ta tag i?

Dessutom borde en beskrivning om hur man håller sitt repo uppdaterat från SSA-mastern beskrivas tydligt.

**Comment by fnadde42** [comment]
Jag kan fixa en guide om hur man gör en Pull Request på GitHub ikväll.

**Comment by sa0mad** [comment]
Coolers. Det är flera som skall levla i sin GitHub kunskap nu, så vi får hjälpa dem nu när det glädjande nog börjar trilla in synpunkter utifrån.

**Comment by Lominean** [comment]
Visst kan man göra mer coola saker i terminalen men ska man jobba aktivt med koden så rekommenderar jag [GitHub Desktop](https://desktop.github.com). Då får man diffar som är enklare att läsa (typsnittsmässigt) och peka-och-klicka för att inkludera ändrade rader i en _commit_.

**Comment by fnadde42** [comment]
Kände inte till det här. Gör guiden för detta och sen för terminal.

**Comment by SM7NTJ** [comment]
Tar gärna emot en guide, har hittills kört med GIT GUI.
Har nyss laddat ner GitHub Desktop

**Comment by fnadde42** [comment]
https://github.com/SverigesSandareamatorer/SSA-Akademin/wiki/

**Comment by fnadde42** [comment]
Se guiden ovan
