### ISSUE TITLE
Layout: Korrigera avstavning

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#230]
Läsandet av boken bör syfta till att man får "certifikat", inte motsatsen "ocertifikat".

![screen shot 2017-10-27 at 05 26 39](https://user-images.githubusercontent.com/24322442/32086747-8e9003e4-bad7-11e7-8322-2b9b14d739f1.png)

**Comment by sikvall** [comment]
Korrigerat genom införande av avstavningsanvisningar i ordet "amatörradiocertifikat" enligt "amatör\-radio\-certi\-fikat".
