### ISSUE TITLE
P=R*I*I är samma som P=R*I^2

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#231]
### Avsnitt
1.1.13

### Kommentar
`P = R * I * I` är samma som `P = R * I^2`, liksom även `P = U * U / R` är en dublett

### Filversion
3e9d68a65217076434e4cfc36b0764b4fc2a9f90

**Comment by sikvall** [comment]
Matrisen av flera formler i 1.1.14 verkar lite märklig och håller med, det är en sak om man vill via och gå genom mellanledet P = R * I * I = R * I^2 för att vara ordentligt tydlig men denna leder tanken till att det är olika samband om man är ovan.

**Comment by SM7NTJ** [comment]
Javisst är det samma sak. Läs texten över formlerna.
Föreslår att vi skriver en mellantext mellan ohm lag och effektlagen som förklarar tydligare att det visar hur de två formlerna kan kombineras och kanske några "medförattpilar" mellan formlerna.

**Comment by sa0mad** [comment]
\Rightarrow

**Comment by SM7NTJ** [comment]
Åtgärdad
