### ISSUE TITLE
Layout: Innehållsförteckning i Acrobat 7

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#233]
Det har rapporterats att innehållsförteckningen ser lite konstig ut i Acrobat 7....
För kapitel 10, 13 och 16 saknas mellanslag mellan kapitelnummer och kapitelrubrik.

Nu är väl Acrobat 7 väldigt gammal? Jag vet inte varför någon envisas med att köra med den, och vi kanske inte behöver vara kompatibla hur långt bakåt som helst. Men finns något som skiljer just dessa kapitelrubriker från övriga, som skulle kunna tänkas ställa till problem även för nyare läsare?

**Comment by sa0mad** [comment]
Det ser korrekt ut i Acrobat 9.5.5 som jag kör. Däremot behövde man bredda TOC-delen för att det inte skulle bli forcerad radmaning.
Acrobat 7 är så gammal att det finns flera säkerhetshål som är opatchade. Främsta anledningen att den körs är nog att det är äldre Windows-installationer som inte uppdaterats, och därmed finns ytterligare säkerhetshål som borde patchas, men nu är det inte vårt egentliga sak att kommentera.

Jag är nog benägen att säga att vi inte gör något specifikt åt det.

**Comment by fnadde42** [comment]
Om man inte uppdaterar sin programvara så har jag svårt att se anledning varför jag ska lägga ner tid att supporta. Börja med att dra hem den senaste versionen och om fel fortfarande uppstår, återkom.

**Comment by Lominean** [comment]
Adobe Acrobat 7.0 släpptes alltså i januari 2005, ifall någon undrar.

**Comment by sa0mad** [comment]
Om inte det här någon känd och enkel lösning och workaround som fungerar även på nyare versioner så är det lätt beslut att ta att vi tänker inte göra något åt det här. Jag låter denna issue bero, men har inte herrarna grus sagt något om att de känner till en lösning fort, så tycker jag den här faller på ålderssträcket för supportad mjukvara.

**Comment by sikvall** [comment]
Jag tror det har med längden av siffror och rubriktext att göra och knas i avstavningen av densamma. Jag tror det finns nått noterat i en gammal rapport om pdflatex och detta men att woraround redan då var att uppgradera. 

Jag vet att det nog finns radioamatörer som allra helst håller fast vid sin Windows 95, 22 år gammal om de har hårdvara som kan köra den fortfarande och det var inte jättelänge sedan jag såg en 3.11 med winsock i dessa sammanhang men det är nog inte värt tiden att försöka fixa detta eller göra en särskild PDF för dessa.

Jag föreslår vi gör en notis om att det kan bli så i bokmärkena på riktigt gammal Acrobat, att det inte bör förta glädjen att den öht finns som pdf och sedan ser vi framåt med klar och ren blick i stället.

**Comment by sm5phu** [comment]
Återmatat att rapportörens pdf-läsare är tolv år gammal och behäftad med säkerhetshål. Felet går inte att replikera i nyare läsare. Ingen ytterligare åtgärd.

**Comment by sm5phu** [comment]
Enligt rapportören blir det fel även i Acrobat 11. OK, den är väl inte heller supportad längre, men kanske ändå något att undersöka?

![saknade mellanslag](https://user-images.githubusercontent.com/24322442/32420592-f365d016-c28c-11e7-9783-5d11b83d9293.jpg)

**Comment by sa0mad** [comment]
OK, det där exemplet visar nog snarare på att för lite utrymme har tilldelats för siffrorna, så när man får dubbelsiffriga tal så försvinner marginalen. Oups. @sikvall och @tfritzon kanske har något klokt att tänka här, känns som en klassisk LaTeX layout detalj och inte något Acrobat Reader specifikt.

**Comment by sikvall** [comment]
Avvakta layoutingen. Det kommer bli en hel del förändringar i hur TOC sätts.

mån 6 nov. 2017 kl 01:05 skrev Magnus Danielson <notifications@github.com>:

**Comment by sa0mad** [comment]
Nu åtgärdat.
