### ISSUE TITLE
Typsnitt (Serif) känns lite gammalt (och passar inte för webb)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#237]
### Kommentar

Typsnittet känns gammalt  (Times New Roman??) och skall ni använda delar av det som webbmaterial kan man få svårt att läsa det, Använd då hellre Verdana eller Arial eller liknande. Dessa är gjorda för bland annat datorskärmar, det är inte Helvetica eller Times New Roman.

**Comment by fnadde42** [comment]
Typsnittet som används heter [Computer Modern Unicode](http://cm-unicode.sourceforge.net/).

![screenshot from 2017-10-29 18-55-45](https://user-images.githubusercontent.com/1107419/32146721-01678364-bcdc-11e7-90a7-b4e601e0bd81.png)

Typsnittet har serifer precis som Times New Roman eller Georgia. Typsnitt som inte har dessa, så som Verdana eller Arial, heter sans-serif ("without serif"). Mycket tryckt material använder sig av serifer  eftersom det påstås att det ska vara lättare att läsa då seriferna förstärker linjen man ska läsa efter. Det finns (mig veterligen) inget vetenskapligt bevis att det är så då vi läser från ord till ord utan verkar mera vara något som typsättare säger. 

Personligen föredrar jag serif-text när jag läser i tryckt material och sans-serif när jag läser på dator (då skärmar ofta inte har tillräckligt bra upplösning som utskrift har, typ 300dpi).

Webbversionen använder sig just nu av ett sans-serif typsnitt men om någon känner att dom vill ha serifer där så kan nog stöd ordnas så att det går att växla mellan typsnitt.

**Comment by sa0mad** [comment]
Det är klart att man kan ha olika typsnitt för online/skärm och för tryck. Det finns en del annat som också skall anpassas med den distinktionen.

Vad som känns som "lite gammamlt" är däremot helt irrelevant, det är tycke och smak.

Som det är nu är det en online-variant får vi förmoda, så man kan fundera på om vi skall göra några justeringar på för just online-bruk.

@tfritzon @sikvall har kanske några vettiiga synpunkter.

**Comment by fnadde42** [comment]
Av min erfarenhet så använder nästan all tryckt litteratur, och framförallt kurslitteratur, serif och mycket av det jag läste på universitetet var dessutom skrivet med LaTeX i just Computer Modern Unicode. Däremot när det kommer till webb så gillar jag mer sans-serif och det använder vi även i testversionen av webbvarianten av KonCEPT

Om tryck sker på on-demand så går det ju att beställa en KonCEPT-bok som har sans-serif istället för serif men problemet då är att layout-teamet måste gå igenom hela boken och se till att inget har förändrats av förändringen av typsnitt och det är inget vi kommer att lägga ner energi på just nu. Om någon vill göra detta arbete så är det ju bara att köra på!

**Comment by SM7NTJ** [comment]
Det finns undersökningar om vad som läses bäst av typsnitt med serifer eller typsnitt av sans-serif typ .
Den första länken leder till en undersökning av läshastighet med hjälp av ögonrörelsekamera.
http://www.fungerandemedier.se/sites/default/files/bifogade_filer/Skarmlasning.pdf

Undersökningens resultat pekar mot att teckensnittet Georgia med serifer är lättare att läsa samt att tolv punkters teckengrad är ett bättre val än tio eller åtta punkter för läsning på bildskärm.

Länk två leder till Åke Hallbergs text om läsbarhet ur grafisk synvinkel.
http://www.fungerandemedier.se/sites/default/files/bifogade_filer/L%C3%A4sbarhet%20ur%20grafisk%20synvinkel.pdf

En slutsats i texten är att "den stil som är mest lättläst är den stil som du är mest van att läsa".

**Comment by sikvall** [comment]
Hej,

Under typografiutbildningen gjorde några ett särskilt studiearbete i detta
och gick igenom ett stort antal undersökningar som visar att på skärmar med
begränsad upplösning kan antikva (fr. serif) ibland vara svårare eftersom
vitsen med klackar och schatteringar inte kommer lika väl till sin rätt
medan groteska typsnitt (fr. sans serif) enklare renderas på sådant vis. I
dag kanske skillnaden mellan 600 dpi tryck på papper och skärm är mindre än
en gång i tiden när skärmar hade 72 dpi upplösningar i och med
"retinaskärmar" och annat.

Tekniska rapporter på jobbet sätts numera i en modern Helvetica just på
grund av att folk läser dem på skärmar mycket mer än att de skrivs ut innan
läsning.

Intressant nog har antikvor tydligen också någon liten fördel för folk med
lässvårigheter, osäker varför.

/Anders

sön 29 okt. 2017 kl 22:17 skrev SM7NTJ <notifications@github.com>:

**Comment by sikvall** [comment]
Hej,

Under typografiutbildningen gjorde några ett särskilt studiearbete i detta och gick igenom ett stort antal undersökningar som visar att på skärmar med begränsad upplösning kan antikva (fr. serif) ibland vara svårare eftersom vitsen med klackar och schatteringar inte kommer lika väl till sin rätt medan groteska typsnitt (fr. sans serif) enklare renderas på sådant vis. I dag kanske skillnaden mellan 600 dpi tryck på papper och skärm är mindre än en gång i tiden när skärmar hade 72 dpi upplösningar i och med "retinaskärmar" och annat.

Tekniska rapporter på jobbet sätts numera i en modern Helvetica just på grund av att folk läser dem på skärmar mycket mer än att de skrivs ut innan läsning. 

Intressant nog har antikvor tydligen också någon liten fördel för folk med lässvårigheter, osäker varför.

/Anders

**Comment by SM7NTJ** [comment]
För personer med lässvårigheter har typsnitt med antikva tecken sin betydelse.
Specialpedagogiska institutet (nuvarande Specialpedagogiska skolmyndigheten) har undersökt saken.
Flera faktorer underlättar läsande för personer med lässvårigheter. Direkt taget ur minnet:
Vänsterjusterad marginal d.v.s ojämna radlängder utan radbrytning av ord
10-12 ord per rad,
55-60 tecken per rad,
teckenstorlek 12-14 punkter,
lite ökat radavstånd,
typsnitt med seriffer.
En orsak är att personer med lässvårigheter ofta har svårt att följa en textrad med blicken och svårt att hitta tillbaka med blicken till rätt textrad. Variationerna i radlängd och seriffer hjälper till att hålla rätt rad i fokus.
Utöver detta kan pappersfärg, textens färg och papprets glansighet ha betydelse men dessa faktorer är mera av typen hur läsaren upplever att text går att läsa.

OBS, att göra text mera lätt att läsa är inte samma sak som att skriva det som kallas lättläst text där enklare ord, stor stil, korta meningar och gott om luft i och mellan texter gör det lättare att läsa för målgruppen för lättläst text.
