### ISSUE TITLE
Förtydliga: Ej myndighetskrav på loggbok

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#238]
### Avsnitt
15.1.2

### Version
7c63d9be8fa41ff965fc41cd00904966d85bbc71

### Kommentar
Det bör tydligare framgå att det inte är ett myndighetskrav att föra loggbok. 
I vår klubb använder vi det elektroniska loggprogrammet Logger32. Där finns ingen möjlighet att föra in när man öppnar och stänger stationen, inte heller om man skickar ut ett CQ. Man loggar bara genomförda QSOn.

**Comment by sa0mad** [comment]
Åtgärdad
