### ISSUE TITLE
Kommentar 4: Tabell med frekvensspektrum är rörig

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#239]
### Avsnitt
1.5.3

### Version
e5cc6da954cb03359e859e9cd52d060383ab86dc

### Kommentar
Vårt frekvensspetrum som här presenteras är helt annorlunda än tidigare och (känns fel) jag gillar det inte. Anser att nu har man rört till det.

![koncept-frekvensspektrum](https://user-images.githubusercontent.com/1107419/32363893-e2a493b0-c071-11e7-81a7-a121b0155fe7.png)

**Comment by sa0mad** [comment]
Ska man få det här så mycket tydligare så behöver man göra en ny grafisk form förmodligen.

**Comment by fnadde42** [comment]
Lade till jämförelsebild mellan först och andra upplagans frekvensspektrumstabeller

**Comment by fnadde42** [comment]
Jag vet då inte, men om tabellen är rörig nu så beror det inte på att den inte är tillräckligt lik den gamla utan att den gamla var för otydlig. Den nya tabellen är näst intill identisk med den gamla så när som på längden av strecken. Den enda betydande skillnaden jag ser är att mellan ULF och EHF fanns en klammer som förtydligade med texten "Radio" men det är typ allt.

**Comment by Lominean** [comment]
Kan du komma på _vad_ du känner är fel? Jag tycker den är rätt bra. Förtydligandet med ”Radio” var en bra grej.

**Comment by fnadde42** [comment]
@Lominean Förtydligande: Det här är feedback ifrån formuläret som jag har dragit in i GitHub så det är inte min åsikt att tabellen är "rörig". Jag vet ärligt talat inte vad som är problemet med den nya tabellen eftersom den nästan är identisk med den gamla.

**Comment by Lominean** [comment]
Ah! Sorry, jag missade labeln…

**Comment by sa0mad** [comment]
Jag översatte bilden till en tabell, och det blev väl sådär kanske, men det är lite svårt att visa relationerna, men ja, det är viktigt att visa både våglängd och frekvensrelationen. Gränserna för de olika banden är ju satta i dess våglängdrelation och inte frekvens, men vi använder bara frekvens idag.  Går man tillbaka ytterligare visas mycket mer, då visas även vad det är som är dominerande atmosfäriska fenomen för avböjning och reflektion.

**Comment by fnadde42** [comment]
Vill man göra något mer avancerat så får man göra en vektorbild och infoga den antar jag. Kanske en linjär skala och vart allting finns på den (ifrån radio till gamma)?

**Comment by sikvall** [comment]
Bilden (och tabellen) är inte för att presentera "vårt" frekvensspektrum utan den är för att presentera hela det elektromagnetiska spetrumet. Det är inte meningen att man skall slå upp saker i den här för att få reda på saker om amatörradio utan det är en bild som mycket översiktligt visar ungefär hur det ser ut med frekvens och våglängd för olika delar av det elektromagnetiska spektrumet.

Jag ser inte vad som skulle vara så dåligt med den. Det finns förstås säkert tydligare bilder också och i så fall får vi beakta om vi skall ta med dem till nästa version. Mer konkret information än det känns fel och man inte gillar den behövs också för att förstå vad som är det egentliga felet.

**Comment by sa0mad** [comment]
Lämnas utan åtgärdad. Konsensus @Lominean @SM7NTJ @sa0mad.

Rekommenderar lägga till radio-vertikalen.
