### ISSUE TITLE
Fri elektron per kopparatom eller en fri elektron per 850 atomer?

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#240]
### Avsnitt
1.1.2

### Version
1eb7b08cfe186d20259bc1c10f1663d35d0e98d8

### Kommentar
Det kanske är mina fysikkunskaper som är begränsade men som jag har förstått det är det en fri elektron (den i yttersta skalet) per kopparatom, men enligt avsnittet här är det endast en fri elektron per ca 850 atomer, stämmer det? är det mina fysikkunskaper som inte riktigt räcker till?

**Comment by SM7NTJ** [comment]
Korrigerat antalet kopparatomer i 1cm3 koppar.
Korrigerat antalet fria elektroner i 1cm3 koppar.
Metallbindning gör att de för bindningen överflödiga valenselektronerna blir fria elektroner
