### ISSUE TITLE
Kommentar 6: Vilken version av KonCEPT gäller för certskrivningen? Lite förvirrad...

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#243]
### Kommentar
Vilken koncept bok gäller idag för cert skrivningen? Lite förvirrad då den blå boken varit giltig tidigare. Men jag nu fått info om att den nya gäller istället. Vilken gäller. Behöver hjälp att hitta rätt nu läser jag två koncept böcker.

**Comment by fnadde42** [comment]
Andra upplagan av KonCEPT som vi arbetar med här är inte än så länge klar med granskning. Det innebär att det finns ställen där en tryckfelsnisse kan ha smugit sig in. Boken (som regelbundet publiceras på [akademin.ssa.se/files](http://akademin.ssa.se/files/)) är mycket nära ett tryck nu och har många förbättringar och rättningar som den gamla boken inte har. Det största problemet nu egentligen med den upplagan vi arbetar med är layout som kan vara ganska konstig på sina ställen men det håller layout-teamet på att arbeta med.

Du kan bara köpa den [första upplagan av KonCEPT](http://www.ssa.se/hamshop/index.php?route=product/product&product_id=72&search=koncept) på [Hamshop](http://ssa.se/hamshop/) så om du vill ha ett fysiskt exemplar så finns det inget val.

**Officiellt** så gäller fortfarande "gamla" KonCEPT (första upplagan).

Jag skulle säga; Använd den [nya KonCEPT boken](http://akademin.ssa.se/files/) (även fast den inte är klar) och bortse ifrån layoutmässiga fel. Den nya upplagan innehåller förbättringar av den gamla och det är egentligen på de nya bitarna som det kan bli fel på. I vilket fall så innehåller den nya upplagan i värsta fall de gamla felen som finns kvar sedan första upplagan och fel i de tillagda bitarna men efter långt arbete så kan jag försäkra dig om att vi har fixat en stor mängd fel.

**Comment by sa0mad** [comment]
När du överför en fråga/kommentar från återmatningen, ange dels att det kommer från formuläret och vilken fråga i ordningen, så kan man skilja det från när du skriver något som dig själv. Detta är väl kommentar 6.

**Comment by fnadde42** [comment]
Jag tänkte på det så jag gjorde en label som heter "feedback" så om du söker issues med `is:issue label:feedback` så får du allt vi fått i vårt formulär. Internt bockar jag av vilka jag har fört över ifrån kalkylarket som frågorna landar i. Jag återkommer om det här på vårt möte imorgon kväll.

**Comment by sa0mad** [comment]
OK

**Comment by fnadde42** [comment]
Svar införd i [FAQ](https://github.com/SverigesSandareamatorer/SSA-Akademin/wiki/FAQ)
