### ISSUE TITLE
Merge av litteraturförteckning för första och andra upplagan

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#244]
Ser att första upplagans litteraturförteckning är en bilaga just innan litteraturförteckningen för den första upplagan. Varför är det så här? Känns som en mycket bättre ide att se till att den gamla litteraturförteckningen använder sig av samma "system" (bibtex) som den nya.

**Comment by sa0mad** [comment]
Den nya literaturförteckningen införs genom citat-referenser i texten, varvid literaturlistan fylls i automatiskt. Den gamla saknar den informationen, vilket gör att vi inte kunnat införa det på hela listan. Vi var därför tvugna att lägga in hela den gamla listan som en bilaga. I den har vi sedan gjort referensern över till den automatiskt uppdaterade för de fall att de fanns. Det är en kompromislösning som det var svårt att hitta en bra lösning på. Om vi haft tillgång till alla de texter som refererats och mer tid, hade vi säkerligen kunnat ange referenser i texten på mer sedvanligt sätt, men det fanns inte tid till det denna vända. Helt klart något att följa upp över tiden.

**Comment by fnadde42** [comment]
Ok! Så om vi inte vet var litteraturen refererades ifrån så är ju det här den minst "sämsta" lösningen. Håller med och stänger.

**Comment by sa0mad** [comment]
Ja, det här är en kompromis helt klart, att helt kasta referenserna var sämre alternativ.

**Comment by sikvall** [comment]
Håller med men man har väl inte hunnit stoppa in det i bibtex-filen ännu 
och göra alla referenser. Det är en del jobb men på sikt borde det 
förstås vara så.

/Anders
