### ISSUE TITLE
Kommentar 7: Inhehållsförteckning "Sakregister" saknas

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#245]
### Version
6c47bfaefc3a8dd0422deaff4bc5e78ef9f3c9b5

### Kommentar
Inhehållsförteckning "Sakregister" saknas. mvh Ulf

**Comment by sa0mad** [comment]
Även förord saknas, så jo. Mycket bra kommentar!

**Comment by SM7NTJ** [comment]
Likaså "Litteraturförteckning"

**Comment by sa0mad** [comment]
Åtgärdat.
