### ISSUE TITLE
Mer information om baluner

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#246]
### Version
6c47bfaefc3a8dd0422deaff4bc5e78ef9f3c9b5

### Kommentar
Om Baluner se länk http://www.foxcomputer.se/ sedan länk "RF Transformer TLT, Balun, Inductor and RFC.pdf - Practical Handbook about Ferrite and Iron Core ver 1.3". mvh Ulf

**Comment by sa0mad** [comment]
Jag tycker att vi skall göra en websida med behändiga referenser för ytterligare fördjuppning.

**Comment by SM7NTJ** [comment]
KonCEPT innehåller information om baluner dock saknades indexposter för balun och transmissionsledningar. Nu är indexposter införda så att informationen lättare kan hittas.
Vi får se om mer information om olika typer av balunkonstruktioner  förs in en framtida uppdatering av KonCEPT.
