### ISSUE TITLE
Fel i uträkning av fria elektroner (10 saknas i tiopotensen)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#247]
### Avsnitt
1.1.2

### Version
3eaa4a1511439477b7e47f8fe395f632cfdfeab1

### Kommentar
Sista meningen i avsnittet "1cm^3 av koppar innehåller t.ex. 8,5^22 stycken fria elektroner." Borde vara 8,5*10^22.

**Comment by SM7NTJ** [comment]
Fixat ligger som pull request
