### ISSUE TITLE
Bryta loss modulation till separat kapitel

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#250]
En tanke som kom från SA7AKG är att bryta loss modulation till separat kapitel. Idag lite spritt på flera kapitel. Jag tycker att det kanske är lite sent att ändra strukturen nu inför layout och granskning, men inför en kommande revidering kanske.

**Comment by sikvall** [comment]
Håller med. Det är mycket jobb med referenser och annat och att arbeta genom texten så den blir sammanhållen och läsbar.

Håller även med om grundproblemet, på sikt tycker jag att vi skall ha modulation på ett samlat ställe. Jag föreslår vi behåller denna issue men skjuter den på framtiden.
