### ISSUE TITLE
Försättsblad och innehållsförteckning har egen sidnumrering

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#251]
Antingen har man gemensam sidnumrering, vilket är bättre för online-PDF, eller romersk numrering på försätsbladen och innehållsförteckning.
Att åtgärda i layout.

**Comment by sikvall** [comment]
Vi kommer titta på det också. Just nu typsätts knappt denna del i layoutgrenen och det är ingen fara med det, fokus ligger på att få huvudmaterialet layoutbart samt lösa en del inkonsistenser t.ex. hur formler typsatts på olika ställen, Nyttja marginaler bättre för noteringar, små bilder och annat som passar där samt rätta så mycket vi kan i ännu en genomläsning.
