### ISSUE TITLE
Kommentrar 9: Bok för tjock samt illustrationer och pedagogiska element föråldrade

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#252]
### Kommentar
Är det till ungdomar vi riktar oss så kan man inte ge dom en bok på 500 sidor, dela upp boken i flera böcker  efter inne håll. Tex Ellära, Antenner, komponenter. Det sägs att layouten inte är klar , det är ju en evinnerlig tur det. Jag har jobbat på gymnasiet i 27 år som lärare på Elprogrammet. tittar man i moderna läroböcker så är det färgbilder , ofta i 3D , bilder på komponenter, vågformer fotade i ett oscilloskop mm. Dessutom måste det gå att korta av texten betydligt, det blir alldeles för tungt att läsa för ungdomar.

**Comment by fnadde42** [comment]
> Det sägs att layouten inte är klar , det är ju en evinnerlig tur det. Jag har jobbat på gymnasiet i 27 år som lärare på Elprogrammet. tittar man i moderna läroböcker så är det färgbilder , ofta i 3D , bilder på komponenter, vågformer fotade i ett oscilloskop mm.

SSA behöver börja trycka böcker för att det ska finnas att köpa. Det här inledande arbetet har varit att digitalisera, rätta och förbättra så att boken uppfyller HAREC-kraven. Vi har alltså inte fokuserat på att göra illustrationer pedagogiska eller materialet utbildningsvänligt. Det finns helt enkelt inte tid. Det här innebär att vi kommer att göra dessa saker i framtiden *efter* att vi har gjort en bok som går att tryckas inom en snar framtid.

Illustrationerna (som texten) är rakt scannade ur KonCEPT (första upplagan) men texten är på vissa ställen ändrad och har vissa tillägg. Bilderna har fått ta en lägre prioritet där men dom kommer också att uppdatera och där vill vi ha så mycket hjälp som möjligt ifrån andra intresserade att göra dom så pedagogiska som möjligt.

> Är det till ungdomar vi riktar oss så kan man inte ge dom en bok på 500 sidor, dela upp boken i flera böcker efter inne håll. Tex Ellära, Antenner, komponenter. [...] det blir alldeles för tungt att läsa för ungdomar.

Det håller vi med om! KonCEPT var en bok som var tänkt som en lärobok men som blev mer som ett uppslag. Därför innehåller boken både en hel del förklarande element men också en hel del data och information som redan certifierade amatörer kan slå upp och finna användbart. Därför har vi haft på bordet många olika idéer för hur man ska lösa det här problemet varav en av dom var att dela upp efter teknik, reglemente. Ett annat sätt att göra det är att plocka ut de delarna som har med pedagogik att göra till en separat KonCEPT Lärobok medan allt referensmaterial så som data och tabeller hamnar i KonCEPT Referensbok.

**Comment by sa0mad** [comment]
Lämnas utan övrig åtgärd.
