### ISSUE TITLE
Gör ⧈ till en illustration

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#253]
I delen 12.2.3 `Liten terminologi vid elinstallationer` nämns symbolen ⧈ för "Förstärkt isolering" i löptexten. Symbolen skulle gott kunna blåsas upp till en illustration/bild.

**Comment by sa0mad** [comment]
I samma anda borde både CE och FI märkning illustreras.

**Comment by SM7NTJ** [comment]
Det verkar gå att göra så här när jag testar i mitt testdokument

\newfont{\ce}{cerm}                         % 10-point CE symbol
\begin{document}
{\ce CE}-märkt utrustning

{\Huge{\(\boxbox\)}}

Detta ger ett CE-märke följt av efterföljande text

Dubbelkvadraten blir stor

**Comment by SM7NTJ** [comment]
Stäng issuen efter kontroll att CE-märke och Fi-märke gått igenom felfritt

**Comment by SM7NTJ** [comment]
CE-symbol CE-mark.pdf nu införd
Fi-symbol Fi-mark.pdf nu införd
