### ISSUE TITLE
Kommentar 12: KonCEPT måste ha mycket bättre språkbruk

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#255]
### Kommentar

Hej!

En god vän till mig, f d forskare m m, har ögnat igenom den nya upplagan av KonCEPT. Han var t ex imponerad av att författaren lyckats förklara QAM-modulation på ett begripligt sätt. Av nyfikenhet slog jag således upp det stället i boken, där jag läste följande stycke:

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/6e1740226f7ed1c7255340fdf98509301fa3c89c/koncept/chapter1-8.tex#L886-L893

Jag måste nog erkänna att jag studsade till vid anblicken av denna text p g a språket. Några synpunkter:

- dagisglosan "Medans" förekommer inte i min vuxenvärld (senare såg jag ordet på flera ställen i boken)

- fogeordet "att" i första meningen inleder en bisats, och i en sådan skall ordet "inte" placeras före verbet så att det står "att det inte är"

- I frasen "behöver man ha I och Q värden som är" o s v skall det vara bindestreck efter både I och Q. Annars bli det s k "sär skrivning".

- den folkliga förkortningen "iofs" brukar skrivas med mellanslag

- även annat, som särskrivning och rena skrivfel, måste korrigeras

Det kändes något illavarslande, att det första och enda stycket jag således fick syn på är så gravt undermåligt ur språklig synpunkt. Jag avstår från vidare granskning och hoppas att även en språkligt kompetent person får tillfälle att granska texten mer systematiskt för att korrigera såväl felskrivningar som språkliga brister. Min avsikt är självfallet inte att vara petig i överkant. Min förhoppning är att KonCEPT skall bli ihågkommen för sitt fina faktainnehåll - och inte för sitt usla språk.

Min gode vän undrar också över användningen av ordet "resistor" i boken. Det är såvitt han känner till inte ett allmänt vedertaget ord inom svensk elektronisk terminologi.

73 & GL,
Rolf
SM5MX

**Comment by sikvall** [comment]
Inom elektroniken används resistor för att tala om den specifika komponenten som dagligvis kallas motstånd. Men motstånd har man generellt i alla ledare och av olika slag (växelströmsmotstånd eller induktans och komponenten benämns då ofta  induktor).

Ett fackord förvisso men inte felaktigt i min mening. Däremot kanske man bör kontrollera konsekvens, dvs om man oftast använder motstånd för att benämna komponenten och sedan på några ställen använder resistor (kanske olika författare) blir det ju lite förvirrande.

Jag är helt säker på att det finns många många ställen man kan förbättra språket. Ibland är det en smula högtravande. Ibland är det skrivet lite för grovt förenklat. Det där lär vi ta en bit i taget och försöka få en jämn och flödande språklig stil.

Vi ska tänka på att boken läses av unga som skall utbilda sig till sändaramatörer liksom personer som inte har svenska som modersmål varför en text med enklare lexikalitet är att föredra av tillgänglighetsskäl enligt min ringa mening.

**Comment by sikvall** [comment]
Jag skulle också undvika förkortningar av typen "iofs" och "tex" och liknande. Skrivt ut dem i stället.

**Comment by sm5phu** [comment]
Jag har mejlat SM5MX, tackat för hans kommentarer och uppmuntrat honom att fortsätta.

**Comment by fnadde42** [comment]
Den KonCEPT-bok som vi presenterade här för några dagar sedan är i stora delar bara en digitaliserad variant av den gamla KonCEPT boken och mycket av de fel och brister som står där är alltså ärvda ifrån den första upplagan. Det har varit ett hästjobb att bara konvertera boken till det digitala format vi har idag och därför har vi öppnat upp för att få mer hjälp av "allmänheten".

Låt mig bara först säga: Ja! Jag håller med dig om att språkbruket lämnar en hel del att önska. Jag jobbar själv med automatiserade byggen av boken och mycket om det tekniska runtom så jag har själv faktiskt inte läst nästan något av boken men det lilla jag har läst har varit i stort behov av omarbetning. 

Problemet som jag ser det är att vissa som bidrar är jätte entusiastiska att fylla boken med bra och nyttig fakta, förklaringar och information, men använder kanske inte det bästa språkbruket. Det är helt okej eftersom det finns andra som kan granska och se till att den text som läggs till är av god kvalitet. Alla behöver inte vara bäst på allting. Därför är det jätteviktigt att alla som är språkligt begåvade hjälper till för att omformulera dessa välmenande teknikers, ibland, felformulerade svenska.

> Vi ska tänka på att boken läses av unga som skall utbilda sig till sändaramatörer liksom personer som inte har svenska som modersmål varför en text med enklare lexikalitet är att föredra av tillgänglighetsskäl enligt min ringa mening.  
> // @sikvall 

Ja, KonCEPT ska, enligt mig, inte använda sig av en onödigt hög nivå på språket och det är i sig ingen motsättning till att vårda det (och det är det jag antar att du menar).

600 sidor att gå igenom är ganska mycket men vi måste komma ihåg konsten att äta en elefant... en tugga i taget. Ju fler som deltar och som granskar text desto bättre och desto snabbare går det. Jag hoppas att du har möjlighet att göra den här boken bättre genom dina goda språkkunskaper. 

Jag ska själv börja granska texten grundligt men det kommer att ta ett tag. Om jag granskar 20 sidor varje dag så hinner jag innan vi kanske måste börja trycka boken.

Ja, jag vill att KonCEPT ska bli ihågkommet för sin fakta och gedigenhet och inte för dåligt språkbruk. Det är *inte* petigt och gnälligt att sikta på högre mål.

---

> Jag skulle också undvika förkortningar av typen "iofs" och "tex" och liknande. Skrivt ut dem i stället.  
>// @sikvall 

Jag håller med. Skriv ut förkortningarna. Det tar praktiskt taget ingen extra plats. Detta borde föras in i `texifiering.md`.

**Comment by sikvall** [comment]
Jag håller med fullt. Men kommer behöva ägna mig åt layouting a primo och språkfix a secundo till en början i alla fall. Därefter hjälper jag gärna till. Sedan är jag inte någon lingvist men tror ändå jag kan rätta till en del saker som behöver fixas.

Ja, mycket konstigheter är ärvt, det är helt sant. Rent personligen så vill jag också hellre skjuta lite på tryckningen tills att det känns bättre. Dåligt språk kan alla ha åsikter om, det räcker med religiösa åsikter om antenner vilka vi tids nog kommer få ta del av... :)

**Comment by sm5phu** [comment]
Jag tror att "resistor" var den benämning som användes i gymnasiekursen (Markesjö) på min tid. Men det var länge sedan och minnet har bleknat. I Elfa-katalogens register är sökordet "motstånd". I Ericssonvärlden (Eriterm) gäller "motstånd". Enligt TNC är "motstånd" det rekommenderade begreppet, men "resistor"är accepterat: http://www.rikstermbanken.se/visaTermpost.html?id=205593

**Comment by sa0mad** [comment]
"resistor" är ett korrekt ord för komponenten, men idag har "motstånd" ersatt benämningen för komponenten och används därför för både själva fenomenet och komponenten. Jag tycker nog att det korrekta sättet är att förklara att bägge begreppen är relevanta för komponenten, men jag tycker nog att man skall använda ett av dem genomgående, och då tycker jag nog att vi kan använda motstånd på de flesta platser, men egentligen är det slarv, för det är så det kallas i dagligtal.

**Comment by sm5phu** [comment]
Den ursprungliga benämningen är "motstånd". Så heter det i Hermods "Radio 1" från 1952 och i Schröders "Radiobyggboken 2" från 1952 och i Ericssons tekniska ordlista Eriterm från 1992. Även enligt Tekniska nomenklaturcentralen är benämningen "motstånd" att föredra, men "resistor" kan accepteras. Benämningen "resistor" tillkom någon gång på 1970-talet, vilket kan förklara att läsare av den gamla stammen hakar upp sig på uttrycket.

En del finns att läsa här: 
[http://www.ham.se/index.php?threads/n%C3%A5gon-som-vet-vad-en-kapacitor-%C3%A4r.22731/page-3#post-57644](url)

**Comment by fnadde42** [comment]
Som en som kommer utifrån och inte vuxit upp med ellära så gillar jag benämningen "resistor" på komponenten och "motstånd" på själva effekten. Det blir för mig en semantiskt tydlig uppdelning av hårdvaran och vad den gör.

**Comment by sm5phu** [comment]
Så här ser jag det, i de ideala fallen:

Komponenten "kondensator" har egenskapen "kapacitans".
Komponenten "spole" har egenskapen "induktans".
Komponenten "motstånd" har egenskapen "resistans".

Men såklart kan även andra komponenter, exempelvis en rak ledare, ha såväl kapacitans som induktans och resistans, mer eller mindre uttalat beroende på frekvens och annat.

**Comment by fnadde42** [comment]
Ok, om vi håller oss till @sm5phu's förslag så är jag nöjd. Jag yrkar att vi öppnar ett separat ärende för att gå igenom och granska så att de föreslagna "reglerna" efterföljs.

**Comment by sa0mad** [comment]
Nu mer åtgärdad.
