### ISSUE TITLE
"…person, egendom eller husdjur."

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#256]
Är listan `person, egendom eller husdjur` tagen från något auktoritativt dokument? _Husdjur_ bör nog annars bytas ut till t.ex. _natur_ eller _djur_.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/9e5d5945fb4a3102f024f6c62da9e875dbe6435e/koncept/chapter12-2.tex#L110

**Comment by SM7NTJ** [comment]
Ja listan är tagen från föreskrifterna. I den äldre ELSÄKFS 2004:1
En starkströmsanläggning skall uppfylla de allmänna 
säkerhetskraven i 3 kap. Den skall vara utförd enligt god 
elsäkerhetsteknisk praxis, så att den ger betryggande säkerhet 
för personer, husdjur och egendom mot skada till följd av el. 

I ersättaren ELSÄKFS 2008:1 är skyddskraven uppdelade på flera paragrafer men innebörden är lika.

2kap 1§ En starkströmsanläggning ska vara utförd enligt god elsäkerhets- teknisk praxis så att den ger betryggande säkerhet mot person- eller sakskada på grund av el.

3kap 2§ En starkströmsanläggning ska vara utförd så, att personer och husdjur skyddas mot elchock som kan uppstå vid direkt beröring av spänningsförande delar eller av utsatta delar som blivit spännings- förande genom ett fel, det vill säga indirekt beröring.

(Som kuriosa kan nämnas att som husdjur räknas djur som ingår i din försörjning. D.v.s vanlig katt, hund eller annat djur som är sällskapsdjur ingår egentligen inte. Livestock (boskap eller husdjur) översattes till husdjur i den svenska översättningen av de harmoniserade föreskrifterna)
