### ISSUE TITLE
Bör reapeater-tabeller innehålla motsvarigheten i det gamla systemet för beteckning av kanaler?

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#259]
Ser att tabellerna bara innehåller det nya systemet. I Bli Sändaramatör så har tabellen den nya och den gamla beteckningen för kanalerna. Fördelen med det är att det är lätt att se vilken frekvens "gubbarna" snackar om. Nackdelen att ha med de gamla är att folk kanske fortfarande väljer att använda dom gamla istället för dom nya.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/1b72f194a3a20ff00ad96a6f4cf35ea92dc03772/koncept/appendix-i.tex#L41-L47

![screenshot from 2017-10-31 11-30-16](https://user-images.githubusercontent.com/1107419/32219595-f7aff21c-be2e-11e7-8ecb-a9d741b45b3b.png)

**Comment by sa0mad** [comment]
Jag tycker gott att vi kan ha med den gamla. Det bör finnas en passus om gamla och nya systemet, men med explicit listning tror jag det blir tydligt och bra referens.

**Comment by tfritzon** [comment]
+1

**Comment by sikvall** [comment]
Det gamla systemet måste vara med också. Folk refererar till repeatrarna som "RU4" och "RU5X" på radion fortfarande, har inte hört en människa använda det nya systemet på 70cm i alla fall.

**Comment by sa0mad** [comment]
Efter diskussion var vi enhälliga om att vi skall komplettera med det gamla systemet. Det fyller ett uppenbart syfte.

**Comment by sa0mad** [comment]
Åtgärdad.
