### ISSUE TITLE
Kapitel 3.10.1

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#264]
Kommentar från läsare: "Påstås att man kan göra IIR-filter med linjär fas. Något jag aldrig hört talas om. Däremot gäller förklaringen (någorlunda) om författaren avser FIR-filter."

**Comment by fnadde42** [comment]
Kan vara fel i den optiska inläsningen. Bra att det fångades upp.

**Comment by sa0mad** [comment]
Det är ett orginalfel från mitt tangentbord. :)
