### ISSUE TITLE
Referens till .git/refs/heads/master fungerar inte i andra grenar än master

### ISSUE THREAD

**Issue by sikvall** [SverigesSandareamatorer/SSA-Akademin#269]
Byggsystemet refererar en fil i en specifik gren, nämligen master. 
I grenen layout blir detta trasigt och t.ex. Travis CI får problem.

`Package catchfile Error: File `.git/refs/heads/master' not found.`

**Comment by fnadde42** [comment]
Det här är ett känt problem sedan ett tag #159 

Har gjort två lösningsförslag här: https://github.com/SverigesSandareamatorer/SSA-Akademin/issues/159#issue-256645632

**Comment by sa0mad** [comment]
Om HEAD fungerar även för den layout-grenen så är det en lösning som kan fungera. Vi vill nog inte få en massa shell-scripts som funkar olika på olika miljöer i spannet Linux, Windows och Mac och en massa olika saker att ladda ned.

**Comment by sikvall** [comment]
En enkel workaround är att vi bara stänger av det eller stubbar den för layoutgrenen och slår på den igen vid merge till master. Det är funkis för mig eftersom layout inte är en officiell gren där folk skall bygga från och referera till i alla fall.

**Comment by sa0mad** [comment]
Ja, OK, det duger nog för stunden. Helst vill man väl ha någon form av automagi i det så vi inte råkar göra bort oss vid merge mot master, såsom det så gärna blir.

**Comment by sa0mad** [comment]
OK, jag experimenterade lite och nådde nästan fram. Den lösningen gör per automagi rätt med den branch man är i och kräver inget extra. Däremot lyckades jag inte integrera ihop de bitarna jag har, men de fungerar däremot som tänkt var för sig.

**Comment by fnadde42** [comment]
Stänger, då det är en kopia av #159
