### ISSUE TITLE
Kommentar 11: Kapitel 16.9 Sidhuvud texten går ihop

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#274]

**Comment by sikvall** [comment]
Åtgärdad, det finns säkerligen fler ställen. Åtgärdas genom att sätta en kortare version av rubriknamnet för just sidorubrikerna. Exempel:

`\section[Kortversion]{Den lite längre versionen som inte flödar snyggt}`

För att förenkla lades ett litet paket till i common.tex som heter titlesec.
