### ISSUE TITLE
Vissa rubriknivåer i Tufte saknas för layout. Dessa behöver vi återskapa.

### ISSUE THREAD

**Issue by sikvall** [SverigesSandareamatorer/SSA-Akademin#275]
Det finns inte rubrikdefinitioner för alla nivåer i tufte-book vilket gör att vi får en del konstigheter men det får vi fixa till. Jag föreslår ganska liten skillnad mellan section, subsection, subsubsection medan chapter skall vara ganska stor.

**Comment by tfritzon** [comment]
Är det mer än subsubsection som saknas? Det finns en rubriknivå som heter paragraph som kan ersätta subsubsection. Det ligger ett makro i koncept-tryck.tex som ser ut som:
\renewcommand{\subsubsection}[1]{\paragraph{#1}}

**Comment by sa0mad** [comment]
Ej längre relevant.
