### ISSUE TITLE
Kommentar 18: V används som variabel för spänning. Borde vara U

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#276]
### Avsnitt

2.11.4

### Version

0d96bced9dbd099217fd7d202c2492cd336700cb

### Kommentar

V används som variabel för spänning. Borde vara U.  P och I används (korrekt) för effekt och ström. Antingen U, P och I eller V, W och A.

**Comment by sikvall** [comment]
Håller med. Har ev. gått mig förbi.

**Comment by sa0mad** [comment]
Håller med. Låtom oss rätta.
