### ISSUE TITLE
Elektroner är inte jon

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#277]
Kapitel 8.3
HAREC a.7.3
"Jonosfären har fått namnet från begreppet jon, som är en laddad partikel till exempel en elektron."

Elektron är inte en jon. Detta är fel.
/NEJ

**Comment by sa0mad** [comment]
Jag håller med, det här är oerhört lätt att fixa så låt oss göra det.

**Comment by sikvall** [comment]
Reagerade på den också men missade gå tillbaka och ändra.

**Comment by sa0mad** [comment]
Åtgärdad.
