### ISSUE TITLE
Upphuggen mening vid beskrivning av troposfärisk vågutbredning

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#279]
Avsnitt `8.6.1`
Version `0d96bce`

> Denna del av atmosfären kallas för troposfär och vågutbredningen därför
> för troposfärisk vågutbredning.

Känns som meningen har redigerats och det nu saknas ord och/eller ordföljden hamnat fel.

Bättre alternativ
> Denna del av atmosfären kallas för troposfär och vågutbredningen benämns därför
> troposfärisk vågutbredning.

Medvetet valt bort "kallas" för att undvika repetition i texten.

**Comment by fnadde42** [comment]
Håller med om att meningen låter konstigt och att det verkar saknas ett ord. Tycker även ditt förslag låter bra. Yrkar för denna förändring.

**Comment by sa0mad** [comment]
Jag håller med. Bara att införa.
