### ISSUE TITLE
Formel för tre (eller fler) parallellkopplade induktorer saknas

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#286]
Avsnitt 3.1.7
Version 0d96bce

Sektionen om galvaniskt parallelkopplade induktorer har ett räkneexempel med två induktorer. Men inget exempel med fler induktorer.

Eftersom formeln för två komponenter

    L = L1*L2 / (L1+L2)

inte går att direkt översätta till tre komponenter

    L = L1*L2*L3 / (L1+L2+L3)

tycker jag det kan vara bra att vara övertydlig med att man bör använda annan formel vid beräkning av fler komponenter.

    1/L = 1/L1 + 1/L2 + 1/L3
    L = 1/(1/L1 + 1/L2 + 1/L3)

Dessutom konsekvent med sektionerna med resistorer och kondensatorer som redan har räkneexempel med tre komponenter.

**Comment by SM7NTJ** [comment]
Det är väldigt ovanligt att man kan koppla tre induktorer i parallell utan att få en ömsesidig påverkan som påverkar resultatet. Därför finns egentligen inget behov av formel för flera induktorer i parallell. I  Bli sändaramatör finns formeln med för 2 eller flera parallellkopplade induktorer och vi kan i och för sig ändra texten så att formuleringarna blir mer likartade, men jag anser själv inte att det är nödvändigt.

Däremot behöver vi ändra uträkningen i exempel 2 där svaret felaktigt angetts till 28uH i stället för det riktiga 26uH.

Vi behöver även ändra den felaktiga formeln för i magnetiskt kopplade induktorer i parallell då den är felaktig.
1. om spolarna är kopplade så att de samverkar (L1*L2- M^2)/(L1+L2-2M)
2. om spolarna är kopplade så att de motverkar (L1*L2- M^2)/(L1+L2+2M)

**Comment by adbre** [comment]
> Det är väldigt ovanligt att man kan koppla tre induktorer i parallell utan att få en ömsesidig påverkan som påverkar resultatet. Därför finns egentligen inget behov av formel för flera induktorer i parallell.
> I Bli sändaramatör finns formeln med för 2 eller flera parallellkopplade induktorer och vi kan i och för sig ändra texten så att formuleringarna blir mer likartade, men jag anser själv inte att det är nödvändigt.

Jag går ännu kursen för att ta amatörradiocertifikatet och har ingen erfarenhet hur man brukar koppla.

Som studerande av amatörradiocertifikatet gillar jag att det är samma formel (byt bokstav) för att räkna ut parallella resistorer och induktorer samt seriekopplade kondensatorer. Det håller ned antalet formler jag behöver lära mig.

Däremot gillade jag inte att boken "Bli sändaramatör" oftast (och i sammanfattningsrutan) oftast ställer upp uträkningen med formeln (ersätt X med R, C eller L) `X = X1*X1/(X1+X2)`.
Därför, precis om jag skrev i orginalposten, felaktigt översatte detta till att räkna `X = X1*X2*X3/(X1+X2+X3)`.
Exempelvis 4 st 100 ohms resistorer räknade jag ut den totala resistansen till 250 000 ohm!
Det tog mig nästan två månader för mig att upptäcka att jag lärt mig fel.

Jag hade istället föredragit att lära mig `1/X = 1/X1 + 1/X2 + .... 1/Xn` då den alltid fungerar, oavset antalet komponenter.

Litar på din erfarenhet och köper ditt resonemang. Accepterar att mitt förslag lämnas utan åtgärd.
De ändringar du föreslår låter dock vettiga (och nödvändiga).

**Comment by SM7NTJ** [comment]
1/X = 1/X1 + 1/X2 + .... 1/Xn  är den formel som används i min undervisning oavsett R, L eller C.

 X = X1*X2/X1+X2 medför ofta att uträkningen ger fel svar då eleverna inte kommer ihåg prioriteringsreglerna. Att skriva formeln X = X1*X2/(X1+X2) med parenteser är mycket bättre då parenteser är nödvändiga för uträkningen, speciellt vid användning av formelräknare. 

Oavsett att vem som ger förslag på förbättringar så tittar vi på det hela med öppna ögon och för in rättelser och förtydligar uppgifter som kan misstolkas.

**Comment by sa0mad** [comment]
Fenomenet mutual coupling finns för R, L och C, men det är i allmänhet bara för L som man brukar behöva bry sig. 

Jag brukar understryka att det är samma formler, bara att för C är det omvända formler än för R och L. Ganska enkel minnesregel.

Självklart försöker vi ta vara på alla synpunkter som framkommer.

**Comment by SM7NTJ** [comment]
Formler för parallellkopplade induktorer nu korrigerade och införda.
Formel för parallellkoppling av fler än 2 galvaniskt kopplade induktorer införs inte.
Stänger ärendet
