### ISSUE TITLE
Konstig formulering "utbildats en praxis"

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#287]
Sektion 1.11
Version 0d96bce

> **Det har utbildats en praxis**, att referensvärdet vid jämförelse av signalnivåer
> i radiosystem ska vara en milliwatt (1 mW) utvecklad i en belastning med
> impedansen 50 Ω.

Min språkkänsla reagerar på den inledande satsen.
Borde istället lyda "Det har utvecklats en praxis".

**Comment by SM7NTJ** [comment]
Ändra enligt förslaget
