### ISSUE TITLE
Flera kapitel om EMF

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#292]
Boken innehåller flera olika kapitel med samma titel:

1.5 Elektromagnetiskt fält
1.5.3 Elektromagnetiska fält
11 Elektromagnetiska fält

Kapitel 1.5 och kapitel 11 har olika syfte. Vi borde förbättra strukturen här. Kanske bör vi ändra kapitelrubriker för att man lättare ska hitta rätt.

**Comment by sa0mad** [comment]
Håller med. Kapitel 11 är nytt och den intagna EMF supplementet.

1.5 och 1.5.3 är märkligt i sig, däremot menas olika saker mot 11.

11 borde reflektera EMF gränsvärden på ett rimligt sätt, för det är slarv att bara säga EMF om det.

1.5 borde heta elektromagnetiska vågor
