### ISSUE TITLE
Komplettering av Docker-image

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#3]
Docker-image behövs uppdateras för att omfatta alla beroenden som definieras i `BUILD.md` och där måste även instruktioner för att fixa en Docker-container läggas till.

**Comment by sa0mad** [comment]
Är den här öht aktuell så som vi bygger just nu? Om inte så kan vi väl stänga denna, eller uppdatera med det vi har från den använda byggmiljön.

**Comment by fnadde42** [comment]
Det här är något som @hin har koll på. Vi kan lägga den på is tills det blir aktuellt igen. Öppnas när någon känner för att göra den.
