### ISSUE TITLE
Vi behöver nytt exempel på provtext i avsnitt 16.17

### ISSUE THREAD

**Issue by SM7NTJ** [SverigesSandareamatorer/SSA-Akademin#300]
Vi behöver nytt exempel på provtext i avsnitt 16.17. Nuvarande exempel innehåller en mening som hänvisar till 2182kHz som frekvens för nödanrop.
bygge 445143b

.... ASCUNCION ÄR HUVUDSTAD I PARAGUAY, SOM LIGGER I SYDA-
MERIKA. **VID RADIOTELEFONERING UTGÖRES NÖDSIGNALEN AV
ORDET MAYDAY OCH SKALL OM MÖJLIGT UTSÄNDAS PÅ FREKVEN-
SEN 2182 KHZ.** QRV? MEANS ARE YOU READY? THE RECEIVER CON-
TROL SETTINGS SHOULD BE ADJUSTED AS INDICATED ON PAGE 3-4,
DATED 7/10 1994. QRT + @
(summa 277 teckenvärden)

**Comment by SM7NTJ** [comment]
Funktionen för radbrytning i LaTeX lägger i extra skiljetecken varför taktberäkning enligt nästa avsnitt inte stämmer. Den ursprungliga övningstexten inleddes med "lystring" i stället för de fyra punkter som finns nu.

Ska vi lägga en ny övningstext som en bild så att inte radbrytningar förändrar det beräknade teckenvärdet?

**Comment by sa0mad** [comment]
\texttt{} eller annan \text runt stänger av hyphenation.
