### ISSUE TITLE
Kommentar 24: Delutskriftsproblem

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#309]
### Avsnitt
1.1

### Version
Jag får inte delutskrift att fungera som t.ex. väljer sid 451 så skriver jag ut från sida 433. Provade att indexera utskriften med 18 som är sid felet men då blev allt konstigt och utskriften blev bara svarta rutor och läsligt. Så det måst nog vara något mer som är fel. Ring om ni vill ha mer info. 

### Kommentar
5f4dc35

**Comment by SM7NTJ** [comment]
Problemet verkar hänga samman med #251 och numreringen 1-18 som sedan börjar om igen från 1 när texten börjar.

Testade att skriva ut sidan 451 från webbläsaren, fick då sidan 433 utskriven. Ändrade till sidan 469 och fick sidan 451 utskriven.

Sidorna 1-18 finns två gånger vilket gör att bara de första 18 går att skriva ut utan krångel.

**Comment by sa0mad** [comment]
För online/utskrifts PDF föreslår jag att vi har gemensam sidnumrering.
@tfritzon kanske har en synpunkt om hur detta skall göras?

**Comment by fnadde42** [comment]
Jag yrkar på att sidnumreringen börjar ifrån förstasidan med nummer 1 och ökar för varje sida.

**Comment by sa0mad** [comment]
Vilket var det jag sa.
