### ISSUE TITLE
Sortera om filer och kataloger

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#31]
Just nu är det blandat innehållsfiler (t.ex. preface.tex) och arbetsfilter (t.ex. textifiering.txt) i katalogstrukturen. Jag föreslår att högsta nivån hålls så ren som möjligt samt att aktiva och inaktiva filer hålls isär.

**Comment by sa0mad** [comment]
Du föreslår helt enkelt att vi skall slutföra flytten av filer för att man skall hitta runt, låter vettigt. Jag tar en titt på det.

**Comment by sa0mad** [comment]
En första rejält städning är nu gjort och pushad.
