### ISSUE TITLE
Kommentar 25: Bild 1.26: AM-signalens amplitud för 0V är olika vid olika tider

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#312]
### Avsnitt
1.8.4

### Version
6b7b9de

### Kommentar
Bild 1.26: AM-signalens amplitud för 0V är olika vid olika tider. I första segmentet (kontant LF-spänning) visas medelamplitud vid 0V, vilket är rimligt I andra segmentet (sinusformad LF-spänning) visas 0V ungefär som tidigare Felet ligger i tredje segmentet - digital modulation. Där är 0V något annat. I AM är den helt utsläckt signal, i FM är frekvensen ungefär samma som lägsta frekvensen från sinus-LF. Jag skulle tycka det var mer pedagogiskt att illustrera LF-signalen, då den är graderad i volt, ändra spänningsnivåerna till full positiv och full negativ spänning, samma amplitud i LF som ljudsignalen. Det skulle då vara spänningsnivåer som motsvarar t.ex. RS232-signaler. Dvs. dra ner 0:an i digitalsignalen till negativ spänning.

**Comment by SM7NTJ** [comment]
För digital signalering via AM verkar det förekomma två vanliga metoder att modulera bärvågen.
OOK (on-off keying) vilket är det som nu visas i bild1.26 samt ASK amplitude shift keying.

I det första fallet, on-off keying, så får bärvågen full amplitud vid insignal "1" och noll i amplitud vid insignal "0"
I det andra fallet, amplitude shift keying så får bärvågen full amplitud vid insignal "1" och minimum amplitud vid  insignal "0"

Föreslår att vi stänger detta issue

**Comment by phieri** [comment]
Stänger ärendet i enighet med ovan samt separat mejltråd.
