### ISSUE TITLE
Kommentar 26: Bild 2.45 ser ut som TTL-logik, och tämligen lik bild 2.46

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#313]
### Avsnitt
2.8.3

### Version
6b7b9de

### Kommentar
Bild 2.45 ser ut som TTL-logik, och tämligen lik bild 2.46

**Comment by sa0mad** [comment]
@SM7NTJ Anser du denna åtgärdad nu?

**Comment by SM7NTJ** [comment]
Åtgärdad med ny bild
