### ISSUE TITLE
Kommentar 28: "En mikroprocessor är en avancerad LSI-krets"

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#315]
### Avsnitt
2.9.4

### Version
6b7b9de

### Kommentar
Det står "En mikroprocessor är en avancerad LSI-krets", och innan hänvisas LSE som tiotusental transistorer. De minsta mikroprocessorer idag är i storleksordningen ARM Cortex-M0, vilket är omkring 100k transistorer, exkl. perferienheter och minne. Blir lätt några miljoner transistorer. Jag hävdar att en mikroprocessor idag borde klassas VLSI http://www.tomshardware.co.uk/answers/id-2136898/transistor-count-arm.html

**Comment by sa0mad** [comment]
Nja, många av de mikroprocessorerna som fanns då finns kvar, och sedan har de vuxit och vuxit.

Samtidigt har begreppen LSI ch VLSI slutat att användas annat än historiskt då nästan allt vi använder idag är VLSI.

**Comment by pengi** [comment]
Mm. Kanske finns någon bättre benämning på det, att inte använda LSI-begreppet alls?

Om man kollar på vad som används idag av amatörer så är det nog oftast arduino, dvs. en ATmega328. Hittar inte några gissningar på transistorantal, men antar att det inte rör sig om mindre än ATmega128, vilket gissas vara uppåt 1M:

https://www.embeddedrelated.com/showthread/comp.arch.embedded/14362-1.php

Kanske bara ändra meningen till något likt detta, och stryka LSI-delen helt?

> En mikroprocessor kan programmeras (kopplas upp) ”mjukvarumässigt” inte bara för ett ändamål utan för många olika.

**Comment by sa0mad** [comment]
Jag funderar på om inte LSI/VLSI skall tonas ned eller helt tas bort.
@sikvall @SM7NTJ Har ni något klokt att tillägga?

**Comment by SM7NTJ** [comment]
Jag tror att vi tar bort det mesta om LSI/VLSI

Under Intergrationsgrad, ta bort allt utom nedanstående:
En integrerad krets är uppbyggd på en basplatta av halvledarmaterial --
ett chip.
På plattan framställs, med fototeknik eller etsning, kompletta eller nästan
kompletta dioder, transistorer, resistorer och kondensatorer.
Metoden, som kallas planarteknik, medger att många komponenter kan få plats på
samma platta.
Den snabba utvecklingen av produktionsmetoder för integrerade kretsar gör
alltmer avancerade system möjliga och dessutom på allt mindre utrymme.

Under Digitala IC ersätt andra stycket med:
Dagens digitala system styrs av en eller flera mikroprocessorer.
Funktionen programmeras (kopplas upp) ''mjukvarumässigt'' varför det är lätt att
ändra hur kringutrustningen inhämtar och avger information -- kommunicerar.

**Comment by sikvall** [comment]
Jag tycker vi förpassar det till en historisk parentes och fokuserar på 
nutid. Alltså ha kvar en kortfattad förklaring utan för mycket 
ordbajseri och förklara att det mesta i dag är VLSI-teknik.

/Anders

**Comment by sm5phu** [comment]
Hoppsan, det där är redan ändrat. Nu står

_En mikroprocessor är en avancerad krets som kan programmeras (konfigureras) mjukvarumässigt inte bara för ett ändamål utan för många olika._
