### ISSUE TITLE
Kommentar 29: Tycker Kirchhoffs lagar har blivit lite konstiga.

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#316]
### Avsnitt
3.1.2

### Version
6b7b9de

### Kommentar
Tycker Kirchhoffs lagar har blivit lite konstiga. 1:a lagen är visserligen nära. Men den säger att summan av alla strömmar in och ut från framma punkt (eller område) är lika med 0. Alternativt att summan av alla strömmar in ska vara lika med summan av alla strömmar ut. Det är visserligen vad den visar att in-strömmen I är summan av alla delströmmar ut. Det nämns dock inte att det kan vara flera inströmmar, om man ska referera till kirchhoffs lag. 2:a lagen är dock helt fel. Det är skrivet att spänningen över paralellkopplade komponenter är samma. Det är visserligen helt sant, men det är inte det kirchhoffs 2:a lag säger. Kirchhoffs 2:a lag säger att summan av alla spänningar i en slinga är lika med 0V. (T.ex. ett batteri, motstånd och lysdiod får +3.7V i batteriet, -1.7V i motståndet, -2V i lysdioden). Dvs. den behandlar seriekopplade komponenter i en loop. https://en.wikipedia.org/wiki/Kirchhoff%27s_circuit_laws#Kirchhoff.27s_voltage_law_.28KVL.29

**Comment by SM7NTJ** [comment]
Kirchhoffs lagar tas upp i avsnitt 1.1.12
Hänvisningarna till Kirchhoffs lagar i punkt 3.1.2 visar på en tillämpning av lagarna, inte att det är  Kirchhoffs lagar.
Hänvisningen kan skapa missförstånd och tas därför bort.
