### ISSUE TITLE
Kommentar 30: nätet/ledaren mellan kondensatorerna blir flytande

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#317]
### Avsnitt
3.1.6

### Version
6b7b9de

### Kommentar
Borde nämna något om att nätet/ledaren mellan kondensatorerna blir flytande, och potential kan byggas upp där. Det gör att man kan komma utanför kondensatorns spänningstålighet. Ofta är det bra att parallelkoppla kondensatorerna med ett högohmigt motstånd för att mitten-nätet inte ska flyta

**Comment by sa0mad** [comment]
I vilka sammanhang förekommer det att man bygger upp höga potentialer? Dessutom är det nog fel ställe att påpeka det, här handlar det om den mer teoretiska beräkningen.

**Comment by pengi** [comment]
jag har mest blivit varnad för det själv, så det är information i andra hand.

Men tänk dig följande:
# Du har två kondenstatorer i serie, med tre nät, dvs. tre potentialer: Va - Ca - Vb - Cb - Vc. Kapacitansen på kondensatorerna är samma. Allt är urladdat, Dvs Va = Vb = Vc = 0V
# Du höjer potentialen på Vc till 20V
# Vb kommer följa med till 10V genom kapacitiv spänningsdelning
# Tänk dig att du har ett läckage genom Ca, modellerat som en paralell resistor, som inte existerar i samma storleksordning i Cb. Kan vara p.g.a. fukt, någon går in och petar på, olika egenskaper i kondensatorerna (olika individer)
# Vb kommer långsamt sjunka till 0V
# Du sänker Vc till 0V igen
# Vb kommer sjunka med 10V, genom kapacitiv spänningsdelning, dvs. hamna på -10V

Om Ca och Cb är elektrolytkondensatorer kommer detta hamna utanför spec.

Men du har nog rätt... Det kanske är överkurs att skriva det där... Tänkte mer att det är där folk kommer kolla för att hitta hur man räknar på kapacitanser när dom bygger något, så sådana kommentarer kan vara intressanta, då jag gillar Koncept som en praktisk uppslagsbok i elektronik, där wikipedia eller andra är teoretiska på ett annat sätt.

**Comment by pengi** [comment]
Jag har mest hört det från några olika källor, och därför har jag hållit det så själv när jag byggt. Så jag har tagit det som något vedertaget. Men hittar inte referenser nu när jag söker, så skippa det... Men ändock intressant :)

**Comment by sa0mad** [comment]
Koncept försöker innehålla huvudsak teori och med en del praktik. Dock, just det avsnittet försöker täcka den rent teoretiska delen så man förstår hur det ska räknas.

Har du ingen halvledare med så kommer du max få den högsta spänningen du har, och då skall alla dina komponenter klara den spänningen, om du inte kan motivera väl att spänningen blir lägre, och då väljer man spänningstolerans därefter. Det kan säkert stå någonstans, men just det där är inte rätt plats, det är generiskt applicerbart och inte enbart i en kapacitiv spänningsdelare. Det hör mer hemma vid kraftaggregat och elsäkerhet.

**Comment by sa0mad** [comment]
Just att försöka simulera icke-polariserad konding med två elektrolyter är alltid något som ger mig rysningar längs med ryggen, så det är ett special-fall. Jag tror vi har betydligt mer att klara av innan vi kommer till just det fallet.

Jag stänger just den här issuen, sen kanske vi får tillfälle att återkomma till ämnet tids nog.

**Comment by fnadde42** [comment]
Vi borde inte stänga ärendet ifall vi ämnar att lösa det vid ett senare tillfälle. Öppna det och låt det ligga och skvalpa i botten på issue-listan tills vi tar tag i det.

**Comment by SM7NTJ** [comment]
Det finns ett antal rekommendationer på nätet där seriekopplade kondensatorer bör parallellkopplas med högohmiga motstånd för att undvika problem med den totala spänningståligheten.

Dessa rekommendationer gäller dock endast när de seriekopplade kondensatorerna var för sig inte tål kretsens maximala spänning.

Vid "fel" i en kondensator riskerar då nästa kondensator att få en spänning som överstiger kondensatorns maximala.

Stänger denna issue igen.
