### ISSUE TITLE
Ström i glättningskretsar (likriktare)

### ISSUE THREAD

**Issue by pengi** [SverigesSandareamatorer/SSA-Akademin#318]
### Avsnitt
3.3.2
### Version
6b7b9de
### Kommentar
Borde stå något om strömmen när man glättar, t.ex.:

Tänk på att all ström kommer dras endast när glättningskondensatorn håller på att laddas upp. Strömmen dras således mest under första halva halvvågen, vilket gör att nätaggregatet kommer att lasta elnätet kapacitivt. Strömkurvan kommer även få skarpa flanker, vilket kan ge upphov till störningar.

### Referens
En som sammanfattar ganska bra:
https://electronics.stackexchange.com/a/104803

**Comment by sa0mad** [comment]
En helvågslikriktare kommer ha en förstagradskompensering eftersom den kommer lasta första halvvågen på den andra polariteten, vilket kompenserar den kapacitiva lasten från den positiva halvvågen. Resultatet kommer arta sig mycket mer resitivt än för en halvvågslikriktare.

Däremot kommer man gladeligen skapa övertoner från den PWM-våg i ström som är från när man börjar ladda till toppen av vågen, grovt räknat.

**Comment by SM7NTJ** [comment]
Det är riktigt att det kan bildas övertoner vid likriktning. Vid halvvågslikriktning bildas jämna övertoner och vid helvågslikriktning udda övertoner. Det kan även bildas en besvärlig likströmskomponent.

Vid FFT analys av övertonerna med en "elkvalitets analysator" kan diverse underliga kurvformer beskådas.

En belastad helvågslikriktare med glättningskondensator drar dock inte ström från elnätet enbart när spänningen överstiger kondensatorns spänning. 

Det refererade exemplet är ganska bra, dock är kurvan för Ic felaktig då Ic i verkligheten byter riktning hela tiden. När kondensatorn laddas upp flyter en ström in i kondensatorn, när kondensatorn sedan laddas ur går strömmen i andra riktningen vilket helt utelämnats i exemplet.

Den totala bilden av hur transformator, likriktare, kondensator, stabilisering och last samverkar och återverkar på elnätet är komplicerad. Detta gäller både vid enkla seriereglerade kraftaggregat och för primärswitchade kraftaggregat. Klart är att det kan bildas övertoner och störningar vid ogenomtänkta konstruktioner.

Stänger issuen då en fördjupning i ämnet inte passar in i koncept.

**Comment by pengi** [comment]
Hur går strömmen i en helvågslikrikte när spänningen ut från transformatorn har lägre belopp än spänningen på kondensatorn och kondensatorn driver lasten då? Detta om den inte endast går i pulser då beloppet på spänningen från transformatorn överstiger kondensatorspänningen?

Ic byter inte riktning hela tiden, då det är strömmen från likriktarbryggan till kondensatorn. Den kommer dock från olika vägar genom likriktarbryggan. Det är just det som gör en likriktare; att den likriktar.

Däremot kommer den byta riktning ut från transformatorn. Det stämmer, men inte efter likriktarbryggan. Där är den samma.

Men när strömmen byter riktning ut ur transformatorn (mellan transformator och likriktarbrygga) så är det en följd av att spänningen också har bytt polaritet, så effekten som dras från elnätet är positiv och ligger till betydande del före spänningstoppen, vilket gör en reaktiv last med övertoner.

Det finns till och med specifika IC-kretsar för att switcha signalen efter en likriktarbrygga för att få ett DC-led som inte ger dessa störningar tillbaka på elnätet:
http://www.ti.com/lit/ds/symlink/ucc28063a.pdf

Då vi pratar om störningar, och hur vi avhjälper detta, liksom hur man designar nätagg. Förtjänar inte detta i alla fall en kommentar, då det faktiskt ger störningar på elnätet?

**Comment by SM7NTJ** [comment]
Jag föreslår att du gör en laboration med en transformator, likriktarbrygga, kondensator och belastning kopplade som en sluten krets.

I kretsen kopplar du in tre mätpunkter för ström.
Punkt 1 i plusledaren mellan likriktarbrygga och anslutningen för kondensatorn.
Punkt 2 i ledningen mellan plusledaren anslutning och kondensatorn.
Punkt 3 i plusledaren till lasten.

Strömmen i punkt 1 kommer alltid att vara positiv och består av en  ström vars värde är summan av belastningsströmmen och kondensatorns uppladdningsström.

Strömmen i punkt 2 kommer att växla i riktning i takt med kondensatorns upp- och urladdning. Den är positiv när kondensatorn laddas upp och negativ när kondensatorn laddas ur.

Strömmen i punkt 3 kommer att vara positiv. Den består av dels av strömmen direkt från likriktaren och strömmen från kondensatorn. Mellan likriktaren och kondensatorn sker en periodisk lastdelning där likriktaren och kondensatorn tillsammans och var för sig driver en ström genom belastningen.

Laborationen brukar kopplad till ett flerkanals oscilloskop för strömvisning ge en AHAH-upplevelse gällande hur strömmarna i verkligheten flyter i kretsen.

Strömmen i punkt 1 brukar bli i storleken den dubbla mot belastningsströmmen.

Vi har inget avsnitt i koncept som behandlar dimensionering och design av nätaggregat där texten kan läggas in.
Jag kommer dock att ta en funderare på om det går att skriva in det någonstans i avsnitten om störningar.

**Comment by pengi** [comment]
Strömmen som tittas på är just Punkt 1.

Men som du säger så är det lite av en Ahah-upplevelse när man kollar på det. Så det är just störningsaspekten jag tänker på, inte så mycket dimensionering. Så det låter bra.

Det jag vill motverka med kommentaren är folk som tycker att dom har koll och bygger ett nätagg på några hundra W, om inte någon kW, för att driva ett slutsteg, och inte tro att den stör, för den inte är switchad.

**Comment by sa0mad** [comment]
Det klassiska sättet att minska störningarna från diodklipplningarna är kondensatorer direkt över dioderna, så nära upp på dem som bara möjligt. Detta kan man nämna direkt där och sedan även referera till vid störningsavsnittet. Ett rejält nätfilter hjälper sekundärt till.
