### ISSUE TITLE
Kommentar 32: Gällande halvledare

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#321]
### Avsnitt
1.1.4

### Version
3274342

### Kommentar
Gällande halvledare. En odopad (Oförorenad) halvledare leder inte vid rumsteperatur, men vid högre temperaturer kan de göra det. Tänker mest att det heter dopning, och man förorenar materialet. För att hålla terminologin rätt 

Exempelförändring: "En ren kristall av mineralen germanium[Ge] eller av kisel[Si] leder inte elektrisk ström, att de nästan leder är en egenskap utnyttjas i halvledarteknik. Om man förorenar kristallerna genom att föra in en annan typ av atomer med en mer eller en mindre valence elektron, detta kallas dopning, så blir de i någon mån elektriskt ledande." etc :)

Längre ner under "P-ledning", är inte helt säker men tror det kallas P- och N- typ. Bör dubbelkollas tänker jag. Ändring på det: "Man talar om att N-typ halvledare har majoritetsladdningsbärare i form av elektroner. 

Gällande P-Lening, kanske lägga in en intro pss där hål förklarars kort. Förslag: "När man talar om P-typ halvledare så har de majoritetsladdningsbärare i form av hål, det vill säga avsaknaden av elektroner i valencebandet." (Osäker på hur mycket man bör skriva, men kanske borde skriva ut hela kapitlet mer)

**Comment by SM7NTJ** [comment]
En odopad kristall av mineralen Germanium har konduktiviteten 2,17. Rent Kisel har ännu sämre konduktivitet 4,35x10^-4. Ämnena brukar vid rumstemperatur ses som isolatorer även om en svag läckström kan uppmätas. (Koppar har som jämförelse konduktiviteten 59,6x10^6)

Kristaller av dessa ämnen blir halvledande först då de dopas med andra grundämnen som till exempel arsenik, antimon, indium eller gallium. Den halvledande förmågan är inte nämnvärt beroende av temperaturen utan av inblandningen av andra ämnen. Detta gäller upp till cirka +100 grader för germanium och till +150 grader för kisel sedan sker en växling i dominans mellan majoritetsbärare och minoritetsbärare.

Det sker även andra förändringar i ämnena med stigande temperatur.

Att införa nya begrepp och djupare förklara hur transporten av laddningsbärare sker i övergångsskikten i halvledarmaterial får jag anse ligger utanför målet med Koncept.

Föreslår att vi lämnar förslaget utan åtgärd

**Comment by SM7NTJ** [comment]
Hoppsan, fel blev det.
I Koncept står det att 
_En ren kristall av mineralen germanium eller av kisel leder inte elektrisk ström. Båda dessa mineral är därför isolatorer._
Det här ska vi ändra på då det inte är riktigt, Vi måste även hålla isär begreppen **halvledande** och **halvledare**.
Båda ämnena är halvledande vid rumstemperatur där germanium har konduktiviteten 2,17 och kiselkisel 4,35x10^-4. I äldre litteratur står det att en svag läckström kan uppmätas genom ämnena.
Ledningsförmågan för ämnena påverkas av temperatur då högre temperatur medför ökad atomrörelse.
För att kunna använda ämnena som halvledare behöver de först dopas med andra grundämnen som till exempel arsenik, antimon, indium eller gallium.

När germanium och kisel dopats förändras till viss del det temperaturberoende beteendet.
Den halvledande förmågan är inte nämnvärt beroende av temperaturen utan av inblandningen av andra ämnen. Detta gäller upp till cirka +100 grader för germanium och till +150 grader för kisel sedan sker en växling i dominans mellan majoritetsbärare och minoritetsbärare.

Att införa nya begrepp och djupare förklara hur transporten av laddningsbärare sker i övergångsskikten i halvledarmaterial får jag anse ligger utanför målet med Koncept.

Föreslår att vi lämnar andra delen av förslaget utan åtgärd

**Comment by sm5phu** [comment]
Jag tycker inte detta är riktigt bra ännu. I kapitel 1.1 står om germanium och kisel:

"Om några atomer av ett främmande material som till exempel arsenik, antimon,
indium eller gallium blandas in _dopas_ i deras kristallstruktur, så blir
de i till viss del elektriskt ledande -- de blir halvledare."

Germanium och kisel är varken ledare eller isolatorer. De tillhör i sin rena odopade form en grupp grundämnen med speciella egenskaper som kallas halvledare. De blir alltså inte halvledare när de dopas, de är halvledare redan från början.

Jag skulle vilja formulera om avsnittet enligt följande:

"Om några atomer av ett främmande material som till exempel arsenik, antimon,
indium eller gallium blandas in _dopas_ i halvledarnas kristallstruktur, ökar deras  
elektriska ledningsförmåga."

**Comment by SM7NTJ** [comment]
Kisel och germanium tillhör gruppen **halvledande** ämnen, det vill säga att de har en viss förmåga att leda elektrisk ström, när de inte är i _kristallinisk form._

I _kristallinisk_ form formar kisel och germaniumatomerna en "matris" där de lånar elektroner av varandra så att valensskalet blir fullt med åtta elektroner, ämnena leder då inte elektrisk ström.
Det vill säga de är isolatorer.
(utan yttre påverkan som värme eller ljus som kan bryta loss elektroner till ledningsskiktet)

När kisel eller germanium dopas blir de **halvledare** då det beroende på ämne som tillförts genom dopning bildats ett underskott eller ett överskott av elektroner som gör att en elektrisk ström kan flyta genom ämnet. När ämnena väl är halvledare förändras därför deras elektriska egenskaper.  

Jag betonade **halvledande** och **halvledare** i texten ovan för de är de begreppen som vi behöver hålla isär.

I nuläget tror jag att texten i Koncept stämmer hyfsat med teorin, men det är bra om vi kan hitta en annan förklaring eller förtydning som inte lyfter nivån mot höga teoretiska höjder.

Läs gärna igenom hela textstycket i koncept och se om ni har förslag på text

**Comment by SM7NTJ** [comment]
Har nu hunnit titta även på modernare källor.
Merparten kallar ämnena halvledande så det ska vi ändra i inledningen av texten.
Är det något annat vi ska ändra på, förutom enligt förslag från @phu ?

**Comment by sm5phu** [comment]
Jag tror det finns risk för förvirring om vi försöker göra skillnad mellan "halvledare" och "halvledande ämnen". Wikipedia verkar inte göra någon distinktion mellan dopade och odopade halvledare, båda är rätt och slätt "halvledare". Men vad som står i Wikipedia får man ju ta med en nypa salt ibland, så jag gick till Nationalencyklopedin, där Olof Beckman, professor i fasta tillståndets fysik, beskriver begreppen så här:

"halvledare, material vars elektriska ledningsförmäga ligger mellan ledares och isolatorers.
Halvledare är av grundläggande betydelse inom elektroniken och ingår i dioder, transistorer och övriga halvledarkomponenter.
Välkända halvledare bland grundämnena är de trevärda (se oxidationstal) germanium och kisel varav kisel är mest använt. En stor och viktig grupp är de så kallase III-V-föreningarna mellan ett trevärt element (gallium, indium) och ett femvärt element (kväve, forsfor, arsenik, antimon), till exempel galliumarsenid (GaAs) och indiumantimonid (InSb). Vidare finns II-VI-föreningar, till exempel kadmiumsulfid (CdS) och zinksulfid (ZnS). Andra halvledare är blysulfid (PbS) och vismuttellurid (Bi2Te3).
Den elektriska ledningsförmågan är en materialegenskap med mycket stor variationsbredd. Hos halvledarna kan den ändras med dopning i ett brett intervall (10E-6 till 10E3 (ohm*m)E-1). Goda metalliska ledare har typiskt (10E5 (ohm*m)E-1) och goda isolatorer, till exempel diamant, svavel, kvarts, under 10E-10 (ohm*m)E-1 utläses "per ohmmeter".
Skillnaden i ledningsförmåga mellan halvledare och metaller beror framför allt på skillnaden i mängden fria laddningsbärare. I till exempel koppar motsvarar antalet laddningsbärare en elektron per atom medan halvledarna endast har en mycket ringa bråkdel av detta antal tillgängliga för elektrisk ledning. Karakteristiskt för halvledare är emellertid att antalet laddningsbärare ökar avsevärt med temperaturen. Detta ger en stor ökning i ledningsförmågan, vilket bland annat kan användas i komponenter för temperaturmätning. Ledningsförmågan hos en metall minskar vid ökande temperatur beroende på att elektronernas rörelse störs av en ökande värmerörelse hos atomerna. För halvledare spelar värmerörelsen underordnad roll." 

NE verkar alltså anse att halvledare är "halvledare" även i sin rena odopade form. Eller så läser jag med skygglappar, vilket i och för sig inte är uteslutet :-)

**Comment by SM7NTJ** [comment]
Då är vi överens om det. Något annat vi vill ändra på?
Jag har redigerat texten för halvledare och tagit bort sista stycket om temperaturbeteendet.

_Några grundämnen har en elektrisk ledningsförmåga som ligger mellan gränsvärdena
för att kallas elektriska ledare eller isolatorer.
Dessa ämnen tillhör gruppen halvledare och har en elektrisk ledningsförmåga som
varierar med ämnets struktur, renhet och temperatur.

En ren kristall av mineralen germanium [Ge] eller av kisel [Si] bildar ett
kristallgitter där atomerna binds till varandra med kovalenta bindningar.
Ämnena delar sina fyra valenselektroner med fyra andra atomer så att det
bildas en full oktett med åtta elektroner i valensskalet.

Då valensskalet innehåller åtta elektroner är det fullt, det finns inga fria
elektroner och ämnet leder inte elektrisk ström.
Båda dessa mineraler kan därför i denna form ses som isolatorer.
(\emph{intrinsisk halvledare})

Om några atomer av ett främmande material som till exempel arsenik, antimon,
indium eller gallium blandas in, (\emph{dopas in}), i kristallstrukturen så
förändras egenskaperna och den elektriska ledningsförmågan ökar tusenfalt._
