### ISSUE TITLE
Odämpad svängning

### ISSUE THREAD

**Issue by pengi** [SverigesSandareamatorer/SSA-Akademin#322]
### Avsnitt
3.6.1
### Version
fa02fb8
### Kommentar
Odämpad svägning är när svägningen är förlustfri, inte att summan av tillförd och dämpad energi är samma.

Exemplet som ges hänvisar även till att det är pulsat tillskott på energi som inte sker samtidigt som den minskar.

> Stöt nu till pendeln varje gång, som den pendlar tillbaka. För lika stora utslag varje gång – en odämpad svängning – fordras det upprepade energitillskott som precis kompenserar förlusterna.

Odämpade och dämpade har inte ens samma frekvens.

https://sv.wikipedia.org/wiki/Harmonisk_oscillator#D.C3.A4mpad_harmonisk_oscillator

Jag skulle ändrat till något likt:

> En teoretisk pendel som är helt frikton och förlustfri kallas odämpad och kommer behålla sin amplitud över tid. Alla praktiskta pendlar har dock förlust och kräver att man även tillför energi för att behålla amplituden.

En liten bonus är att en pendel som exemplet visar är inte en harmonisk svägning, men appriximeras till det för små vinklar, detta för att då kan man appoximera sin(v)=v och cos(v)=1

**Comment by sa0mad** [comment]
Nja, det finns ett specialfall som faktiskt är mycket viktigt där just summan av tillförd och dämpad energi är samma, och det kallas oscillatorer. Det är grundvillkoret jämte fasvillkoret för en oscillation och är faktiskt det enda fallet där det förekommer, för man har alltiid förluster.

**Comment by pengi** [comment]
Hum... det kan diskuteras, då odämpade svägningen är mer av en matematisk modell. Frågan är om man kan ansätta dämpande kraften till 0 genom att säga att dämpning+tillförd kraft= 0 då tillför kraft=-dämpning.

https://en.wikipedia.org/wiki/Harmonic_oscillator#Simple_harmonic_oscillator
> A simple harmonic oscillator is an oscillator that is neither driven nor damped.

Exemplet hänvisar dock till en modell med en pendel som puttas under en kort puls under en period, så att tillförda kraften över en period är samma som dämpande. Detta gör att momentant är kraften helt olika då tillförda kraften alltid är 0 då fingret inte rör pendeln, och därför bör påverka frekvensen jämfört med odämpade fallet, även om amplituden håller sig konstant.

Vill man komma bort ifrån att krångla till det så kan man ta bort begreppet odämpad svägning, och bara ha kvar meningen "För lika stora utslag varje gång fordras det upprepade energitillskott som precis kompenserar förlusterna."

**Comment by sa0mad** [comment]
Odämpad svängning är ett grundläggande koncept som används, och det är konsekvent fel i så mycket literatur att vi kan inte ändra här, utan snarare bara förmedla vad begreppet innebär. Att det finns en balans mellan tillföröd och bortförd energi är relevant och användbart.

Att det kanske borde fått heta något annat är väl korrekt, men nu heter det så av hysteriska/historiska skäl. Vårt fokus måste ligga på att göra det begripligt och dessutom göra det begripligt på ett användbart sätt, och då är balansen mellan energier det relevanta, inget annat.

**Comment by pengi** [comment]
Jag accepterar det inte riktigt ändå... Det är just exemplet med att putta pendel som är det jag mest reflekterar över.

Så jag gjorde en liten simulering i python, som gav följande resultat:

![svagning](https://user-images.githubusercontent.com/1087673/32992909-f70b7918-cd50-11e7-85e3-dd9508cdcc55.png)

Här har jag tre grafer:
- grön - odämpad svägning
- röd - dämpad svägning
- blå - dämpad svägning, men med "putt" varje gång den passerar y=0, till den grad att summan av dämpningen över en period är 0

Det man ser tydligt är att blå har annan frekvens, vilket gör att man inte kan få fram frekvensen på denna pendel genom att använda ekvationerna för odämpade svängingen, utan måste kolla på dämpade fallet, eller mer simulera. Därav skulle jag inte kalla denna pendel med "putt" för odämpad, utan just dämpad med periodiskt tillförd energi.

Hade det varit en konstant putt som var vid varje ögonblick precis vad svägningen hade i dämpning så hade det tagit ut sig även i simuleringen, och damp-fukntionen hade alltid haft resultatet 0.

I praktiken med höga Q, får man att dämpningen är väldigt liten, samt att man mäter upp den när man kalibrerar, så kommer man kompennsera bort frekvensskiftet från dämpningen. Den kommer i praktikten även antagligen vara mindre än toleransen på komponenterna.

Men den finns ändå där, och därför har jag svårt att se pendel med "putt" som odämpad.

```python
import matplotlib.pyplot as plt

def harmonic(k, dt, n, damp):
	l = 1.0
	v = 0.0
	for t in xrange(n):
		a = -l*k

		l += v*dt
		v += a*dt + damp(a,v,l)*dt

		yield l

def build_plot(flags, damp):
	k = 0.05
	n = 20000
	dt = 0.01
	ys = list(harmonic(0.05, dt, n, damp))
	xs = range(len(ys))
	plt.plot(xs, ys, flags)

# Push one impulse just when l goes from negative to positive
class push_damp:
	def __init__(self, k_damp, n_period):
		self.last_l = 0.0
		self.k_damp = k_damp
		self.n_period = n_period

	def damp(self, a, v, l):
		res = v * self.k_damp
		if l >= 0.0 and self.last_l < 0.0:
			print "trig"
			res = -v*self.k_damp*self.n_period
		self.last_l = l
		return res

if __name__ == "__main__":
	build_plot('green', lambda a,v,l: 0)
	build_plot('blue',  push_damp(-0.05, 2050).damp)
	build_plot('red',   lambda a,v,l: -v*0.05)
	plt.show()
```

**Comment by sa0mad** [comment]
Vad som egentlgen händer med en pendel och alla intrikata detaljer för att göra rätt med en pendel är helt utanför scopet här. Den enda anledningen till att prata om en pendel är för att ge någon form av tankebild. Begreppet med odämpad svängning är inte något som är specifikt för pendlar, det är generellt för styr och reglerteknik och dess många användningar. Det är den aspekten som är den viktiga, inte detaljerna kring en pendel. Jag skulle kunna utveckla hela pendel-grejen men det är ett sidospår. Övertolka inte exemplet helt enkelt, det är bara ett försök att ge en mental bild utan att vara definierande för begreppet. Det är begreppet som är korrekt, exemplet är haltande.

**Comment by pengi** [comment]
Jag skulle nöja mig med att inte kalla den för odämpad, utan bara nöja mig med att säga att man periodiskt måste tillföra energi för att hålla amplituden, dvs. ha kvar exemplet, men ta bort "en odämpad svängning" då det innefattar mycket mer för den som kollar på matematiska modellen. Stycket är som du säger i övrigt en väldigt bra tankebild över hur en oscillator fungerar.

Problematiken är att om man använder begrepp felaktigt så fallerar trovärdigheten i boken, och när jag använder den som kurslitteratur för amatörradiocert till teknologer så kan jag inte bara hänvisa till att den är en förenkling, utan man även får ta innehållet med en nypa salt.

Pendeln är på engelska en "parametric oscillator", medans en "harmonic oscillator", dvs. den odämpade svägningen definieras som, vad jag kan läsa mig till och minnas, att funktionen av kraften inte är beroende av hastigheten, utan bara läge.

 Mitt förslag är att ändra:
> Stöt nu till pendeln varje gång, som den pendlar tillbaka. För lika stora utslag varje gång – en odämpad svängning – fordras det upprepade energitillskott som precis kompenserar förlusterna.
till
> Stöt nu till pendeln varje gång, som den pendlar tillbaka. För lika stora utslag varje gång fordras det upprepade energitillskott som precis kompenserar förlusterna.

**Comment by sa0mad** [comment]
Problemet är att vi behöver faktiskt just det begreppet, odämpad svängning, det är det tekniska begrepp vi har och måste leva med. Ditt förslag hjälper inte, det har fel utgångspunkt.

**Comment by pengi** [comment]
Ordet "odämpad" förekommer på två ställen i hela boken, båda i detta stycke (finns i en parentes nedan)

Om begreppet är viktigt att nämna, ska det inte vara i korrekt sammanhang? Och då borde man ha ett exempel på något odämpat? För exemplet visar en "parametric oscillator".

Eller så är inte just begreppet så viktigt, utan konceptet att oscillationen ska fortgå, och då kan man ta bort just den inskjutna satsen, samt parentesen på nästa rad, och allt stämmer, och det pratats om att oscillationen ska fortgå istället.

Det är ordvalet "odämpad svägning" som jag reagerar på, som betyder så myeckt mer än att oscillationen fortgår.

Vad säger andra?

**Comment by sa0mad** [comment]
Jag är mer benägen att kasta ut den redan sedan tidigare ifrågasatta och problematiska pendeln än själva begreppet odämpad svängning, bara så du förstår vad jag prioriterar. Jag gillar inte begreppet jättebäst heller, men nu är det som det är, det får vi leva med som det är. Elektroniken är full av det. Vi har bara att försöka presentera det för vad det är. Man kan ifrågasätta om det skall finnas med, men termen är den korrekta, det kommer vi inte runt.

**Comment by SM7NTJ** [comment]
Mitt minne kommer ihåg tre olika svängningsrörelser av vikt för reglerteknik och elektronik.

- Den med minskande amplitud, dämpad svängning.
- Den med ökande amplitud, självsvängning
- Den med konstant amplitud, odämpad svängning.

**NE** _Odämpad svängning, svängning eller vibration med oförändrad amplitud, dvs utan energiförlust._

Om vi nu talar om en praktisk oscillator, så för att svängningen ska vara odämpad, med konstant amplitud, samt ha en bibehållen frekvens krävs att jag tillför en energimängd som kompenserar för förluster och den energi som tas ut.

Simuleringen med python har nog en brist då den tillför en "putt" osymmetriskt. Kurvan blir därför osymmetrisk och frekvensen sjunkande. Skulle "putten" tillföras oavsett riktning vid nollgenomgången och **enbart** kompensera för dämpningen så skulle kurvan troligen bli symmetrisk och amplituden konstant och frekvensen oförändrad?

Vi kommer nog enklast vidare genom att lämna den mekaniska jämförelsen och ta bort pendeln ur texten samt beskära bort pendeln från bilden. Kvarvarande bild med dämpad och odämpad svängning behöver då ha lite mera text om dessa fenomen.
(vi behöver även justera stavningen av svängningar i \caption för bilden)

**Comment by pengi** [comment]
Även om man puttar åt båda hållen (och då varje putt blir svagare) så kommer man få en annan frekvens än odämpade fallet. Blå i följande graf visar samma dämpning som röd, vilket man ser fram tills graferna avviker. vid noll-genomgången. Även här ser man att frekvensen är något olika.

![screen shot 2017-11-20 at 22 54 55](https://user-images.githubusercontent.com/1087673/33043658-7353d90c-ce46-11e7-9934-3402d47d3d05.png)

Det jag är ute efter är den fysikaliska benämningen ska upprätthållas av odämpad, dvs. en oscillation som kan uttryckas med ekvationen F=-k*∆x, dvs. oberoende av hastighet (dvs. friktionsfri hela tiden). Konstant amplitud är bara en bieffekt av att den är odämpad. Dvs. odämpad leder till konstant amplitud, men konstant amplitud kan nås utan att den är odämpad.

```python
import matplotlib.pyplot as plt

def harmonic(k, dt, n, damp):
	l = 1.0
	v = 0.0
	for t in xrange(n):
		a = -l*k

		l += v*dt
		v += a*dt + damp(a,v,l)*dt

		yield l

def build_plot(flags, damp):
	k = 0.05
	n = 20000
	dt = 0.01
	ys = list(harmonic(0.05, dt, n, damp))
	xs = range(len(ys))
	plt.plot(xs, ys, flags)

# Push one impulse just when l goes from negative to positive
class push_damp:
	def __init__(self, k_damp, n_period):
		self.last_l = 0.0
		self.k_damp = k_damp
		self.n_period = n_period

	
	# Over n_period (approixmate samples for one period), integral of damp should be about 0
	def damp(self, a, v, l):
		res = v * self.k_damp
		if (l >= 0.0 and self.last_l < 0.0) or (l <= 0.0 and self.last_l > 0.0):
			res = -v*self.k_damp*self.n_period/2.42
		self.last_l = l
		return res

if __name__ == "__main__":
	build_plot('green', lambda a,v,l: 0)
	build_plot('blue',  push_damp(-0.05, 2050).damp)
	build_plot('red',   lambda a,v,l: -v*0.05)
	plt.show()
```
