### ISSUE TITLE
Bilder i sektion 3.4 Förstärkare ligger i osynk med text

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#326]
Sektion 3.4 Förstärkare
Version f18c1d2

Bild 3.45 beskriver frekvensmultipliceringskedja, men bilden ligger på en sida tidigare än brödtexten för frekvensmultiplicering. Förstärkare klass C separerar bilden från dess text.

Bild 3.43 beskriver förstärkare klass B och bild 3.44 beskriver förstärkare klass C.
Men de verkar vara placerade ovanpå varandra och i anslutning till brödtexten om klass C.
Ger effekten av att endast en bild är synlig och bildrubrikerna flyter ihop.
Brödtexten om klass B är en sida tidigare.

**Comment by sa0mad** [comment]
Bilder blir lätt förskjutna innan layout gjorts, därför är det en fråga för layout snarare än innehåll.

**Comment by sa0mad** [comment]
Förbättringar har gjorts, men det är svårt att få det helt rätt.
