### ISSUE TITLE
Mall för Pull Requests (PULL_REQUEST_TEMPLATE.md)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#33]
För att det ska bli lättare att hålla reda på saker att tänka på när man gör en Pull Request borde vi fixa en mall ([`PULL_REQUEST_TEMPLATE.md`](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)). Den kan stapla upp saker som:

- Följ stilmallen när det kommer till hur man formatterar texten
  - Radbrytning vid varje mening (när man lägger till och redigerar text)
  - 80 teckens maxbredd innan radbrytning
  - Kursiv stil indikerar nyckelbegrepp
  - Enhetsangivelser ska vara LaTeX-formler
  - osv... osv...
- Förändringarna ska kunnas köras utan fel i `pdflatex` med den senaste versionen av branchen som PR är branchad ut ifrån.
- HAREC ska mappas om texten är ny eller har ändrats med nytt innehåll
- osv... osv...

Denna information bör även finnas att läsa i en [`CONTRIBUTING.md` fil](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

Det blir lättare för den som gör PR:en att själv rätta till dessa saker innan de antingen av misstag merge:as in i texten eller måste bollas fram och tillbaka till granskare.

**Comment by sa0mad** [comment]
Förslagsvis pekar man på CONTRIBUTING och duplicerar inte den texten. Däremot en del annat matnyttigt kan gott finnas där.

**Comment by fnadde42** [comment]
Yes. PR-mallen är text som är förifylld i beskrivningen när man gör PR likt:

-----

Jag har sett till att
- [x] PDF bygger utan fel
- [ ] text är granskad enligt `texifiering.txt`
- [ ] förändringar (om signifikanta) är tillagda i changelogen

**Comment by sa0mad** [comment]
@fnadde42 Eftersom mycket redan är på plats av infrastrukturen runt om börjar det bli dags att skriva den här.
