### ISSUE TITLE
Antalet fria elektroner i Cu är lika med antalet atomer

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#333]
Sektion 1.1.2
Version 24409c2

Sektionens sista stycke avslutas med meningen "1 cm3 av koppar innehåller cirka 8,5 · 10^22 fria elektroner."

Samma formel användes i ett tidigare stycke för att beräkna antalet atomer i 1 cm3 koppar. Så givetvis kan man dra slutsatsen att det är en fri elektron per atom. Men det är lite otydligt. Dessutom är meningen placerad i ett stycke som handlar om atomers massa. Känns därför lite malplacerad och utan sammanhang.

Föreslår att sista meningen tas bort och istället ersätts med nytt kortare stycke efter nuvarande stycke som avhandlar 1 cm3 koppar. 

Atomernas massa och volym är ytterst liten. Tag som exempel en kub av koppar
med volymen 1 cm3 och vikten 8,9 gram. Den består av ca 8,5 · 1022 koppara-
tomer, dvs. 85 000 000 000 000 000 000 000 stycken.

En kopparatom har i  sitt valensskal en ensam elektron. Därför innehåller 1 cm3 koppar ca 8,5*10^22 fria elektroner, eller en per atom.

**Comment by sa0mad** [comment]
@SM7NTJ kanske skall ta hand om denna.
