### ISSUE TITLE
Referens till bild 26 sidor bort... 

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#334]
Sektion 1.1.5
Version 24409c2 

Hänvisning till bild 1.16 finns på sida 10.
Men bilden finns på sida 36.
26 sidor bort.

Trodde först det var tryckfelsnisse som skrivit fel bildnummer.

Även om det går bläddra framåt, då bildnummer ligger i sekvens, antyder den enkla formuleringen att bilden borde ligga i anslutning till texten. 
Ett annat ordval kan hjälpa läsaren att förstå att bilden ligger långt borta.

"Se kapitel 1.6 och bild 1.16 för illustration av relationen mellan dessa för en sinuskurva."

**Comment by SM7NTJ** [comment]
Ja det kan göras tydligare.
Bilden används flera gånger och ligger i det avsnitt som förklarar de aktuella begreppen.

**Comment by adbre** [comment]
Har inga invändningar mot att bilden ligger långt bort. Språkstilen var dock samma som för de fall bilderna ligger i nära eller omedelbar närhet.

**Comment by sa0mad** [comment]
@SM7NTJ \ref{} och \label{} är bra för detta, bara en liten påminnelse.

**Comment by SM7NTJ** [comment]
Åtgärdad, hänvisning till 1.6 tillagd med f3f51b1
