### ISSUE TITLE
[16] efter ampere och ohm

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#335]
Sektion 1.1.6 och 1.1.10
Version 24409c2 

Förstod inte varför det stod [16] efter enheten ampere. 

    Måttenheten för ström är ampere [A] [16].

Förekommer även för ohm 

    Resistans uttrycks i enheten ohm [16]

I fallet ampere blev det konstigt då A också placerades inom hakparanteser.
Läser på mobilen och kan inte avgöra om [16] är en länk till källa eller motsv, men vid fotnot eller dylikt brukar väl dessa vara upphöjda från brödtexten? 

Oavsett så borde inte A vara placerat inom hakparanteser för att inte tillskriva [16] otillbörlig relevans. Istället omformulera meningen likt fallet ohm: "och betecknas med bokstaven A".

**Comment by SM7NTJ** [comment]
A inom hakparenteser följer skrivreglerna för Koncept. 
 [16] är en länk till litteraturförteckningen.
Det kan vara förvirrande när de hamnar efter varandra men det blir så när det finns en litteraturreferens efter en beteckning.

**Comment by sa0mad** [comment]
[16] är i det här fallet en literatur-referens. Om du trycker på den så hoppar du till referensen.

[A] är sättet att referera till enhetens benämning, något som dock inte förklaras jättebäst innan det används, det borde förstås göras då det återkommer på fler ställen. Det är standard notations-sätt för enhetsbetraktelser. Därför borde man skriiva något sådant här:
`
Måttenheten för ström är ampere och betecknas med A [16], vilket ofta skrives som enhetbeskrivningen [A].
`

**Comment by adbre** [comment]
Sitter med mobilen. Kan inte klicka/följa länkar med den klienten jag har.

Som jag skrev i orhinalposten, brukar inte fotnot/litteraturreferenser vara upphöjda?

Om skrivreglerna för Koncept är att använda hakparanteser för enheter så konstaterar jag att det inte gör det i fallet ohm.

**Comment by sa0mad** [comment]
Literaturreferens brukar inte vara upphöjd, den brukar vara precis som angivet. Standard notation i vetenskapliga artiklar och böcker, så därför formar LaTeX den så automatiskt.

Referens till fotnötter är helt korrekt normalt upphöjda.

Man skall skilja på enheter som anges vid värden och när de används vid enhets-analys, det är mer själva enhetsanalysen som brukar göras med hak-klamrar. När man anger värde så skall det vara 2,5 kV. Det finns säkert ställen där det där kunde göras tydligare och mer konsekvent.

**Comment by adbre** [comment]
>Literaturreferens brukar inte vara upphöjd, 
>den brukar vara precis som angivet. Standard >notation i vetenskapliga artiklar och böcker, så >därför formar LaTeX den så automatiskt.
>
>Referens till fotnötter är helt korrekt normalt >upphöjda.

Ok

>Man skall skilja på enheter som anges vid värden >och när de används vid enhets-analys, det är mer >själva enhetsanalysen som brukar göras med >hak-klamrar. När man anger värde så skall det >vara 2,5 kV. Det finns säkert ställen där det där >kunde göras tydligare och mer konsekvent.

Är inte helt med på vad du menar med enhetsanalys. 
Är nedanstående exempel på det du nämner inte använder hakparanteser konsekvent? 

Jämför med kapitel 1.1.5 volt som använder hakparanteser. 

    Spänningen över ändpunkterna på en strömledare är 1 volt [V], då ledaren ge-
nomflyts av en likström av 1 ampere [A] under effektutvecklingen 1 watt [W].

Kapitel 1.1.7 för ampere och 1.1.10 för ohm gör det inte.

    Strömmen är 1 A när 6,25 · 1018 elektroner per sekund flyter genom ett givet
ledartvärsnitt, vilket motsvarar laddningen 1 coulomb.


    Resistansen i en resistor är 1 Ω, när en spänning av 1 V driver en ström av 1 A
genom den resistorn.
