### ISSUE TITLE
Primärbatteri och sekundärbatteri

### ISSUE THREAD

**Issue by adbre** [SverigesSandareamatorer/SSA-Akademin#339]
Primärbatterier och sekundärbatterier är termer som frågas efter i PTS övningsprov.

Dessa finns inte i koncept (eller "bli sändaramatör" för den delen). 
Däremot nämns termen "primärcell".

Dock enkelt att hitta svar på internet om man söker på dessa ord.
Så ursäkta mitt ordklyveri med att inte termerna ordagrannt finns med i koncept. 

Så frågan här berör även ett lite högre plan. 
- ska koncept ordagrant förklara termer som PTS använder? 

Å ena sidan är det bra att täcka upp det PTS frågar efter. 
Å andra sidan kan det i vissa fall vara överarbetat att alla smådetaljer ska stämma.
Å ena sidan är det synd att behöva ha än fler källor än koncept vid studie. 
Å andra sidan är det lätt att hitta svaret på internet.
Å ena sidan fördel att i koncept använda exakt samma term då det går att söka på när frågan digitalt.
Å andra sidan kan koncept lämna visst utrymme åt egna slutsatser/förståelse.
Å ena sidan är förståelse av förhållanden inte samma sak som kunskap om termer. 
... Osv

**Comment by fnadde42** [comment]
> Primärbatterier och sekundärbatterier är termer som frågas efter i PTS övningsprov.

> Dessa finns inte i koncept (eller "bli sändaramatör" för den delen).

Det är mycket viktigt att termerna åt åtminstone finns i registret längst bak om andra termer används i boken. Man ska kunna slå upp allt, lätt och smidigt, som man hittar ifrån PTS övningsprov.

**Comment by sa0mad** [comment]
Egentligen har termerna tappat sin ursprungliga betydelse, så egentligen kan det ifrågasättas om det är så relevant att ens fråga om det, det är arv från svunna tider som borde städas ur.
