### ISSUE TITLE
Information/Regler för de som vill bidra (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#34]
En [`CONTRIBUTING.md` fil](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) som innehåller alla regler för att bidra till repot skulle vara bra. @Lominean (m.fl.) har gjort många bra förändringar (så som att förhindra radbrytning mellan värde och enhet i texten) men jag har inte koll på alla. Därför skulle det vara bra att få upp en lista på dessa så att det är lätt att granska ny och befintlig text.

Vissa av dessa "regler" finns i `texifiering.txt`

**Comment by sa0mad** [comment]
textfiering.txt har varit dokumentet för att försöka styra tex formatet till något gemensamt. Kanske inte helt up to date, men den kan nog uppdateras. CONTRIBUTING.md borde fokusera på andra delar i helheten, så som att man kan köra make och bygga hela boken innan incheckning och peka på texifiering.txt för mer detaljerade regler om formatering mm.

**Comment by fnadde42** [comment]
Precis det här. Den kan beskriva även hur man bidrar till projektet på andra sätt än PR

**Comment by sa0mad** [comment]
Bootstrappa detta och PR så kan vi hälla i lite info och stänga när de är OKish som aggregat

**Comment by fnadde42** [comment]
"Bootstrappa detta"?

Jag hänger inte med i "ungdomslingot"

**Comment by sa0mad** [comment]
"Bootstrappa" är gammal datorterm som egentligen kommer från cowboy-världen. För att börja dagen drar man på sig sina boots, och då drar man i boot-strappen för att kunna kliva upp på morgonen.
