### ISSUE TITLE
Bild 2.12 ser ut att hamna i fel kapitel

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#345]
Bild 2.12 hör till kapitel 2.5. Men i pdf ligger bilden ligger före kapitelrubriken, så den ser ut att höra till föregående kapitel.

**Comment by sa0mad** [comment]
Det här är ett exempel på en layout-detalj som inte behöver kommenteras alls, eftersom layout inte gjorts, och det är då sådant här fixas. Alla "bilder ligger fel" kommentarer blir lite av QRM. Det är precis därför som formuleringarna är som de är kring hur det ska granskas. Överväger att stänga alla "bilder liger fel" issues av detta skäl.

**Comment by sm5phu** [comment]
Jag brukar inte kommentera hur bilderna är preliminärt placerade inom respektive kapitel, men här hamnade den helt utanför kapitlet. OK att stänga.
