### ISSUE TITLE
Semantic Versioning, git-hash och CHANGELOG.md

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#35]
För att enklare hålla reda på versioner av KonCEPT behöver vi någon slags versionshantering. Förslagsvis använder vi oss av [Semantic Versioning](http://semver.org/) (~~Major = Upplaga, Minor = omskrivning/borttag/tilläg av text, Patch = redaktionella ändringar som inte påverkar innehållet~~. Se tabell nedan) och en hash (förslagsvis Git-standard med 7 första tecken) som finns i boken för att visa vilken version och commit PDF:en är byggd på.

```
 ┏━ Major: Upplaga
 ┃ ┏━ Minor: Tryckning där 0 är första tryckningen
 ┃ ┃ ┏━ Patch: Redaktionella ändringar eller uppdateringsvändor 
 ┃ ┃ ┃  av publicerad PDF som ej släppts i tryck ännu
 ┃ ┃ ┃     ┏ Git-hash (för att kunna identifiera exakt version av PDF)
 ┃ ┃ ┃     ┃
v2.0.0 (d0ff345)
```
För att göra det mer överskådligt vad som har hänt med boken mellan versioner fyller man i en [changelog](http://keepachangelog.com) när man gör anmärkningsvärda förändringar. En `git log` är alldeles för plottrigt och ger inte en överskådlig bild.

EDIT: Uppdaterat tabell med info baserat på SA0MADs inlägg

**Comment by sa0mad** [comment]
Major = Upplaga
Minor = Tryckning där 0 är första tryckningen
Patch = redaktionella ändringar eller uppdateringsvändor av publicerad PDF som ej släppts i tryck ännu

**Comment by sa0mad** [comment]
Hur genomför vi det här i praktiken, vad behöver göras?
Vad behöver jag göra för att sätta det här så det fungerar?
Kan vi hantera formen 2.0.0-RC1 också?

**Comment by fnadde42** [comment]
> Hur genomför vi det här i praktiken, vad behöver göras?

Själva versionshanteringen görs manuellt när utvecklingsteamet känner att man har gjort tillräckligt med smårättningar av en nysläppt version (ökar PATCH-numret) eller känner att det är dags att göra en ny tryckning med de nya förändringarna (ökar MINOR-numret) eller när det är dags att släppa en ny upplaga (som nu) (ökar MAJOR-numret).

>  Vad behöver jag göra för att sätta det här så det fungerar?

Man [taggar Git-committen med versionsnumret](https://git-scm.com/book/en/v2/Git-Basics-Tagging) på den commit där man också ändrar versionsnumret i textfilen VERSION.txt som sedan hämtas därifrån och skrivs in i boken när den genereras. I samma veva hämtas den nuvarande commit hashen och skrivs in i boken när den genereras.

> Kan vi hantera formen 2.0.0-RC1 också?

[Semantic versioning](http://semver.org/) dikterar hur versionsnumret får se ut.

> - *A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.*
>
> - *Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.*

**Comment by fnadde42** [comment]
Kruxet är att få det här att ske automatiskt. Jag har kollat lite på om det går att skicka in parametrar i pdflatex för att kunna skicka in en sträng med versionsnummer in i boken men det skulle underlätta om någon med mer LaTeX kunskaper skulle titta på det då jag inte känner till riktigt hur variabler fungerar.

**Comment by sa0mad** [comment]
Nu infört.
