### ISSUE TITLE
Kommentar 33: Second operator

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#352]
### Avsnitt

13

### Version

b404741

### Kommentar

Man kanske kunde klämma in en kort formulering om vad "Second Operator" är?

**Comment by sm5phu** [comment]
Text från PTSFS 2015:4 finns redan i kapitel 14.3.2:

_"Undantag från kravet på amatörradiocertifikat gäller för den som under en tidsbegränsad period utbildar sig för att få ett sådant certifikat och för den som under en förevisning tillfälligt använder amatörradiosändare, under förutsättning att användningen av  radiosändaren sker under uppsikt av  en innehavare av amatörradiocertifikat."_

Borde väl räcka med att där lägga till en kommentar om att detta avser så kallad second operator?

**Comment by SM7NTJ** [comment]
Ja det borde räcka med en sådan kommentar

**Comment by sa0mad** [comment]
Jag tycker gott vi kan lägga till en skrivning där vi ändå beskriver hur QSOs skall beskrivas, och det med stöd i 14.3.2. Förslag:

13.7.4 Second operator

Under normala förutsättningar skall den som opererar en radioutrustning ha amatörradiocertifikat. Det finns dock ett undantag som kallas second operator. Med detta menas en person som saknar amatörradiocertifikat kan aggera operatör jämte en person som har amatörradiocertifiikat. I Sverige är det reglarat i undantagsföreskriften, så som beskrivs i 14.3.2. Detta medger att man kan förevisa hobbyn och även träna under kontrollerade förhållanden. För att detta skall fungera krävs att den med amatörradiocertifikat instruerar om hur man skall bete sig i etern, hur handhavandet går till och kan övervaka att detta följs.

Självklart används den anropssignal som amatörradiocertifikat-innehavaren har. Det är bra att det är tydligt under QSOt att det framgår att det är en second operator som är aktiv. Antingen ropar amatören upp och sedan berättar att han lämnar över till second operator Simon. Alternativt kan second operator göra anropen själv och då ropa t.ex. "SM5XYZ second operator Anna".

Möjligheten att använda second operator skall användas med klokhet, och kan aggera god morot för att få både ungdommar och vuxna intresserad av hobbyn, samt även skapa en god förståelse.

**Comment by SM7NTJ** [comment]
Jag föreslår direkt efter 13.7.2 innan nuvarande 13.7.3 med en \label{PTSFS2015:4} i 14.3.2

Omarbetat förslag från @mad

\subsection{Second operator}
\index{Second operator}

Den som självständigt använder en amatörradiosändare ska ha ett
amatörradiocertifikat.
Det finns ett undantag från kravet på amatörradiocertifikat då en person
tillfälligt använder en amatörradiosändare under uppsikt av någon som har ett
amatörradiocertifikat.
Detta kallas \emph{second operator} och innebär att en person som saknar
amatörradiocertifikat kan agera operatör jämte en person som har ett.

I Sverige är det reglerat i undantagsföreskriften PTSFS 2015:4 \ref{PTSFS2015:4}.
Detta medger att man kan förevisas hobbyn och även träna under kontrollerade
förhållanden.
För att detta skall fungera krävs att den med amatörradiocertifikat instruerar
om hur man skall bete sig i etern, hur handhavandet går till och kan övervaka
att detta följs.

Självklart används anropssignalen för innehavaren av amatörradiocertifikatet.
Det är bra att det tydligt framgår att det är en second operator som är aktiv.
Antingen ropar amatören upp och sedan berättar att han lämnar över till second
operator Simon.
Alternativt kan second operator göra anropen själv och då ropa till exempel
"SM5XYZ second operator Anna".

Möjligheten att använda second operator skall användas med klokhet, och kan rätt
använd skapa en god förståelse för hobbyn och utgöra en morot för att få både
ungdomar och vuxna intresserade av amatörradio.

**Comment by sa0mad** [comment]
Lyft in i en PR tycker jag.
