### ISSUE TITLE
PANK-regeln

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#353]
Ska vi någonstans nämna minnesregeln för vilket av anod och katod som är plus- respektive minuspol? "PANK - Positiv Anod, Negativ Katod"

**Comment by SM7NTJ** [comment]
Minnesregeln PANK borde kunna skrivas in i 2.5.2 efter andra avsnittet.

Borde vi även uppdatera index för diodavsnittet och lägga in \index{diod!      } så att det tydligare framgår i indexet vilken komponent som avses?
