### ISSUE TITLE
Sortomvandlingstabell

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#357]
En sortomvandlingstabell är ett av få hjälpmedel som är tillåtna på proven. Borde vi ha med en i boken? Se http://www.sm3liv.se/pdf/Sortomvandling2.pdf

**Comment by sa0mad** [comment]
Oj, är det tillåtet?
Då ska vi:
1) Ha det i boken
2) Ha som separat PDF

**Comment by sa0mad** [comment]
Om man dessutom skall ha det som del av utbildningspaketet är separat beslut.
Oavsett kommer jag uppmana alla att lära sig det utantill om de kan. Däremot för de som har svårt med just detta så skall det inte vara det som de skall falla på, utan de skall lära sig att använda det.

**Comment by sikvall** [comment]
Definitivt vara en enkelt utskrivbar sak man kan ta med.

mån 4 dec. 2017 kl 09:03 skrev Magnus Danielson <notifications@github.com>:

**Comment by SM7NTJ** [comment]
Kan detta vara något?
Vill vi ha det i landscape? Det verkar fungera med \usepackage{pdflscape} och  \begin{landscape}.

![prefixomvandling_bild](https://user-images.githubusercontent.com/25039270/33805587-c1f63378-ddbb-11e7-93b7-af91c994f0b6.png)

**Comment by sa0mad** [comment]
Ja precis. Om du lägger det i appendix-n.tex så kan jag fixa en wrapper för separat PDF.

**Comment by SM7NTJ** [comment]
appendix_n.tex på väg
