### ISSUE TITLE
Mätfel – mätonoggrannhet – mätosäkerhet

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#358]
När jag för snart tio år sedan lärde mig mätteknik så var man tydlig med att man inte (längre) skulle använda _mätfel_ för att beskriva den inneboende osäkerheten i alla mätningar utan det kallades _mätosäkerhet_. I Koncept 9.1.13 Mätfel används nu _mätfel_ och _mätonoggrannhet_ på ett sätt som i alla fall jag inte känner igen. Om jag bara utgår från de styckena i boken så vet jag inte säkert hur jag skulle använda begreppen, i förhållande till varandra.

**Comment by sikvall** [comment]
Jag tycker man ofta ser alla tre begreppen, i olika sammanhang behöver de
inte beskriva exakt samma sak, tänkbart är att storleken på
mätonoggrannheten är känd medan mätosäkerheten inte behöver vara det
exempelvis. Men mätfelet beror på flera saker, detls noggrannheten hos
instrumentet, avläsningen, sättet att mäta på och yttre faktorer.

mån 4 dec. 2017 kl 14:50 skrev Philip Eriksson <notifications@github.com>:

**Comment by SM7NTJ** [comment]
Vi kan nog förtydliga texten i avsnittet.
Om jag minns rätt handlar mätosäkerhet om kvantitativa metoder för att bestämma ett område för mätvärdets sanna värde. (beräkning av medelvärde och standardavvikelse)
@mad kan nog mera om ämnet.

**Comment by sm5phu** [comment]
Stängd utan åtgärd, möte #58.
