### ISSUE TITLE
Tillgängliggöra konversation mellan två parter (via t.ex. inspelning)?

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#364]
Vad säger LEK om detta? Det känns ganska bisarrt att man inte får spela in en konversation som sker på t.ex. en repeater då hela uppgiften med en repeater är att nå så långt som möjligt och i de allra flesta fall att komma i kontakt med så många som möjligt. Inte riktigt samma sak som att QSY:a över till simplex och ha en konversation på egen frekvens. 

Det är förvirrande och har skapat många frågetecken kring vad som faktiskt gäller. KonCEPT borde berätta vad som faktiskt gäller så det är inte behöver vara en fråga längre.

**Comment by Lominean** [comment]
Eller i alla fall hänvisa till en säker källa, till exempel ett specifikt råd från PTS i frågan om det nu skulle finnas ett sådant.

**Comment by sa0mad** [comment]
Lorentz har grävt i den här frågan förr visade det sig, så han har erbjudit att skriva ihop något.
