### ISSUE TITLE
Bilder innehåller samma text som bildtexten under

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#37]
Som jag ser det finns det 3 alternativ:

1. Man redigerar bort bildtexten i samtliga bilder
2. Man gömmer bildtexten i LaTeX
3. Man låter det vara som det är

----

![screenshot from 2017-08-23 23-17-19](https://user-images.githubusercontent.com/1107419/29638939-3cabe440-8859-11e7-8f20-bae8b4a6e01b.png)

**Comment by sa0mad** [comment]
Vart efter bilder blivit omritade så har LaTeX texten blivit den enda. Dessutom sätts själva bildnumret av LaTeX, och det utesluter förslag 2. Den som orkar får klippa om bilder eller rita om dem. Den gamla bildtexten och numrering skall bort. Vart efter bilder blir åtgärdade går de från förslag 3 till förslag 1.

**Comment by fnadde42** [comment]
Jag skulle kunna göra jobbet med att ta bort bildtexten i bilderna

**Comment by sa0mad** [comment]
Ta även bort själva ramen.
