### ISSUE TITLE
Kommentar 34: P=R*I*I är samma som P=R*I^2, liksom även P=U*U/R är en dublett

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#371]
### Avsnitt

1.1.13

### Version

3e9d68a

### Kommentar

P=R*I*I är samma som P=R*I^2, liksom även P=U*U/R är en dublett

**Comment by sa0mad** [comment]
Dubbletterna är medvetna av övertydligt pedagogikskäl.

**Comment by sm5phu** [comment]
Står så för pedagogisk tydlighet.
