### ISSUE TITLE
Två avvikande sammanfattningar

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#374]
Just nu är det två kapitel/delar som har sammanfattningar:

- 6.3.10, en `subsection` (i chapter6-2.tex). 
- 11.1, en `section`.

Jag ser inte varför dessa kapitel/delar skiljer sig från resten av boken så att de behöver ha egna sammanfattningar.

**Comment by sikvall** [comment]
Jag föreslår ta bort dessa två.

**Comment by sm5phu** [comment]
Stryk 6.3.10?
