### ISSUE TITLE
\(\mu V\) eller \(\mu\)V

### ISSUE THREAD

**Issue by kmjonsson** [SverigesSandareamatorer/SSA-Akademin#376]
På fler ställen används \mu V för att skriva micro-Volt grupperat i "math"-kontext men inte
i text mV då inte milli är ett grekisk bokstav.

Jag föreslår att man flyttar ut V ur math-kontextet.

**Comment by sikvall** [comment]
\textmu V skall det vara. Ingen math context för enheter, de är ej variabler och skall ej sättas kursivt i löpande text.
