### ISSUE TITLE
Stycke "Mäta resonansfrekvens" har ?? HAREC referens

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#38]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/d0ff3457aa4beb71dd0d0bf38a569fe4929a0a28/koncept/chapter8-1.tex#L323

![screenshot from 2017-08-23 23-26-04](https://user-images.githubusercontent.com/1107419/29639266-75700f58-885a-11e7-9eae-e8b43b3657d2.png)

**Comment by sa0mad** [comment]
Åtgärd pushad.
