### ISSUE TITLE
Hämta senaste bygget koncept.pdf ger gammal fil

### ISSUE THREAD

**Issue by SM7NTJ** [SverigesSandareamatorer/SSA-Akademin#384]
Funktionen "Hämta senaste bygget koncept.pdf" ger gammal fil.
När man trycker på knappen hämtas koncept.2.0.0-RC.1+b0669.95c1d51.pdf från 2017-12-10 22:49.
Det nyare bygget koncept.2.0.0-RC.1+b0674.eabe89c.pdf från 2017-12-25 03:24 hämtas inte.

Koncept.pdf har samma tid och datum som senaste bygget men ett gammalt innehåll.

**Comment by Lominean** [comment]
För mig blir det rätt (eabe89c).

**Comment by SM7NTJ** [comment]
Jag testade igen och fick fel version. Ny test efter inloggning fick jag fel version igen. tryckte på uppdatera och rätt version laddades hem.
Troligen någon mystisk låsning i cachen för webbläsaren.
Stänger ärendet
