### ISSUE TITLE
Flera stycken/kapitel på HAREC krav saknas

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#39]
Boken har uppfyllt en stor del av kraven som HAREC ställer men det finns en del krav som inte har någon förklaring i boken. Om man går till slutet i kapitel "CEPT HAREC krav" finns det en lista med krav och i slutet på varje rad en hänvisning inom en parantes till vilket kapitel som berättar om det kravet. De ställen där det står (??) saknas det litteratur på ämnet och behöver kompletteras.

Ska man radda upp dessa HAREC krav och söka författare till dom?

**Comment by sa0mad** [comment]
De skall konverteras till issues, antingen som enstaka eller som klump, och sedan så betar vi av dem. Denna issue kvarstår tills alla HAREC krav utan text har en issue knuten till sig.

**Comment by fnadde42** [comment]
Jag tror det är bäst att knyta dom till enskilda ärenden så att dom kan diskuteras en och en så man inte blandar ihop en massa diskussion. Utöver det borde vi tagga dessa med något som säger att ärendet behöver författare så det går att lätt söka efter ärenden av det slaget.

**Comment by sa0mad** [comment]
När du har ett block med snarlika som ligger ihop är det bättre att de blir en issue.

**Comment by fnadde42** [comment]
Jo det finns ingen anledning att i onödan skapa 1000 issues men de som har gemensam diskussion (liknande ämne) kan ju dras ihop till ett ärende. Kan du ta det här ärendet då du har bättre kunskap om HAREC täckning och kan bättre döma vilka krav som bör läggas i samma ärende?

**Comment by fnadde42** [comment]
Jag har gjort en tag som heter *needs author* som vi kan använda när vi har ett kapitel som behövs skrivas

**Comment by sa0mad** [comment]
Just därför skrev jag som jag gjorde initialt. Titta på HAREC krav 4.4-gruppen där 4.4.1, 4.4.4, 4.4.7 och 4.4.8 nog kan hanteras som en naturlig grupp, dvs "Kvarvarande HAREC a.4.4 kravven 4.4.1, 4.4.4, 4.4.7 och 4.4.8 behöver skrivas." Det är inte svårare än så.

**Comment by sa0mad** [comment]
Jag har genererat issues för HAREC a.1 till a.7. @fnadde42 kanske kan ta vid att generera fler issues av kvarvarande. En del titlar har ?? men jag har låtit dem vara när de annars är täckta så kan man fundera på om de öht skall vara taggade eller inte.

**Comment by sa0mad** [comment]
Alla åtgärdade.
