### ISSUE TITLE
() eller []

### ISSUE THREAD

**Issue by kmjonsson** [SverigesSandareamatorer/SSA-Akademin#392]
() och [] används lite om vart annat runt om i boken.

Det kan bli väldigt svårtytt på sina ställen då även literaturreferenserna använder [].

Ett sådant exempel är i kapitel 1.1, Resistans – Enheten ohm där ohm efterföljs av [16] vilket gjorde mig rätt förvirrad och var tvungen att gå till .tex-filen för att kolla på källan till siffran. I samma sammanhang används [] runt symbolerna för tex 'ohm'.

Läser man: http://www.skiljetecken.se/parentes.php så står det:
"Hakparentes" eller "klammer" är tecknen [ ] man använder för att avskilja information i en parentes, eller för att avskilja uttalsinstruktioner i en ordbok.".

Utifrån det borde [] i princip inte användas i boken i normala fall.

**Comment by sa0mad** [comment]
[] används dels för referenser och dels för enhetsbetraktelser, det senare är i enlighet med normal skrivstandard för hur man skriver SI-enheter i teknisk literatur.

**Comment by kmjonsson** [comment]
Det används hur som helst inte konsekvent.
Finns många ställen där [] saknas och där () används runt SI-enheterna.

**Comment by sa0mad** [comment]
Peka gärna på ett antal exempel så det blir lättare att se samma sak som du ser.

**Comment by kmjonsson** [comment]
Några exempel jag hittade lite snabbt.
Kap 1.1:
"Måttenheten för ström är ampere A [16]."
"Strömmen är 1 A"

Att jämföra med: 
"Måttenheten för spänning är volt [V]."

Användningen av ():er var kanske inte så ofta men används i \index{}

Sakregister:
"watt (W)"
"ampere (A)"

**Comment by SM7NTJ** [comment]
Vi kan göra det mera konsekvent när layouten är genomgången.

För avsnitt 1.1.7 (ampere) och avsnitt 1.1.10 (ohm) så har \cite{SIbrochure8} hamnat så att den kan misstolkas, För att fixa det behöver vi formulera om texten lite.

Vi behöver i 1.1.7 även ersätta  \emph{ampere} \(\mathrm{A}\)  med  \emph{ampere} [A]

Vi behöver  ändra indexposter på 14 ställen \index{enheter!xxxx(X)} till \index{enheter!xxxx[X]}
enheter ampere (A), 10
baud (Bd), 71
coulomb (C), 18
farad (F), 99
henry (H), 106
hertz (Hz), 38
joule (J), 13
ohm (Ω), 12, 91
sample (S), 86
tesla (T), 27
volt (V), 8
voltampere (VA), 13
watt (W), 13

Ändringarna får dock vänta på klartecken från layout

**Comment by sa0mad** [comment]
Det här är en layout-fråga, så jag har markerat den som sådan. Nog för att vi kan gå före och rensa innan layout görs på kapitel, och vi ska nog diskutera igenom detaljerna. För vissa fall förstår jag att det blivit i alla fall märkligt. Förkortningar brukar man skriva inom parantes, så därför har index blivit därefter, men det kan vara lämpligt att ändra för dem. Att beskriva de detaljerade formateringsreglerna, något vi försöker göra och omdefiniera löpande, är inte alltid lika lätt. Jag skulle uppskatta @tfritzon och @sikvall som diskussionspartners.

Just nu är kapitel 1 och 2 låsta för layout, så därför överlåter vi åt layout-gruppen att göra åtgärder där. Vi kan fixa andra kapitel. Just nu skall vi dock komma till konsensus om hur vi gör. Eventuellt behöver vi diskutera olika fall separat.
