### ISSUE TITLE
Sändtagare saknas

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#394]
Det svenska ordet _sändtagare_ som synonym till _transceiver_ saknas i boken.

[Jag började](https://github.com/Lominean/SSA-Akademin/tree/sändtagare) med att lägga in ordet i sakregistret men texten behöver justeras något också.

**Comment by sa0mad** [comment]
Givetvis skall både det svenska och engelska begreppet finnas där det beskrivs. Vad vi har fokus på kan vi fundera på. Jag tror transceiver används oftare än sändtagare, även om det är en anglifieriing av språket. Det blir en bedömnings-sport vad vi väljer.

@sikvall @sm5phu @SM7NTJ

**Comment by sikvall** [comment]
Magnus Danielson <notifications@github.com> writes:

> Givetvis skall både det svenska och engelska begreppet finnas där det
> beskrivs. Vad vi har fokus på kan vi fundera på. Jag tror transceiver
> används oftare än sändtagare, även om det är en anglifieriing av
> språket. Det blir en bedömnings-sport vad vi väljer.
>
> @sikvall @sm5phu @SM7NTJ 

Sedan min signalisttjänst på S1 i Enköping mellan 1992-1993 har jag
aldrig hört någon annan, vare sig före eller efter, benämnda sändtagare
för detta utan det heter 2-vägsradio, eller bara radio i normalt
språkbruk vill jag tillstå.

-- 
Anders Sikvall          http://anders.sikvall.se/
Xindi.ichimusai.org     Using GNUS for mail and news

**Comment by Lominean** [comment]
Nu finns _sändtagare_ med i sakregistret så den som letar kommer att hitta en tråd att följa.
