### ISSUE TITLE
LaTeXML: Error:malformed:#PCDATA #PCDATA isn't allowed here

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#4]
# Återskapa
1. Installera LaTeXML (instruktioner för hur man installerar version 0.8.2 finns i [`BUILD.md`](../blob/master/BUILD.md#latexml):
1. Kör följande kommando:  
    `make koncept.webb`

Fellogg med förekomster av bara det här felet: [error.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/853243/error.txt)  
Hela loggen av körningen: [latexml.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/853244/latexml.txt)

-----

*Fatal Error* som får LaTeXML att stanna. Detta utgör 32 av 100 fel som måste släckas.
```
Fatal:too_many_errors:100 Too many errors (> 100)!
	at koncept/koncept/appendix-l.tex; line 233 col 17
	In Core::Document[@0x478efe8] at koncept/koncept/appendix-l.tex;
	line 233 col 17
	 <= [ <= Core::Document[@0x478efe8] <=
	 [noitemsep]␍\enumerate@itemSimple the... <= ...
6 warnings; 101 errors; 1 fatal error; 9 undefined
macros[\AddToShipoutPicture, {pdfsidelinecomment},
\mdfdefinestyle, \setlongtables, \boxbox, \marginnote, {mdframed},
\DeclareUnicodeCharacter, \harec]; 7 missing files[refbook.sty,
enumitem.sty, mdframed.sty, eso-pic.sty, pdfcomment.sty, marginnote.sty,
stmaryrd.sty] at /usr/share/perl5/LaTeXML/Common/Error.pm line 69.
```
Föregås av flera av följande fel i många av .tex-filerna (mest i `appendix-l` och näst mest i `chapter11-2`)
```
Error:malformed:#PCDATA #PCDATA isn't allowed here
	at koncept/koncept/appendix-l.tex; line 71 col 17
	Currently in XMLDocument[56652224]<ltx:document
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..." _ID_counter_p_="11"
	xmlns="http://dlmf.nist.gov/LaTeXML"
	xmlns:svg="http://www.w3.org/2000/svg">...<ltx:appendix
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..." frefnum="Bilaga J"
	refnum="J" xml:id="A10" _ID_counter_p_="4">...<ltx:section
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..." refnum="J.2"
	xml:id="A10.S2" _ID_counter_p_="1">...<ltx:para
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..."
	xml:id="A10.S2.p1">...<ltx:enumerate
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..."
	xml:id="A10.I2">...<ltx:item
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..." frefnum="1." refnum="1"
	xml:id="A10.I2.i1" _ID_counter_p_="1">...<ltx:para
	_box="LaTeXML::Core::Box=ARRAY(0x2b0..."
	_font="Font[serif,medium,upright,10,b..."
	xml:id="A10.I2.i1.p1">...<ltx:enumerate
	_box="LaTeXML::Core::Whatsit=HASH(0x..."
	_font="Font[serif,medium,upright,10,b..." xml:id="A10.I2.I1"/>
	In Core::Document[@0x478efe8] at koncept/koncept/appendix-l.tex;
	line 71 col 17
	 <= [ <= Core::Document[@0x478efe8] <=
	 [noitemsep]␍\par␍\enumerate@itemCondu... <= ...

```
Rad 71 i filen `appendix-l.tex`:

     71 \begin{enumerate}[noitemsep]

Det verkar som att i de flesta fall så får LaTeXML fel då man har något custom-kommando eller något speciellt importerat som den inte känner igen. Vet inte vad det här skulle kunna vara men någon kanske skulle kunna upplysa mig.

**Comment by sa0mad** [comment]
@fnadde42 har det gått bättre efter att ha filtrerat bort?

**Comment by sa0mad** [comment]
Tittat lite på den här, dels har jag pushat en bort-tagning av [noitemsep] för appendix-l.tex som var mest lite kompaktering. Dels har jag pillat om bygget av koncept.webb. Nu bygger den, men det ser inte jättevackert ut. Dock, löser det denna fråga. LaTeXML är inte jättebra än på att hantera saker, men nu får vi en output. Anser just denna punkt avklarad för stunden.

**Comment by fnadde42** [comment]
`[noitemsep]` går ju visserligen att ta bort med `sed` innan LaTeXML börjar jobba så kan man behålla det om det fyller en bra funktion. Angående outputen så går det att putsa till med lite `sed` och bättre CSS. Vissa grejer stödjer inte LaTeXML riktigt än så man får kolla på om det är något som går att jobba runt på något sätt.
