### ISSUE TITLE
Text i sid-huvud överlappar vid för långa kapitel/avsnitts-rubriker

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#42]
![screenshot from 2017-08-24 01-43-21](https://user-images.githubusercontent.com/1107419/29643171-b67bf7ec-886d-11e7-85c1-493a43628099.png)

**Comment by sa0mad** [comment]
Jobbigt, för man vill å ena sidan ha vettiga namn, men å andra sidan ha läsbara sid-huvuden. Man skulle kunna sätta sid-huvud-versionen av texten till något som blir läsbart förstås.

**Comment by fnadde42** [comment]
Det här måste ju vara något som går att förhindra, som att tvinga dom på två olika rader (headern blir ju lite högre men det ser bättre ut och man bibehåller samma information som alla andra sidor har. Tycker inte att vi ska behöva ändra titeln för kapitlet.

**Comment by sa0mad** [comment]
Man kan
1. Göra ingenting, det får se fult ut som stryk
2. Ändra titeln så att det ser snyggt ut
3. Ändra hur titeln bryts när den är som sidhuvud
4. Ändra titeln när den är som sidhuvud

Det första alternativet finns inte. De två sista kräver nog kunskaper som antingen förvärvas genom att plugga djupt eller genom att vi nyttjar LAT och UEI som är kompetenta på det här. Alternativ 2 är vår backup om lokal kompetens inte mäktar med att lösa det hela.

**Comment by sa0mad** [comment]
Kan @tfritzon eller Täpp-Anders göra något här kanske? Specifik layout-issue vi behöver hjälp med.

**Comment by sikvall** [comment]
Det finns flera sätt. Jag är vän för att arbeta om rubrikerna så de blir mer hanterbara. I brist på vilja från författarna att göra så eller kan man nyttja följande:

`\chapter[det som skall stå i toc]{Det som skall stå på sidan}`

Om man gör så kommer det som hamnar i toc att stå i stället för \markleft eller \markright i huvudet.

En ytterligare variant är att nyttja makrot 

`\chaptermark{vad det skall stå i huvet}`

som inte ändrar i toc men ändrar det som trycks i huvudet.

Men än en gång, läs igenom exemplet ovan, nog kan det där snyggas till så att det blir funktionabelt med en bätre LIX?

Försök INTE typsätta huvudet på omväxlande antal rader eller \markleft och \markright på olika rader. Det ser helt sjukt ut och jag kommer nedkalla onda makter på den som gör sådant våld på \fancyhdr-paketet.

**Comment by fnadde42** [comment]
Låt denna vara öppen tills en lösning är implementerad

**Comment by sa0mad** [comment]
Åtgärdat allt jag sett.
