### ISSUE TITLE
Layout kap. 3.4.5

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#421]
Avsnittet om klass-B-förstärkare inleds med en bild av en klass-A-förstärkare.
Avsnittet om klass-C-förstärkare inleds med en bild av en klass-B-förstärkare.

Jo, jag vet, "det där ordnar vi sedan". Men just här tycker jag att layouten inte bara är ett skönhetsfel, utan den gör avsittet svårare att förstå,

**Comment by sa0mad** [comment]
Här har vi inte nått hela vägen fram, men de ligger på samma uppslag.
