### ISSUE TITLE
Missvisande rubrik Regler och trafikmetoder

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#428]
Kapitel 15 heter "Regler och trafikmetoder" och är två sidor långt. Det enda underkapitlet är "Loggbok" och i det konstateras att det inte finns någon regel om att föra loggbok. Trafikmetoder behandlas inte alls.

**Comment by SM7NTJ** [comment]
Det ursprungliga avsnittet "Regler och trafikmetoder" har delats upp och återfinns nu i kapitel 13 till och med 15.
Föreslår att 15.1 ges rubriken "Att skriva loggbok"
