### ISSUE TITLE
Överflödigt om prefix

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#440]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/c81895da074576b0c9c650d8b25a8c3606f69c0d/koncept/chapter2-3.tex#L130-L141

Den här delen om SI-prefix är onödig då det förklaras på annat ställe i boken. Vi sparar in några rader om det tas bort.

**Comment by Lominean** [comment]
Ok, jag har hittat åtminstone ett till ställe. Om alla prefixförklaringarna ska vara kvar, vilket är okej, så tycker jag att man ska dra ihop till en så kort text som möjligt i slutet på stycket istället för en massa egna rader. Typ så här:

> Eftersom 1 Ö är en stor måttenhet skriver man ofta med hjälp av prefixen i bilaga K. Till exempel är 1 nÖ samma som 0,000 000 001 Ö.

Jag tar bort ändringen från #442 så saken kan redas ut ordentligt.

**Comment by sikvall** [comment]
Bifaller @Lominean i denna fråga. Gör så.

**Comment by sa0mad** [comment]
Det skadar inte att skriva sådana här saker på flera ställen, för en del behöver få se det på flera sätt för att lära sig. Däremot kan man skriva det på komptaktare form, absolut.
