### ISSUE TITLE
Fonetisk skrift

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#441]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/c81895da074576b0c9c650d8b25a8c3606f69c0d/koncept/chapter2-1.tex#L40
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/c81895da074576b0c9c650d8b25a8c3606f69c0d/koncept/chapter2-1.tex#L62
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/c81895da074576b0c9c650d8b25a8c3606f69c0d/koncept/chapter1-8.tex#L1306
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/c81895da074576b0c9c650d8b25a8c3606f69c0d/koncept/chapter8-5.tex#L119
Det hade varit väldigt snyggt att använda [fonetisk skrift](https://sv.wikipedia.org/wiki/Internationella_fonetiska_alfabetet) för att beskriva hur sakerna uttalas.

**Comment by Lominean** [comment]
Jag håller med, i praktiken, men om ambitionen är att boken ska vara ett komplett referensverk så är det inte helt orimligt. Man kan ju till och med ha båda varianterna.

**Comment by sikvall** [comment]
Är frågan aktuell eller skall vi stänga den?
Jag vidhåller att visst kan vi införa fonetisk skrift men jag tror fler har problem med den än "bonnfånetiskan" som vi har i dag och den fyller ändå en funktion. Att ha båda skär sig lite.

Vad sägs?

**Comment by sm5phu** [comment]
Beslut: Bondfonetiska
