### ISSUE TITLE
Flytta koden

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#446]
När [Microsoft köpte](https://computersweden.idg.se/2.2683/1.703485/microsoft-kop-github) GitHub skedde det en relativ massflykt till [GitLab](https://www.gitlab.com). En fördel där är att CI-delen, det vi har [Travis CI](https://travis-ci.org) till idag, är helt integrerat. Och dessutom som grund baserad på [Docker](https://docker.com). Det här borde göra det avsevärt enklare att bygga den layoutade boken, som vi har problem med idag.

Jag funderar på om vi ska byta till något annat än GitHub. Inte nödvändigtvis GitLab, men det är det jag har mest – god – erfarenhet av för egen del.

Vi bör överväga i alla fall, till nästa revision och tryckning. Relaterat är #6 #55 #159 #191 #206 #370 #445

**Comment by kyrias** [comment]
> Och dessutom som grund baserad på Docker.

Både Travis och GitLab CI har Docker support som en extra funktion man kan använda dock, så *det* är inte direkt en anledning att flytta, men att det är integrerat är ju rätt smidigt, som t.ex. att det går att ladda up artefakter direkt till GitLab.

**Comment by sikvall** [comment]
Ja Det är ju tråkigt att byggservern skall vara så urmodig att det inte får
använda paket som funnits i CTAN i 15 år...

Och att vi måste ha den. Varför?

/Anders

**Comment by fnadde42** [comment]
Jag har länge funderat på att vi borde använda oss av [Buildbot](http://buildbot.net/) som vi skulle kunna köra på SSA:s server för att bygga det vi behöver. Dock kör SSA Ubuntu 14.04 på sin server så det skulle nog behövas en uppgradering för att, med enkelhet, köra med moderna verktyg och beroenden. Den går också att koppla till GitHub som en "check" vid incheckning av ny kod och Pull Requests.

**Comment by kyrias** [comment]
I min fork har jag som ett exempel skrivit om Dockerfilen till att vara baserad på Alpine istället för Debian, och har konfigurerat Travis till att bygga i Docker containern.  Den skapar också GitHub releaser för varje master build, och laddar up `koncept.pdf` till den nya GitHub releasen.

**Comment by fnadde42** [comment]
Med "master build" menar du bygge på master? Det tycker jag låter som en bra idé. I så fall måste vi börja utveckla på en develop-branch och använda master till "stable"-releases som man gör i [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/).

Gör en Pull Request på de förändringar som du talar om så kan börja jobba för att implementera dom. I så fall skulle vi kanske slippa byta plattform.

**Comment by kyrias** [comment]
Ja precis.  Som jag har det nu så skapas de som prereleases (se <https://github.com/kyrias/SSA-Akademin/releases>), men när man taggar en version och prereleasen har skapats, så kan man gå in och klicka ur en checkbox så den blir en vanlig release istället.  Det går också att säga till den att bara skapa releaser när det är en ny tag som byggs.

**Comment by fnadde42** [comment]
Jag skulle visserligen inte vilja att det skapades pre-releases varje gång vi bygger eftersom vi ibland har byggt [100 gånger på en månad](http://akademin.ssa.se/files/koncept-pdf/). Release-sidan på GitHub skulle vara full av crap att gå igenom för att hitta något värdefullt. Däremot skulle jag vilja använda oss av en branch-strategi där vi utvecklar på develop och merge:ar in till master när vi vill bygga, antingen en pre-relese eller, en release likt [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/).

**Comment by Lominean** [comment]
Så som @kyrias har fixat var väl ambitionen från början men så ska det ju göras också. Tummen upp!

Om ingen har något mer i ärendet så stänger jag denna _issue_ om någon dag.

**Comment by sa0mad** [comment]
Det som vi sagt är att det är ju de taggade releaserna som skall läggas upp. Allt anant är per definition develop/test-byggen.
