### ISSUE TITLE
Framsidan måste fixas

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#45]
Just nu är titeln på framsidan justerad åt vänster och alldeles för liten. Ett förslag kan ju vara att göra texten så här (minus logotypen förstås):

![koncept](https://user-images.githubusercontent.com/1107419/29666367-45e85a50-88d8-11e7-8382-1e372e4b688f.png)

**Comment by sa0mad** [comment]
Ja, men vad väntar du på? Skriv med amatörradiocertifikat.

**Comment by sa0mad** [comment]
Krävs nog någon mer LaTeX layout-guru än mig, för jag får inte riktigt till det. @tfritzon kanske har någon ide som fungerar bättre än min.

**Comment by sa0mad** [comment]
Jag kom inte så långt, men ett försök har gjorts. Någon kanske kan ta det sista steget.

**Comment by sa0mad** [comment]
Åtgärdad

**Comment by fnadde42** [comment]
Texten på framsidan skulle kunna vara större men fram för allt så verkar den vara sidojusterad som sidorna i boken verkar vara (för att undvika att texten hamnar i vecket på boken). Hur tar man bort den justeringen för endast framsidan?

**Comment by sa0mad** [comment]
I den här fasen ska vi inte detalj-pilla layout. Låt de som gör layout ta hänsyn till det när de börjar jobba med det. Just nu är det här bara störningar. Fokusera på att granska innehållet.

**Comment by fnadde42** [comment]
Öppnar igen för att fixa framsidan

- Minska SSA-logotyp nere i hörnet
- Ta bort svart kant nedtill
- (Göra logotypen en del av framsidebilden?)

**Comment by sa0mad** [comment]
I layout-jobbet blev framsidan helt utbytt.
