### ISSUE TITLE
Skapa kursplansdokument

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#452]
För att hjälpa studenter och klubbar som håller kurs borde en tentativ kursplan skapas som ger referenser in i boken för de olika del-kapitel som behöver gås igenom för att läsa en kurs som uppfyller HAREC-kraven.

En första skiss finns redan påbörjad.

**Comment by Lominean** [comment]
Adress för den som är ny till koden: https://github.com/SverigesSandareamatorer/SSA-Akademin/tree/master/lectures

**Comment by sikvall** [comment]
Anser vi med läsanvisningarna att detta är uppfyllt nu?

**Comment by sa0mad** [comment]
Eftersom det nu är inkluderat i bok anser jag att denna är uppfylld.

**Comment by sikvall** [comment]
Jag har uppfattat detta som nog något annat än läsanvisningarna. En
kursplan är kanske mer i vilken ordning man bör ta läsanvisningarna och hur
man uppdelar det på studietillfällen.

**Comment by sa0mad** [comment]
I så fall så får jag väl återöppna issuen.

**Comment by sikvall** [comment]
Jag vet ju inte men kanske originalförfattaren kan förtydliga?

Den mån 18 nov. 2019 11:08Magnus Danielson <notifications@github.com> skrev:

**Comment by sm5phu** [comment]
Städa bort kursplan.tex och stäng därefter.
