### ISSUE TITLE
Tydligare markera fördjupning

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#453]
För de som använder KonCEPT som kursbok behöver en tydligare separering av vad som kan anses ingå i en HAREC-baserad kurs och det som är fördjuppande material göras. Därför behöver jämte HAREC markering även fördjupningsmarkering göras.

**Comment by sikvall** [comment]
Vi har ju nu en lista på vad som ingår i certifikatskunskaperna. Räcker detta eller vad är fördjupning enligt ovan?

**Comment by sm5phu** [comment]
Läsanvisningarna pekar ut grundnivån. Allt annat är födjupning.
