### ISSUE TITLE
Ställa in XeLaTeX istället för pdfLaTeX

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#455]
Vi borde gå över till att använda XeLaTeX nu när vi har en Docker-container med fräscha beroenden. Se issue #206 och Pull Request #215.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/71a64f6355281f943c22a03590510841dabfdc01/Makefile#L106-L115

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/71a64f6355281f943c22a03590510841dabfdc01/Makefile#L136-L142

**Comment by sa0mad** [comment]
Varför behöver vi gå över till XeLaTeX? Vad är det för problem som behöver lösas? Det har varit en massa vilt hoppande förut och det skall inte behövas. Jag motsätter mig tills vi har en klar bild om problemet.

**Comment by fnadde42** [comment]
Vad jag vill minnas vad det ett evligt h-vete med unicode-tecken men det kanske är löst, eller? För annars håller jag med om att det inte finns någon anledning att gå över till XeLaTeX.

**Comment by sa0mad** [comment]
Det är ju det här man skall ha @tfritzon och @sikvall involverade i. Låt oss börja med att titta på problemet och se hur det kan lösas.

**Comment by sikvall** [comment]
Magnus Danielson <notifications@github.com> writes:

> Det är ju det här man skall ha @tfritzon och @sikvall involverade i.
> Låt oss börja med att titta på problemet och se hur det kan lösas.

Jag är lite oinsatt men kör unicode utan problem med pdflatex själv,
dock är xelatex en modernare tex men den är inte utan problem den heller
för den bryter lite saker som traditionellt fungerat genom att man har
lite ny filosofi.

XeLaTeX använder OS-specifika saker för att hantera WTF-8 och annat
vilket gör att det som fungerar för windowsanvändaren kan eventuellt
också fungera på Mac eller Linux. Vitsen är väl att man kan skriva µH
direkt i såsen och få det rendera rätt i stället för att använda makrot
\textmu och liknande saker.

Den supportar även systmefonter direkt som inbäddning i PDF, inte heller
något som man kanske måste sträva efter då jag tycker de fonter som
används skall antingen tillhöra TeX standardfonter eller fonter
anpassade för TeX snarare än importera fonter från windows, mac osv då
det också kan skapa systemberoenden som är oönskade.

LuaTeX är också en populär maskin för att köra TeX men jag kan den inte
så väl.

Vad var det för problem vi skulle lösa med XeLaTex, jag har nog glömt
historiken?

-- 
Anders Sikvall          http://anders.sikvall.se/
Xindi.ichimusai.org     Using GNUS for mail and news

**Comment by sikvall** [comment]
Petter Karkea <notifications@github.com> writes:

> Jag tycker att vi tar bort alla referenser till XeLaTeX och så tar vi
> upp debatten igen den dagen det blir aktuellt. Det verkar ju som att
> pdfLaTeX har fungerat bra hittills. *Don't fix it if it ain't broke*.

Håller med.

-- 
Anders Sikvall          http://anders.sikvall.se/
Xindi.ichimusai.org     Using GNUS for mail and news
