### ISSUE TITLE
Se till att PDF:er kan jämföras med checksumverktyg

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#456]
@kyrias skrev i [en kommentar](https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/449#issuecomment-423841120):

> Jag satte i min andra branch `SOURCE_DATE_EPOCH=0` när PDF:en byggs så att xelatex använder 0 som datumet, så att PDF:erna får samma kontrollsumma varje gång, för att se till att de byggs rätt.

Detta skulle möjliggöra jämförelser av byggen av samma PDF för att kontrollera att det blivit rätt. En liten grej men trevlig sak att kunna göra. Kanske @kyrias kan göra en PR med denna förändring?

Jag tänker mig att man kan lägga en variabel så att när man vill ha datum så kan man skicka in det med make kommandot.

**Comment by Lominean** [comment]
Om man vill kunna jämföra mellan datorer och program så finns väl risken att programmet skriver med sitt namn och versionsnummer i filen? Har för mig att det finns ett fält i PDF för just det. Är det testat så det fungerar?

**Comment by fnadde42** [comment]
Jag tror det är om man genererar en PDF ifrån programmet så som "Spara som..." eller "Spara kopia...". Annars genereras det ju alltid med samma verktyg; pdflatex.

**Comment by sikvall** [comment]
Petter Karkea <notifications@github.com> writes:

> @kyrias skrev i [en
> kommentar](https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/449#issuecomment-423841120):
> 
>> Jag satte i min andra branch `SOURCE_DATE_EPOCH=0` när PDF:en byggs
> så att xelatex använder 0 som datumet, så att PDF:erna får samma
> kontrollsumma varje gång, för att se till att de byggs rätt.
> 
> Detta skulle möjliggöra jämförelser av byggen av samma PDF för att
> kontrollera att det blivit rätt. En liten grej men trevlig sak att
> kunna göra. Kanske @kyrias kan göra en PR med denna förändring?
> 
> Jag tänker mig att man kan lägga en variabel så att när man vill ha
> datum så kan man skicka in det med make kommandot.

Vi borde finna ett bättre sätt tänker jag. Har vid annat tillfälle bara
pajpat PDF:erna genom "strings" och diffat på resultatet, då kommer iofs
datumen sticka ut men om inget mer gör det så är det ju rätt stor chans
det är samma innehåll.

-- 
Anders Sikvall          http://anders.sikvall.se/
Xindi.ichimusai.org     Using GNUS for mail and news

**Comment by sa0mad** [comment]
Man ska inte ha sönder datumet för våra normala byggen. Det är fel (TM). Om ni har speciella test-behov så är det väl en sak, men inget sådant får riskera att ha sönder våra normala byggen.

**Comment by Lominean** [comment]
Inte det ni är ute efter tror jag men jag vill ändå framhålla att checksummor för det senaste årets byggen finns i loggarna 👇
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/71a64f6355281f943c22a03590510841dabfdc01/.travis.yml#L20

**Comment by sikvall** [comment]
Kan vi stänga denna?

**Comment by fnadde42** [comment]
Det skulle jag säga. Öppna igen om det önskas.
