### ISSUE TITLE
Rensa upp en massa varningar? (Label multiply defined, undefined references, Not defining x, Option y has already been used)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#457]
Det är svårt att få en överblick när det kommer till utskriften ifrån `pdfLaTeX` och därför testade jag använda verktyget [`pydfLaTeX`](https://github.com/olivierverdier/pydflatex) som ger en sammanfattning. Vi har en massa varningar, vissa som förekommer mer än andra, men min fråga är om det är något vi borde göra något åt. Jag har fått lära mig att man ofta ska behandla varningar som fel (`-Werror=`) men det kanske inte gäller i LaTeX... eller? @sikvall @tfritzon 

Det här är något som bland annat påverkar webbygget (#6, #454).

Körningen är gjord på senaste committen i master: https://github.com/SverigesSandareamatorer/SSA-Akademin/commit/71a64f6355281f943c22a03590510841dabfdc01

<pre><font color="#729FCF"><b>$</b></font> pydflatex koncept.tex
        <b>[2018-10-19 11.53.12] pdflatex koncept.tex</b>
<b>This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)</b>
<font color="#75507B">Label `myHAREC.a.1.1.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.1.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.1.1.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.1.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.1.8.5&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.1.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.1.1.4&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.1&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.4&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.9&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.9&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.9&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.9&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.a.3.2.9&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.1.1&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.1.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.1.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.1.4&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.1.5&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.2.1&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.2.2&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.2.3&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.3.1&apos; multiply defined.</font>
<font color="#75507B">Label `myHAREC.b.3.2&apos; multiply defined.</font>
<font color="#75507B">Label `decibel&apos; multiply defined.</font>
p.    L21   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.    L33   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.    L40   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.    L86   : [<font color="#EF2929"><b>DARCaus</b></font>] undefined
p.    L14   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.    L21   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.8   L316  : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.8   L375  : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.8   L439  : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.9   L491  : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.16  L171  : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.23  L147  : [<font color="#EF2929"><b>ott1988</b></font>] undefined
p.84  L335  : [<font color="#EF2929"><b>letrafo</b></font>] undefined
p.111 L496  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.143 L54   : [<font color="#EF2929"><b>K27-1991</b></font>] undefined
p.143 L55   : [<font color="#EF2929"><b>K27-1991</b></font>] undefined
p.143 L66   : [<font color="#EF2929"><b>K27-1991</b></font>] undefined
p.143 L115  : [<font color="#EF2929"><b>ott1988</b></font>] undefined
p.144 L175  : [<font color="#EF2929"><b>ott1988</b></font>] undefined
p.145 L304  : [<font color="#EF2929"><b>K27-1991</b></font>] undefined
p.146 L431  : [<font color="#EF2929"><b>K27-1991</b></font>] undefined
p.189 L30   : [<font color="#EF2929"><b>SIbrochure8</b></font>] undefined
p.195 L33   : [<font color="#EF2929"><b>Rothammel2001</b></font>] undefined
p.223 L130  : [<font color="#EF2929"><b>ARRLHDB2015</b></font>] undefined
p.228 L186  : [<font color="#EF2929"><b>ARRLHDB2015</b></font>] undefined
p.243 L35   : [<font color="#EF2929"><b>SFS1992:1512</b></font>] undefined
p.243 L40   : [<font color="#EF2929"><b>SFS2016:363</b></font>] undefined
p.243 L64   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.243 L66   : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.253 L64   : [<font color="#EF2929"><b>SSMFS2008:18</b></font>] undefined
p.253 L67   : [<font color="#EF2929"><b>1999/519/EG</b></font>] undefined
p.254 L141  : [<font color="#EF2929"><b>SSMFS2008:18</b></font>] undefined
p.254 L167  : [<font color="#EF2929"><b>1999/519/EG</b></font>] undefined
p.255 L304  : [<font color="#EF2929"><b>OETbul65b</b></font>] undefined
p.259 L688  : [<font color="#EF2929"><b>SSMFS2008:18</b></font>] undefined
p.259 L696  : [<font color="#EF2929"><b>OETbul65b</b></font>] undefined
p.259 L698  : [<font color="#EF2929"><b>1999/519/EG</b></font>] undefined
p.262 L57   : [<font color="#EF2929"><b>SFS2016:392</b></font>] undefined
p.269 L32   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.269 L33   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.269 L63   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.269 L67   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.270 L13   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.270 L39   : [<font color="#EF2929"><b>TSFS2009:95</b></font>] undefined
p.270 L59   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.272 L69   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.272 L73   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.272 L86   : [<font color="#EF2929"><b>TampereConvention</b></font>] undefined
p.272 L110  : [<font color="#EF2929"><b>IARU-ETG</b></font>] undefined
p.273 L7    : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L9    : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L19   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L21   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L39   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L58   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L68   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.273 L74   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.274 L179  : [<font color="#EF2929"><b>TR6101</b></font>] undefined
p.276 L377  : [<font color="#EF2929"><b>LowBandDX</b></font>] undefined
p.277 L465  : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.277 L474  : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.277 L523  : [<font color="#EF2929"><b>SFS1998:204</b></font>] undefined
p.277 L524  : [<font color="#EF2929"><b>GDPR</b></font>] undefined
p.277 L525  : [<font color="#EF2929"><b>SFS1962:700</b></font>] undefined
p.279 L21   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.279 L25   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.279 L88   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.279 L89   : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.281 L30   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L51   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L67   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L73   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L77   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L88   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L93   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L98   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L103  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L108  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L114  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.281 L118  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L122  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L126  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L131  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L137  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L143  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L149  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L159  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L178  : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.282 L32   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.282 L39   : [<font color="#EF2929"><b>TR6101</b></font>] undefined
p.282 L46   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.283 L13   : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.283 L52   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.283 L53   : [<font color="#EF2929"><b>SFS2003:396</b></font>] undefined
p.283 L61   : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.283 L74   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.284 L103  : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.284 L111  : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.284 L147  : [<font color="#EF2929"><b>TR6101</b></font>] undefined
p.284 L148  : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.284 L149  : [<font color="#EF2929"><b>SFS2003:389</b></font>] undefined
p.284 L150  : [<font color="#EF2929"><b>SFS2003:396</b></font>] undefined
p.284 L152  : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.285 L25   : &apos;<font color="#EF2929"><b>loggblad</b></font>&apos; undefined
p.287 L56   : [<font color="#EF2929"><b>M1677-1</b></font>] undefined
p.290 L362  : &apos;<font color="#EF2929"><b>provtext</b></font>&apos; undefined
p.305 L14   : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.309 L9    : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.312 L220  : [<font color="#EF2929"><b>TR6101</b></font>] undefined
p.313 L14   : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.313 L81   : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.315 L154  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.316 L216  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.317 L279  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.317 L294  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.317 L322  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.318 L349  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.318 L366  : [<font color="#EF2929"><b>IARU1</b></font>] undefined
p.319 L7    : [<font color="#EF2929"><b>ITU-RR</b></font>] undefined
p.319 L17   : [<font color="#EF2929"><b>SFS2003:396</b></font>] undefined
p.319 L19   : [<font color="#EF2929"><b>PTSFS2015:3</b></font>] undefined
p.319 L38   : [<font color="#EF2929"><b>PTSFS2015:4</b></font>] undefined
p.325 L6    : [<font color="#EF2929"><b>TR6102</b></font>] undefined
p.325 L62   : &apos;<font color="#EF2929"><b>myHAREC.I.d.2a</b></font>&apos; undefined
p.325 L62   : &apos;<font color="#EF2929"><b>myHAREC.I.d.2b</b></font>&apos; undefined
p.325 L93   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.2a</b></font>&apos; undefined
p.325 L93   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.2b</b></font>&apos; undefined
p.325 L93   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.2c</b></font>&apos; undefined
p.325 L94   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.3a</b></font>&apos; undefined
p.325 L94   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.3b</b></font>&apos; undefined
p.325 L94   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.3c</b></font>&apos; undefined
p.325 L95   : &apos;<font color="#EF2929"><b>myHAREC.a.1.1.4b</b></font>&apos; undefined
p.326 L173  : &apos;<font color="#EF2929"><b>myHAREC.a.1.8.5a</b></font>&apos; undefined
p.326 L173  : &apos;<font color="#EF2929"><b>myHAREC.a.1.8.5b</b></font>&apos; undefined
p.327 L354  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.1h</b></font>&apos; undefined
p.327 L356  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.2a</b></font>&apos; undefined
p.327 L356  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.2b</b></font>&apos; undefined
p.327 L359  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.3a</b></font>&apos; undefined
p.327 L359  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.3b</b></font>&apos; undefined
p.327 L359  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.3c</b></font>&apos; undefined
p.327 L360  : &apos;<font color="#EF2929"><b>myHAREC.a.3.1.3d</b></font>&apos; undefined
p.327 L366  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.1b</b></font>&apos; undefined
p.327 L368  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.2b</b></font>&apos; undefined
p.327 L371  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.4b</b></font>&apos; undefined
p.327 L383  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.9a</b></font>&apos; undefined
p.327 L384  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.9b</b></font>&apos; undefined
p.327 L384  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.9c</b></font>&apos; undefined
p.327 L384  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.9d</b></font>&apos; undefined
p.327 L385  : &apos;<font color="#EF2929"><b>myHAREC.a.3.2.9e</b></font>&apos; undefined
p.330 L944  : &apos;<font color="#EF2929"><b>myHAREC.c.1.1</b></font>&apos; undefined
p.330 L946  : &apos;<font color="#EF2929"><b>myHAREC.c.1.2</b></font>&apos; undefined
p.330 L948  : &apos;<font color="#EF2929"><b>myHAREC.c.1.3</b></font>&apos; undefined
p.330 L950  : &apos;<font color="#EF2929"><b>myHAREC.c.1.4</b></font>&apos; undefined
p.330 L952  : &apos;<font color="#EF2929"><b>myHAREC.c.1.5</b></font>&apos; undefined
p.330 L958  : &apos;<font color="#EF2929"><b>myHAREC.c.2.1</b></font>&apos; undefined
p.330 L960  : &apos;<font color="#EF2929"><b>myHAREC.c.2.2</b></font>&apos; undefined
p.330 L962  : &apos;<font color="#EF2929"><b>myHAREC.c.2.3</b></font>&apos; undefined
p.330 L968  : &apos;<font color="#EF2929"><b>myHAREC.c.3.1</b></font>&apos; undefined
p.330 L970  : &apos;<font color="#EF2929"><b>myHAREC.c.3.2</b></font>&apos; undefined
p.331 L5    : [<font color="#EF2929"><b>KonCEPT1</b></font>] undefined
p.331 L15   : [<font color="#EF2929"><b>ARRLHDB2015</b></font>] undefined
p.331 L21   : [<font color="#EF2929"><b>DARCaus</b></font>] undefined
p.331 L75   : [<font color="#EF2929"><b>Rothammel2001</b></font>] undefined
<font color="#75507B">Option `pdftex&apos; has already been used, setting the option has no effect.</font>
<font color="#75507B">fixltx2e is not required with releases after 2015 All fixes are now in the LaTeX kernel. See the latexrelease package for details.</font>
<font color="#75507B">Not defining \perthousand.</font>
<font color="#75507B">Not defining \micro.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">Font shape `U/stmry/b/n&apos; undefined using `U/stmry/m/n&apos; instead.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`!h&apos; float specifier changed to `!ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">Float too large for page by 16.755pt.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`!h&apos; float specifier changed to `!ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">`h&apos; float specifier changed to `ht&apos;.</font>
<font color="#75507B">Some font shapes were not available, defaults substituted.</font>
<font color="#EF2929"><b>There were undefined references.</b></font>
<font color="#EF2929"><b>There were multiply-defined labels.</b></font>
<font color="#8AE234"><b>Typesetting of &quot;koncept.tex&quot; completed in 19.6s.</b></font>
</pre>

**Comment by sikvall** [comment]
Jo det bör man. Det finns dock lite olika saker att vara uppmärksam på.

Overful och underful box (hbox/vbox) betyder att raden eller sidan är över-
eller underfull och man har ett layoutproblem, man bör fixa främst
överfulla lådor.
Saknade referenser dyker upp som ?? i texten så det är definitivt en
prioriterad sak att fixa. Makrot som används för att peka ut HAREC-delarna
har genomgått ett par olika generationer av olika trasighet och det är det
som syns nu. Det bör vi styra upp på ett vettigt sätt. Där tror jag att jag
och Magnus bör sätta oss vid tillfälle och bara ta en efter en och beta av
och sedan designa ett vettigt makro för det en gång för alla.

De här andra sakerna som pekar på att ITU-RR är odefinierad mm beror
sannolikt på att man inte kört bibtex ordentligt.

Float specifier changed from 'h' to 'ht'. Vad det betyder egentligen är att
man vill att en bild skall sättas vid ett visst textstycke genom att man
specificerar [h] (here) men den får inte plats så systemet har ändrat till
[ht] vilket betyder (here or top of next page). Den där biten är inte
kritisk och något man normalt inte behöver jaga bort för de kommer igen när
man lägger till ett stycke text tidigare i kapitlet osv. I stället bör man
kontrollera i layoutprocessen att bilden inte flutit iväg för långt.

Ibland kan man skapa en särskild sida/sidor i ett stycke och skicka floats
som figurer, tabeller mm dit. Det är oftast inte bästa lösningen men ibland
är det snyggt. Vi har ju lite jobb kvar med bilder i figures som kan behöva
pillas med så inget konstigt.

Font shape `U/stmry/b/n' undefined using `U/stmry/m/n' instead.


Antagligen har man använd math env i en rubrik eller något annat som gör
det pysslade till sig här. Man får kolla på sidan som den kastade felet på.
Jag såg det på något ställe att man kört in ett matteenv för att få till
något specialtecken. Det finns andra lösningar oftast för sånt så vi kan
kika på det.

/Anders

fre 19 okt. 2018 kl 11:57 skrev Petter Karkea <notifications@github.com>:

**Comment by sa0mad** [comment]
Jag har tidigare gjort en hel del sökningar i log-filen som sedan byggde på filen TODOs.txt som jag sen kämpade med att minskal längden på, felmeedelande för felmeddelande. Jag lyckades dock inte få grep att inte kasta varning om den inte hittade något, så jag tvingades kommentera bort saker. De finns dock kvar i Makefilen om ingen städat bort dem av misstag.

bibtex måste köras rätt, och jag har byggt lokgiken i Makefilen för att det skall byggas korrekt. Tyckte mig se att någon var och pillade på bygg-logiken och det är olyckligt för det har sönder det som måste finnas. Den kan säkert göras bättre men jag tror att det är något där Anders och jag kan lista ut det rätta sättet, men att "sannera" bygg-strukturen skapar fel och motverkar projektet, så låt bli det utan att jag är explicit med på det.

Låt mig titta på vad som trillar ut och se på det. En del HAREC fel dök upp när HAREC macrot skrevs om, vilket är olyckligt, jag tror att det är fixat nu. En hel del referenser blev fel för att bibtext och hur byggen måste göras för att alla skall fångas upp.

**Comment by sa0mad** [comment]
Jag överväger att införa frysning av repot och förändringar tills vi släppt för nästa tryckning, det sker för mycket osynkade förändringar och just nu är stabilitet och byggbarhet viktigare än "låt oss prova det här".

**Comment by sikvall** [comment]
Det är helt fine att labba och dona men avvakta med att pusha in sådant
just nu. Det är bättre om vi jobbar med att


   - Fixa till bilder, storlekar, placering och generellt utseende varierar
   lite för mycket
   - Fixar overfull hbox, meddelandet betyder att den inte får plats på
   raden och blöder ut i marginalen vilket är osnyggt. Enklast är genom att
   leta upp meningen som orsakar varningen och se till att sk\-r\-i\-va in
   av\-stav\-nings\-tecken så TeX får lättare att avstava. Detta blir svårare
   och svårare ju smalare spalt man har. Ibland får man ändra formuleringen
   lite så det blir synonymt men lite andra ord.
   - Se över matematiksättningen, det finnjs en uppsjö märkligheter i
   diverse formler, jag städade hundratals sådant i första layouten men som
   aldrig blev mergeat till master
   - Referenserna är fortfarande trasiga på några ställen, rätt bibtexbygge
   för att fixa det, men också de referenser som är handknackade på sina håll
   kanske inte pekar på rätt makro, hur som finns det några ?? som behöver bli
   av med.
   - Jag och Magnus skall kika på HAREC-makrot och försöka lösa det, inte i
   kväll men när vi ses vid tillfälle ska vi dona lite så lämna det så länge.
   - Ändringar i byggsystemet, style-filer och annat som hör till
   "infrastrukturen" skall vi helst undvika men fixar vi buggar bör vi
   diskutera dem tillsammans för det börjar bli en del komplexitet i det hela.
   - Bilder skall ritas om och konverteras till något vettigt format (svg?)
   som kan redigeras enkelt (InkScape) eller motsvarande. Här kan man gärna ta
   sig en funderare på vad som är bäst. Det finns också TikZ som gör man kan
   bygga figurer direkt i koden vilket ofta fungerar bra, nu är jag ingen
   hävert på just det paketet men tror LAT har lite erfarenhet.
   - etc etc

Som Magnus sade, vi skall fokusera på det som inte blev rätt, snyggt eller
bra i senaste trycket. Efter nästa tryck om sisådär en månad då kan vi byta
ut hela byggsystemet om vi nu vill det (det tror jag inte) men då kan vi ta
nappatag med de mer strukturella problemen som vi kanske fångar up.

fre 19 okt. 2018 kl 13:42 skrev Magnus Danielson <notifications@github.com>:

**Comment by fnadde42** [comment]
Eftersom webbgenereringen inte kan hantera så pass "allvarliga" fel så lägger jag locket på den grytan tills vidare och fortsätter med annat tills när vi fixat det här.
