### ISSUE TITLE
Amatörradiocertifikat eller Radioamatörcertifikat?

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#46]
Då är ju frågan (som jag har sett på kommentarer i boken) om det ska heta _Amatörradiocertifikat_ eller _Radioamatörcertifikat_. Jag tycker att amatörradiocertifikat rullar bättre på tungan men å andra sidan radioamatör ett mer vardagligt använt ord.

Om jag skulle vara tvungen att välja så skulle jag ta amatörradiocertifikat då det låter bättre och är den terminologin som [PTS](http://www.pts.se/sv/Privat/Radio/Amatorradio/Amatorradiocertifikat/) använder.

**Comment by Lominean** [comment]
Finns det någon annan, förutom PTS, som man kan snegla på?

Jag frågar [Språkrådgivningen](http://www.sprakochfolkminnen.se/sprak/sprakradgivning) och ser vad de tycker…

**Comment by sa0mad** [comment]
Amatörradiocertifikat är svaret från mig och vad gallupen här säger.

**Comment by sa0mad** [comment]
Anpassade titeln enligt vad som verkar vara total enighet.

**Comment by Lominean** [comment]
Språkrådet svarade "Amatörradiocertifikat tycks vara den etablerade benämningen."
