### ISSUE TITLE
Korrigering till PTSFS 2018:3

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#460]
I och med PTSFS 2018:3 har utkommit skall Koncept anpassas till dess innehåll.

**Comment by sa0mad** [comment]
En PTS tjänsteman påminde mig, så det var lika bra att ta tag i det.

**Comment by fnadde42** [comment]
Jag försöker hitta en motivering till att sänka maxeffekten till 200W men hittar inte det på PTS hemsida. Någon som vet? Har det varit ett problem?

**Comment by sa0mad** [comment]
Vi tar det offline och inte här.
