### ISSUE TITLE
2.2.5 Kondensatorn i likströmskretsen

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#467]
I kapitel 2.2.5 beskrivs kondensatorn i likströmskretsen. Där förklaras laddningsmängd och uppladdnings- och urladdningsförlopp. Men ingenstans nämner vi explicit den mest grundläggande egenskapen, att konstensatorn blockerar likström.

**Comment by sikvall** [comment]
Denna kan återöppnas efter jag rullat tillbaka mina ändringar.

**Comment by SM7NTJ** [comment]
Fixad via PR #546
