### ISSUE TITLE
Försättssida Isolation och jordning

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#47]
Alla (?) kapitel börjar med en sida där bara kapitelnummer och kapitelnamn står, förutom kapitlet _Isolation och jordning_ där innehållstexten kommer direkt efter på samma sida.

**Comment by sa0mad** [comment]
Åtgärdat.

**Comment by fnadde42** [comment]
Fixad med: https://github.com/SverigesSandareamatorer/SSA-Akademin/commit/1f3731043b416ad6099f7e0f6aa0b2a4756ae387
