### ISSUE TITLE
Byta ut manliga pronomen emot något mer neutralt

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#471]
Radioamatören är nödvändigtvis inte en "han" och boken borde återspegla det. Det här är ett av ställena som det återfinns på men ska söka igenom lite noggrannare. Förslagsvis byta ut "hans" emot "amatörens".

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/1122c39b2fcf0e84100658fb2bcf4a0bc13bee37/koncept/chapter13-5.tex#L553-L572

**Comment by Lominean** [comment]
Amatören kan skriva _hen_. Det finns redan [minst ett hen](https://github.com/SverigesSandareamatorer/SSA-Akademin/commit/833833df8d4bba1d9f928c3c7c7bb70a0203887c).

**Comment by fnadde42** [comment]
Ok. Visste inte att det redan fanns. För vissa så är *hen* lite laddat men det är onekligen ett praktiskt ord. Jag är för att vi systematiskt går och byter ut till könsneutrala pronomen som *hen* och *henom*.

**Comment by sikvall** [comment]
Jag har personligen inget mot det men jag hade hellre använt skrivningar
som "den", och "amatören" eller "personen" osv då det är mer accepterat
fortfarande. Beror ju på vad man vill men eftersom amatörradion är en hobby
som slutförvarar en rätt stor mängd surkartar redan kanske kan man tänka
sig det retar en hel del människor.

I övrigt ingen synnpunkt på det. Jag finner det också praktiskt men
förordade att vi skulle låna in det finska "hän" i stället då jag tycker vi
har för få finska låneord i språket.

Mvh,
*Täpp-Anders Sikvall*
PGP Key ID EF53EECE <anders@sikvall.se>
Fingerprint C226 1919 C442 3661 4A76  B749 C2D9 E688 EF53 EECE



Den sön 14 apr. 2019 kl 07:53 skrev Petter Karkea <notifications@github.com

**Comment by fnadde42** [comment]
Det var lite så jag tänkte. Privat använder jag *hen* men precis som boken är konservativ i sin kunskap och bygger på etablerad fakta så kanske vi ska låta *hen* inarbetas av mer progressiva krafter tills det är lika självklart och etablerat som faktan i denna bok. Tills dess kan vi faktiskt använda "den", "amatören" eller "personen".

**Comment by sikvall** [comment]
Har fixat det "hen" som fanns i texten som jag hittade. Stänger tills vidare, kan öppnas igen om det blir omtag i så fall.
