### ISSUE TITLE
Enkelspalt när det borde vara helsida, s16

### ISSUE THREAD

**Issue by sikvall** [SverigesSandareamatorer/SSA-Akademin#472]
Sidan 16 har dubbelspalt fast texten bara fyller tre små stycken. Ser inte bra ut layoutmässigt.

**Comment by SM7NTJ** [comment]
Ett sätt att lösa detta skulle kunna vara att flytta texten från preface till
tryckort. Raderna skulle då kunna placeras i det tomma utrymmet över "förlag" eller under rubriken före upplagetexten.
