### ISSUE TITLE
Begreppet UKV bör vara sekundärt och ersättas av VHF i förekommande fall

### ISSUE THREAD

**Issue by sikvall** [SverigesSandareamatorer/SSA-Akademin#488]
Exempelvis i bilden 1.14 förekommer uttrycket UKV vilket är mer ovanligt i dag och i princip bara används på äldre mottagare för rundradio på 3-metersbandet. VHF bör vara det primära uttrycket och UKV tas med som historisk förklaring till förkortningen.

**Comment by sa0mad** [comment]
Jag håller med. Begreppet skall inte helt försvinna, för det används dels historiskt och ibland som kuriosa, men det skall inte vara det primära begreppet.

**Comment by Lominean** [comment]
UKV är inte med sakregistret. Det borde det nog vara.
