### ISSUE TITLE
TODOs behöver addresseras

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#49]
Idag har vi en lång lista TODOs taggade i texten, de är:

1. koncept/chapter1-1.tex:262:\hilight{TODO: Kolla att figur-referensen fungerar.}
2. koncept/chapter1-1.tex:499:\hilight{TODO: NTJ Bilden på snurran ser ut att hamn a högt i tabellen ovan.}
3. koncept/chapter1-6.tex:143:\hilight{TODO: Här hade det varit bra med en bild på pendeln. /SM7NTJ}
4. koncept/chapter1-7.tex:140:\hilight{TODO: Illustrera resistor, brus en och in.}
5. koncept/chapter1-7.tex:142:\hilight{TODO: Illustrera brus över tid.}
6. koncept/chapter1-7.tex:144:\hilight{TODO: Illustrera brus över frekvens.}
7. koncept/chapter1-10.tex:69:\hilight{TODO: illustrera sampling}
8. koncept/chapter1-10.tex:83:\hilight{TODO: illustrera kvantisering och PCM}
9. koncept/chapter1-10.tex:174:\hilight{TODO: illustrera viknings-spektrum}
10. koncept/chapter2-5.tex:120:  \hilight{TODO:  här borde vi även ta upp moderna powerledar som kräver
11. koncept/chapter2-6.tex:40:\hilight{TODO: Bild på transistor saknas (ej numrerad)}
12. koncept/chapter2-8.tex:149:\hilight{TODO: Bilden felaktig. Jämför med bild 2.37 och-kretsen.
13. koncept/chapter3-1.tex:387:\hilight{TODO: Fixa flödet runt bilderna här.}
14. koncept/chapter3-4.tex:8:\hilight{TODO:  Det pratas allmänt mycket om rörförstärkare i det här avsnittet.
15. koncept/chapter5-2.tex:175:\hilight{TODO: tabellen kan göras bredare}
16. koncept/chapter6-3.tex:27:\hilight{TODO:  Här borde vi ta upp att Zepp-antennen och J-pole är olika namn
17. koncept/chapter6-5.tex:68:\hilight{TODO: ge Uda lite kärlek här också}
18. koncept/chapter6-5.tex:70:\hilight{TODO: antennvinsten bestäms väl snarare av längden på bommen, eller?}
19. koncept/chapter7-5.tex:179:\hilight{TODO: beskriv 30 m, 17 m och 12 m som egna band}
20. koncept/chapter7-6.tex:136:\hilight{TODO: Beskriv undantagen från detta - Es, tropo, meteorscatter, m.m.}
21. koncept/chapter7-6.tex:183:\hilight{TODO: info om AMSAT-SM}
22. koncept/chapter8-1.tex:154:\hilight{TODO: Här borde vi främst beskriva den moderna DMM:en och hur man väljer en}
23. koncept/chapter8-1.tex:196:\hilight{TODO: Skippa hur det var förr i tiden, irrelevant idag}
24. koncept/chapter8-1.tex:206:\hilight{TODO: Ta bort texten om N-licensen}
25. koncept/chapter8-1.tex:329:\hilight{TODO: Komplettera med spec, SNA och VNA}
26. koncept/chapter8-2.tex:359:\hilight{TODO: Beskriv hur man faktiskt använder ett oscilloskop och vad
27. koncept/chapter8-2.tex:362:\hilight{TODO: Beskriv digitala och PC-baserade digitala oscilloskop}
28. koncept/chapter8-2.tex:366:\hilight{TODO: Beskriv spektrumanalysator och vad man kan göra med den}
29. koncept/chapter8-2.tex:370:\hilight{TODO: Beskriv nätverksanalysator och vad man kan göra med den}
30. koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}
31. koncept/chapter10-3.tex:159:\hilight{TODO: Information om moderna litium-batterier}
32. koncept/chapter11-6.tex:94:\hilight{TODO: Se Appendix F.}
33. koncept/chapter11-6.tex:96:\hilight{TODO: Se Appendix G.}
34. koncept/chapter13-1.tex:21:\hilight{TODO: Exempel på loggblad saknas}
35. koncept/emf.tex:611:\hilight{TODO: Flytta referenser till BibTex}
36. koncept/foreword.tex:108:\hilight{TODO: Uppdatera förord med utvecklingen.}
37. koncept/morse.tex:121:\hilight{TODO: Kolla upp status på SSA:s ''kurser på band och datadiskett''.}
38. koncept/morse.tex:205:\hilight{TODO: Kolla upp det här programmet och om det fortfarande finns tillgängligt.}
39. koncept/appendix-c.tex:34:\hilight{TODO: Förfarandet som beskrivs här för omvandling dB-spänning är otroligt krångligt, föreslår att vi istället har en kort tabell (eller nomogram), samt hänvisar till hur man slår på en miniräknare}
40. koncept/appendix-g.tex:3:\hilight{TODO: F.2 Behöver fixas.}
41. koncept/appendix-g.tex:8:\hilight{TODO: Referens till senare bandplan}
42. koncept/appendix-g.tex:11:\hilight{TODO: Fixa referenserna}
43. koncept/appendix-g.tex:13:\hilight{TODO: Här används en annan tabell-form än i F.1, unifiera}
44. koncept/appendix-g.tex:42:\hilight{TODO: 50,500-50,190 har fel bakre gräns, hitta rätt}
45. koncept/appendix-h.tex:7:\hilight{TODO: Anpassa till PTSFS 2015:4}
46. koncept/appendix-l.tex:230:\hilight{TODO: Missing Heat dissipation items in HAREC}

De borde åtgärdas, förslagsvis som separata issues

**Comment by sa0mad** [comment]
Listan skapas med
`make TODOs`

**Comment by fnadde42** [comment]
Det verkar finnas lite olika typer av ärenden här:

- Illustration behövs göras/saknas
- Layout-problem
- Text behövs omarbetas/saknade referenser

Ska man klumpa ihop dom i en issue baserat på vad som behövs göras eller ska man sätta upp dom individuellt?

**Comment by sa0mad** [comment]
Verkar det rimligt att bunta ihop några av dem, gör då det.

**Comment by sa0mad** [comment]
#1 åtgärdad

**Comment by sa0mad** [comment]
#2 åtgärdad

**Comment by sa0mad** [comment]
Om alla dessa är utbrytna, så redovisa var de gick och stäng sedan denna issue, då den ej längre behövs.

**Comment by sa0mad** [comment]
19. utflyttad till #75 
20. utflyttad till #76 
21. utflyttad till #77 
22. utflyttad till #78 
28. utflyttad till #82 
31. utflyttad till #84 
35. utflyttad till #83

**Comment by sa0mad** [comment]
Kvar är:
Idag har vi en lång lista TODOs taggade i texten, de är:

3. koncept/chapter1-6.tex:143:\hilight{TODO: Här hade det varit bra med en bild på pendeln. /SM7NTJ}
4. koncept/chapter1-7.tex:140:\hilight{TODO: Illustrera resistor, brus en och in.}
5. koncept/chapter1-7.tex:142:\hilight{TODO: Illustrera brus över tid.}
6. koncept/chapter1-7.tex:144:\hilight{TODO: Illustrera brus över frekvens.}
7. koncept/chapter1-10.tex:69:\hilight{TODO: illustrera sampling}
8. koncept/chapter1-10.tex:83:\hilight{TODO: illustrera kvantisering och PCM}
9. koncept/chapter1-10.tex:174:\hilight{TODO: illustrera viknings-spektrum}
10. koncept/chapter2-5.tex:120:  \hilight{TODO:  här borde vi även ta upp moderna powerledar som kräver
11. koncept/chapter2-6.tex:40:\hilight{TODO: Bild på transistor saknas (ej numrerad)}
12. koncept/chapter2-8.tex:149:\hilight{TODO: Bilden felaktig. Jämför med bild 2.37 och-kretsen.
13. koncept/chapter3-1.tex:387:\hilight{TODO: Fixa flödet runt bilderna här.}
14. koncept/chapter3-4.tex:8:\hilight{TODO:  Det pratas allmänt mycket om rörförstärkare i det här avsnittet.
15. koncept/chapter5-2.tex:175:\hilight{TODO: tabellen kan göras bredare}
16. koncept/chapter6-3.tex:27:\hilight{TODO:  Här borde vi ta upp att Zepp-antennen och J-pole är olika namn
17. koncept/chapter6-5.tex:68:\hilight{TODO: ge Uda lite kärlek här också}
18. koncept/chapter6-5.tex:70:\hilight{TODO: antennvinsten bestäms väl snarare av längden på bommen, eller?}

23. koncept/chapter8-1.tex:196:\hilight{TODO: Skippa hur det var förr i tiden, irrelevant idag}
24. koncept/chapter8-1.tex:206:\hilight{TODO: Ta bort texten om N-licensen}
25. koncept/chapter8-1.tex:329:\hilight{TODO: Komplettera med spec, SNA och VNA}
26. koncept/chapter8-2.tex:359:\hilight{TODO: Beskriv hur man faktiskt använder ett oscilloskop och vad
27. koncept/chapter8-2.tex:362:\hilight{TODO: Beskriv digitala och PC-baserade digitala oscilloskop}

29. koncept/chapter8-2.tex:370:\hilight{TODO: Beskriv nätverksanalysator och vad man kan göra med den}
30. koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}

32. koncept/chapter11-6.tex:94:\hilight{TODO: Se Appendix F.}
33. koncept/chapter11-6.tex:96:\hilight{TODO: Se Appendix G.}
34. koncept/chapter13-1.tex:21:\hilight{TODO: Exempel på loggblad saknas}

36. koncept/foreword.tex:108:\hilight{TODO: Uppdatera förord med utvecklingen.}
37. koncept/morse.tex:121:\hilight{TODO: Kolla upp status på SSA:s ''kurser på band och datadiskett''.}
38. koncept/morse.tex:205:\hilight{TODO: Kolla upp det här programmet och om det fortfarande finns tillgängligt.}
39. koncept/appendix-c.tex:34:\hilight{TODO: Förfarandet som beskrivs här för omvandling dB-spänning är otroligt krångligt, föreslår att vi istället har en kort tabell (eller nomogram), samt hänvisar till hur man slår på en miniräknare}
40. koncept/appendix-g.tex:3:\hilight{TODO: F.2 Behöver fixas.}
41. koncept/appendix-g.tex:8:\hilight{TODO: Referens till senare bandplan}
42. koncept/appendix-g.tex:11:\hilight{TODO: Fixa referenserna}
43. koncept/appendix-g.tex:13:\hilight{TODO: Här används en annan tabell-form än i F.1, unifiera}
44. koncept/appendix-g.tex:42:\hilight{TODO: 50,500-50,190 har fel bakre gräns, hitta rätt}
45. koncept/appendix-h.tex:7:\hilight{TODO: Anpassa till PTSFS 2015:4}
46. koncept/appendix-l.tex:230:\hilight{TODO: Missing Heat dissipation items in HAREC}

**Comment by sa0mad** [comment]
3 utbrutet till #62 
4 utbrutet till #63 
5 utbrutet till #63 
6 utbrutet till #63 
7 utbrutet till #65 
8 utbrutet till #65 
9 utbrutet till #65 
10 utbrutet till #66 
11 utbrutet till #67 
12 utbrutet till #68 
13 utbrutet till #69 
14 utbrutet till #70 
15 utbrutet till #71 
16 utbrutet till #72 
17 utbrutet till #73 
18 utbrutet till #74

**Comment by sa0mad** [comment]
Kvar är:

23 koncept/chapter8-1.tex:196:\hilight{TODO: Skippa hur det var förr i tiden, irrelevant idag}
24 koncept/chapter8-1.tex:206:\hilight{TODO: Ta bort texten om N-licensen}
25 koncept/chapter8-1.tex:329:\hilight{TODO: Komplettera med spec, SNA och VNA}
26 koncept/chapter8-2.tex:359:\hilight{TODO: Beskriv hur man faktiskt använder ett oscilloskop och vad
27 koncept/chapter8-2.tex:362:\hilight{TODO: Beskriv digitala och PC-baserade digitala oscilloskop}

29 koncept/chapter8-2.tex:370:\hilight{TODO: Beskriv nätverksanalysator och vad man kan göra med den}
30 koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}

32 koncept/chapter11-6.tex:94:\hilight{TODO: Se Appendix F.}
33 koncept/chapter11-6.tex:96:\hilight{TODO: Se Appendix G.}
34 koncept/chapter13-1.tex:21:\hilight{TODO: Exempel på loggblad saknas}

36 koncept/foreword.tex:108:\hilight{TODO: Uppdatera förord med utvecklingen.}
37 koncept/morse.tex:121:\hilight{TODO: Kolla upp status på SSA:s ''kurser på band och datadiskett''.}
38 koncept/morse.tex:205:\hilight{TODO: Kolla upp det här programmet och om det fortfarande finns tillgängligt.}
39 koncept/appendix-c.tex:34:\hilight{TODO: Förfarandet som beskrivs här för omvandling dB-spänning är otroligt krångligt, föreslår att vi istället har en kort tabell (eller nomogram), samt hänvisar till hur man slår på en miniräknare}
40 koncept/appendix-g.tex:3:\hilight{TODO: F.2 Behöver fixas.}
41 koncept/appendix-g.tex:8:\hilight{TODO: Referens till senare bandplan}
42 koncept/appendix-g.tex:11:\hilight{TODO: Fixa referenserna}
43 koncept/appendix-g.tex:13:\hilight{TODO: Här används en annan tabell-form än i F.1, unifiera}
44 koncept/appendix-g.tex:42:\hilight{TODO: 50,500-50,190 har fel bakre gräns, hitta rätt}
45 koncept/appendix-h.tex:7:\hilight{TODO: Anpassa till PTSFS 2015:4}
46 koncept/appendix-l.tex:230:\hilight{TODO: Missing Heat dissipation items in HAREC}

**Comment by sa0mad** [comment]
23 utbrutet till #79 
24 utbrutet till #79
25 utbrutet till #80
26 utbrutet till #81 
27 utbrutet till #81 
32 utbrutet till #85 
33 utbrutet till #85 
34 utbrutet till #86 
37 utbrutet till #87

**Comment by sa0mad** [comment]
Kvar är:

29 koncept/chapter8-2.tex:370:\hilight{TODO: Beskriv nätverksanalysator och vad man kan göra med den}
30 koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}
36 koncept/foreword.tex:108:\hilight{TODO: Uppdatera förord med utvecklingen.}
38 koncept/morse.tex:205:\hilight{TODO: Kolla upp det här programmet och om det fortfarande finns tillgängligt.}
39 koncept/appendix-c.tex:34:\hilight{TODO: Förfarandet som beskrivs här för omvandling dB-spänning är otroligt krångligt, föreslår att vi istället har en kort tabell (eller nomogram), samt hänvisar till hur man slår på en miniräknare}
40 koncept/appendix-g.tex:3:\hilight{TODO: F.2 Behöver fixas.}
41 koncept/appendix-g.tex:8:\hilight{TODO: Referens till senare bandplan}
42 koncept/appendix-g.tex:11:\hilight{TODO: Fixa referenserna}
43 koncept/appendix-g.tex:13:\hilight{TODO: Här används en annan tabell-form än i F.1, unifiera}
44 koncept/appendix-g.tex:42:\hilight{TODO: 50,500-50,190 har fel bakre gräns, hitta rätt}
45 koncept/appendix-h.tex:7:\hilight{TODO: Anpassa till PTSFS 2015:4}
46 koncept/appendix-l.tex:230:\hilight{TODO: Missing Heat dissipation items in HAREC}

**Comment by sa0mad** [comment]
@fnadde42 Jag har försökt reverse-engineera alla dina utflyttningar. Man måste tala om i ursprungs-issuen att de är utflyttade så att man kan stänga den när den är tom på ärenden. Nu har det blivit en hel del extra-arbete. Jag är inte säker på att jag hittat alla delarna än, men nu blir det lättare att hitta dem med den reducerade listan. Varje gång man splittar en bugg så skall det finnas ett bidirektionellt beroende så att man hittar både bakåt och framåt, samt kan se var alla delarna tog vägen.

**Comment by sa0mad** [comment]
40 utbruten till #88 
41 utbruten till #88 
42 utbruten till #88 
43 utbruten till #88 
44 utbruten till #88
45 utbruten till #89 

Kvar är:

29 koncept/chapter8-2.tex:370:\hilight{TODO: Beskriv nätverksanalysator och vad man kan göra med den}
30 koncept/chapter9-3.tex:66:%\hilight{TODO: Störningar på analog TV är inte längre relevant}
36 koncept/foreword.tex:108:\hilight{TODO: Uppdatera förord med utvecklingen.}
38 koncept/morse.tex:205:\hilight{TODO: Kolla upp det här programmet och om det fortfarande finns tillgängligt.}
39 koncept/appendix-c.tex:34:\hilight{TODO: Förfarandet som beskrivs här för omvandling dB-spänning är otroligt krångligt, föreslår att vi istället har en kort tabell (eller nomogram), samt hänvisar till hur man slår på en miniräknare}
46 koncept/appendix-l.tex:230:\hilight{TODO: Missing Heat dissipation items in HAREC}

**Comment by sa0mad** [comment]
29 utbruten till #117

**Comment by fnadde42** [comment]
Jo, jag gjorde dom här sent på kvällen och tänkte göra den här biten igår kväll men kroknade. Borde ju så här i efterhand gjort en referens efter varje skapade ärende.

**Comment by sa0mad** [comment]
Sånt händer. Jag har försökt städa upp nu och nu känns det som att det är hyfsat med koll på det. Jag gör också mina fel men försöker göra färre av dem. :)

**Comment by sa0mad** [comment]
39 utbrutet till #58

**Comment by sa0mad** [comment]
36 utbruten till #60

**Comment by sa0mad** [comment]
46 borttagen i commit 84b2967

**Comment by sa0mad** [comment]
38 utbruten till #118

**Comment by sa0mad** [comment]
30 utbruten till #119

**Comment by sa0mad** [comment]
Det finns inga kvarvarande punkter som inte har issue eller är åtgärdad separat.
Stänger.
