### ISSUE TITLE
Hänvisningar till komponentleverantörernas kataloger

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#495]
För att lära sig färgmärkningen på komponenter så hänvisas man till ”komponentleverantörernas kataloger”. Finns det ens några sådana att få tag på?
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/8066451bfd8b979803a58b8542451e16b220a86d/koncept/chapter2-1.tex#L357
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/8066451bfd8b979803a58b8542451e16b220a86d/koncept/chapter2-2.tex#L289

**Comment by Lominean** [comment]
Standarden är alltså [IEC 60062:2016](https://webstore.iec.ch/publication/65655).

**Comment by sa0mad** [comment]
Kanske lite väl outdated. En gång i tiden stod det en ELFA-katalog i var radioamatörs bokhylla, på promient plats med färgkoden på ryggen. Självklar referens då, inte lika självklar idag. Låt oss göra det mer komplett direkt i Koncept, med standard-referens blir det ju rejält och fint.

**Comment by sikvall** [comment]
Alla färgkoder är ju inte resistorns färgkod iofs utan det finns många andra varianter. Det finns en mängd olika färgkoder för spänningar i kablage exempelvis. Några använde vi på firman en gång i tiden, i UK hade man en annan uppfattning, Tyskarna muttrade om ett saligen insomnat försök till DIN-norm...

För att svara på den faktiska frågan:

Gör en tabelljävel över färgerna och deras nummer, förklara precisionsringen, kolla på wikipedia där finns det bra förklaringar och man borde kunna låna lite formuleringar från dem.
