### ISSUE TITLE
LaTeXML: Error:undefined:{pdfsidelinecomment} The environment {pdfsidelinecomment} is not defined.

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#5]
# Återskapa
1. Installera LaTeXML (instruktioner för hur man installerar version 0.8.2 finns i [`BUILD.md`](../blob/master/BUILD.md#latexml):
1. Kör följande kommando:  
    `make koncept.webb`

Fellogg med förekomster av bara det här felet: [error.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/853262/error.txt)  
Hela loggen av körningen: [latexml.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/853263/latexml.txt)

-----

*Fatal Error* som får LaTeXML att stanna. Detta utgör 49 av 100 fel som måste släckas.
```
Fatal:too_many_errors:100 Too many errors (> 100)!
	at koncept/koncept/appendix-l.tex; line 233 col 17
	In Core::Document[@0x478efe8] at koncept/koncept/appendix-l.tex;
	line 233 col 17
	 <= [ <= Core::Document[@0x478efe8] <=
	 [noitemsep]␍\enumerate@itemSimple the... <= ...
6 warnings; 101 errors; 1 fatal error; 9 undefined
macros[\AddToShipoutPicture, {pdfsidelinecomment},
\mdfdefinestyle, \setlongtables, \boxbox, \marginnote, {mdframed},
\DeclareUnicodeCharacter, \harec]; 7 missing files[refbook.sty,
enumitem.sty, mdframed.sty, eso-pic.sty, pdfcomment.sty, marginnote.sty,
stmaryrd.sty] at /usr/share/perl5/LaTeXML/Common/Error.pm line 69.
```
Föregås av flera av följande fel i många av .tex-filerna:

```
Error:undefined:{pdfsidelinecomment} The environment {pdfsidelinecomment}
is not defined.
	at koncept/koncept/appendix-c.tex; line 255 col 19
	Next token is T_OTHER[[]
	In \begin {} from LaTeX.pool.ltxml line 148
	 <= Core::Gullet[@0xd07e78] <= Core::Stomach[@0x338e5f0] <=
	 \begin{document} <= ...
 1.28 sec)
```
Rad 225 i filen `appendix-c.tex`

    255 \begin{rev-raderas}

Förkommer där markeringarna som "omarbetas" och "granskat" i marginalerna finns. Vi måste ta bort dessa eftersom LaTeXML inte förstår hur den ska tolka dom.

**Comment by sikvall** [comment]
pdfsidelinecomments fungerar bara om det är just en PDF man genererar. Dessa försvinner naturligt när de är åtgärdade och granskade och skall inte vara kvar i den färdiga produkten. 

De tillkom för att göra det lättare för de som granskar, fyller på, rättar och redigerar att ha koll på vem som redigerat vad, vilka delar är klara osv.

**Comment by fnadde42** [comment]
Som du tipsade om tidigare så ska jag fixa till så att dessa tas bort innan genereringen startar. Dom kommer ju ändå inte att finnas med i den slutgiltiga produkten. Issue #4 har liknande problem så ska testa att filtrera bort lite grejer där och se om det går bättre. LaTeXML håller på att fixa lite grejer till nästa version så det ska bli kul att se hur det går.

**Comment by sa0mad** [comment]
@fnadde42 Hur har det gått, har det gått bättre med filtrering?

**Comment by fnadde42** [comment]
Jag har jobbat lite med att ta bort taggar och kommit lite framåt men har en bit kvar. Ska pilla på det i sommar.

**Comment by fnadde42** [comment]
LaTeXML har inte support många taggar (bland annat de beskrivna i det här ärendet) så jag stänger den här och öppnar ett nytt ärende ifall det blir problem igen.
