### ISSUE TITLE
Figurer/Tabeller/Litteraturförteckning producerar en tom sida efter registret

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#50]
![screenshot from 2017-08-25 09-28-26](https://user-images.githubusercontent.com/1107419/29703884-c8426e24-8977-11e7-89ad-6cf1e735ce02.png)

**Comment by sa0mad** [comment]
Det här är inte en bug, det är en LaTeX feature att den börjar på en udda sida och tar även upp den jämna sidan bakom. Det är för att dubbelsidigt tryckt skall något börja på en höger-sida, om en vänster-sida blir tom så får den bli det för att nästa sak skall börja på en högersida. Det ser helt fel ut i en PDF, men ser logiskt ut i dubbelsidigt tryckt form. Benägen att stänga denna issue.

**Comment by fnadde42** [comment]
It's not a bug, it's a feature!

Stänger!

**Comment by sa0mad** [comment]
Däremot kan vi fundera på hur den inställningen skall vara när vi gör online-PDF kontra tryck, men jag förespråkar nog att hålla samma. Vi tar det när vi kommer dit.
