### ISSUE TITLE
KonCEPT baksidetext

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#51]
KonCEPT behöver en förklarande text på baksidan som sammanfattar vad boken är till för, vilken nivå den är på osv...

Baksidebilden måste också fixas då upplösningen lämnar en del att önska

**Comment by sa0mad** [comment]
Ett första försök till text skriven och pushad.

**Comment by fnadde42** [comment]
Fixad av: 106d20dc46eb440da3bb5a042256467bf51c3874
