### ISSUE TITLE
Fel i beskrivning av versionsnummer i readme-filen

### ISSUE THREAD

**Issue by sikvall** [SverigesSandareamatorer/SSA-Akademin#513]
Eftersom 0 är första trycningen borde det klargöras i readme-filen liksom att 2 faktiskt är andra upplagan (och inte tredje då det inte fanns någon nollte upplaga) och att 0 som tredje siffra inte är en uppdatering utan första uppdateringen releasad som PDF kommer då heta 1.

Förvirrat? Japp. Men det är så det blev.

Se:
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/README.md

**Comment by sa0mad** [comment]
Det fanns en solklar logik en gång i tiden på den kompromissen. Vi har bara glömt att förklara den.

**Comment by sikvall** [comment]
Jag har alltid sneglat på det som står på https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/README.md och den behöver därmed uppdateras för den är felaktig. Andra och tredje siffrorna beskrivs inte på ett sätt att man naturligt tänker sig att 0 = 1:a.
