### ISSUE TITLE
CQ Emergency

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#517]
"CQ Emergency" förekommer i frågebanken men finns inte omnämnt i boken.

**Comment by sikvall** [comment]
Har gjort en uppdatering i PR #520 den kanske inte är perfekt men kan byggas vidare på.

**Comment by sa0mad** [comment]
Jag har för mig att konklusionen från diskussion är att vi kom fram till att vi inte skall ta upp själva begreppet i utbildningsmaterialet.

**Comment by sikvall** [comment]
Så länge som PTS har frågan kvar i provfrågebanken tycker jag ett litet
stycke om att den inte finns är bra att ha med.

**Comment by sm5phu** [comment]
Inga provfrågor på detta längre.
