### ISSUE TITLE
Saknade releaser

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#523]
v2.2.0 och v2.3.0 inte synliga i https://github.com/SverigesSandareamatorer/SSA-Akademin/releases

**Comment by sikvall** [comment]
Även på github saknas de flesta releaser, det finns en gammal RC och två releaser till men resten saknas.

**Comment by sa0mad** [comment]
v2.2.0 och v2.3.0 saknade taggar, åtgärdat.

**Comment by sa0mad** [comment]
v2.1.0, v2.2.0 och v2.3.0 har nu koncept.pdf och koncept-tryck.pdf. Lite uppstädning till så är det snyggt.
