### ISSUE TITLE
Engelska förkortningar annorlunda

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#524]
Engelska förkortningar skrivs ut på det här sättet:
> En sådan nätverksanalysator kallas för _vektornätverksanalysator_ (eng. _Vector Network Analyzer (VNA)_).

Det gör att även parentestecknen blir kursiverade. Det kan fungera att deklarera förkortningar på den här formen också:

> En sådan nätverksanalysator kallas för _vektornätverksanalysator_ (eng. _Vector Network Analyzer, VNA_).

På så sätt undviks parenteskursiveringen.

**Comment by sikvall** [comment]
Bifall, snyggare med bara innehållet i parenteserna som kursiv text.

Den sön 27 okt. 2019 21:14Philip Eriksson <notifications@github.com> skrev:

**Comment by sa0mad** [comment]
Kan fungera. Jag tror att vi skall nog ha någon snutt av förklaring i inledningen som förklarar formen, så det blir lite explicit. Så görs ofta i tekniska böcker.
