### ISSUE TITLE
Vitt på sida 60 (2.3.11)

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#527]
Jättemycket vitt på sida 60 (2.3.11) (09d076e25a4f484d58d1d9f4a966657b9758a03e).

**Comment by sikvall** [comment]
Verkar redan fixat i current.

[image: image.png]


Den tis 29 okt. 2019 kl 00:56 skrev Philip Eriksson <
notifications@github.com>:

**Comment by Lominean** [comment]
Inte i min senaste -> https://akademin.ssa.se/files/koncept-pdf/koncept.2.3.6+b1036.09d076e.pdf

**Comment by sikvall** [comment]
Då är det nått som är knas. Jag har synkat min git och gjorde make på koncept-tryck.pdf precis nu och den är samma. Byggnumret är exakt samma. 2.3.6 09d07ge och såhär ser sidan 60 ut.

![image](https://user-images.githubusercontent.com/12225714/67727690-a48edb80-f9ea-11e9-9443-1a5528b0a8e9.png)

**Comment by sikvall** [comment]
Det finns en spaltbrytning iofs i närheten där, om du gjort ändringar innan den i din kopia så kan det ju vara så att den kommer fel i förhållande till sidan. Detta får fixas i layout. 

Spårar jag det bakåt ser jag en skillnad i våra PDF:er som uppstår på sidan 56 under 2.2.11.1 och längst ned sista stycket i vänsterpalten. På min ryms hela texten för "Elektrolytkondensator" på den sidan i den spalten, på din flödar den över. 

Varför den gör det begriper jag inte. Så gör den inte här.

**Comment by sikvall** [comment]
Kan du slå en git log och en git status och klippa in resultaten här?

**Comment by Lominean** [comment]
Aha! Det skiljer sig mellan koncept.pdf och koncept-tryck.pdf. Jag, och servern, bygger koncept.pdf.

**Comment by Lominean** [comment]
koncept-tryck.pdf har tydligen en annan initiering av microtype: https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/100e498464946bad52bec85d7eb695f992680e32/koncept-tryck.tex#L14
Flytta båda till common.tex?

**Comment by sikvall** [comment]
Jag mergade tidigare förslag på microtype med mindre ändringar, dvs jag gav den kontroll över kerning och spacing som det borde vara och det kanske är det som skiljer (true i stället för false) på kerning och spacing.

**Comment by sikvall** [comment]
Jag håller på och synkar och löser detta så länge, pilla inte i layouten under tiden för då kan det bli merjobb. Jag tror det ordnar sig typ under morgondagen.

**Comment by Lominean** [comment]
> Jag mergade tidigare förslag på microtype med mindre ändringar, dvs jag gav den kontroll över kerning och spacing som det borde vara och det kanske är det som skiljer (true i stället för false) på kerning och spacing.

Dokumentationen för microtype är tydlig.

> These features do not unconditionally improve the quality of the typeset text: the spacing feature is still considered experimental, while the kerning feature only makes sense in special cases.

Och efter att ha jämfört både med och utan så ser jag ingen anledning att använda dem i dagsläget.

**Comment by sikvall** [comment]
Fixat i senaste merge.
