### ISSUE TITLE
Vilka koncept*-filer används?

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#529]
Vilka av dessa filer används faktiskt och vilka kan tas bort?
- [koncept.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept.tex)
- [koncept-alpha.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept-alpha.tex)
- [koncept-larobok.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept-larobok.tex)
- [koncept-online.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept-online.tex)
- [koncept-refbok.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept-refbok.tex)
- [koncept-tryck.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept-tryck.tex)
- koncept-screen.tex **

** [Redan borttagen](https://github.com/SverigesSandareamatorer/SSA-Akademin/commit/6aa9e958870ecf6802385debe5a31cd77c322992) då den inte finns i Makefile.

**Comment by sikvall** [comment]
Jag *tror* koncept-alfa inte längre är aktuell. 

Sedan är frågan, behöver vi *både* en koncept.pdf och en koncept-tryck.pdf för det är den senare som layoutas vid behov.

De övriga har jag inte jobbat med men jag är med på att städa ut lite (kan ju flytta dem till attic om man ändå vill de "flyter med") på sådant som inte kommer arbetas med under överskådlig framtid.

**Comment by sa0mad** [comment]
larobok och refbok kom från en ambition att dela upp innehållet till en ren lärobok och det övriga till en ren referensbok. Resonemanget bygger på att det kan kännas övermäktigt att se hela materialet. Det verkar dock inte varit något vi hört något om sedan, så jag tror vi kan pensionera det.

alpha och beta var experiment-byggen vi nu kan pensionera.

**Comment by Lominean** [comment]
Behöver någon koncept-online.tex? Är det alltså endast en av koncept.tex och koncept-tryck.tex som behöver finnas?

**Comment by sa0mad** [comment]
koncept-online är så pass inaktuell att vi kastar den. Kokar en pull-request som addresserar alla dessa städningar.

**Comment by sa0mad** [comment]
Städ-PR 532 gör att vi kan fokusera på kvarvarande koncept.tex och koncept-tryck.tex. Om ni godkänner den kan jag merga in den direkt så har vi lite renare miljö, så kan vi titta mer på det som är kvar.

Vi behöver inte attic egentligen, vi har git.

Det fanns en tanke om att online-PDF och en tryck-PDF, där man skulle optimera olika för de olika medierna. Den dubbel-länkning som fanns för HAREC-reglerna togs felaktigt bort vid layout-jobbet, vilket har gjort online-upplevelsen sämre. Den behöver återställas.

**Comment by Lominean** [comment]
Den enda dokumentationen jag hittar kring skillnaden är
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/23f71c4531ee421a617c99fbb6d2a17acc760469/Makefile#L8-L9
och det ger i alla fall mig fler frågor än svar. Byta namn på koncept.tex? @sa0mad kanske kan skriva förklaringen någonstans?

**Comment by Lominean** [comment]
koncept.tex nämns även här men koncept-tryck saknas i den tabellen.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/bed8520e6454dd3c84f4762d757151af4b21d873/BUILD.md#L90

**Comment by phieri** [comment]
Nu är bara koncept.tex kvar så denna kan stängas.
