### ISSUE TITLE
Standard 'make' borde göra en online-vänlig PDF med alternativ mål för tryck-PDF

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#53]
För att förhindra tomma sidor som är helt värdelösa i en *online-PDF* så borde standard make-mål göra en online vänlig version utan justerad höger och vänster marginal och tomma sidor.

Relaterad till #50

**Comment by sa0mad** [comment]
Jag tycket gott vi kan ha en skrivarvänlig PDF tillgänglig också. Just nu är det de enda vi har.

Det man gör är att ändra "twoside" till "oneside" i koncept.tex så går man från 583 sidor till 562 sidor.
Se de två första raderna i koncept.tex.

**Comment by Lominean** [comment]
Jag brukar läsa PDF-böcker i helskärm, tvåsidigt sida-vid-sida, och vill man använda [något JavaScript-bibliotek](http://www.turnjs.com/) för att simulera att bläddra i boken så har jag bara sett sådana som visa uppslag (två sidor). Jag hade hellre sett en EPUB-variant.

**Comment by fnadde42** [comment]
> Jag tycket gott vi kan ha en skrivarvänlig PDF tillgänglig också

Det jag menar är att _de flesta_ som laddar ner kommer att vilja ha en variant som dom ska använda för att antingen titta på sin datorskärm (och då vill man i regel inte ha att marginalen justeras varannan sida och tomma sidor) eller skriva ut enskilda sidor på sin skrivare (och då vill man inte heller ha tomma sidor). De enda gångerna man faktiskt vill ha en utskriftsvänlig/bok version är när man trycker bok och då är det bättre att ha ett alternativt Make-mål för det. Det går till exempel att ha två olika TeX filer som specificerar skillnaderna och som sedan kallar vidare på de "gemensamma" filerna.

> Jag brukar läsa PDF-böcker i helskärm, tvåsidigt sida-vid-sida

Jag upplever inte att det är många som gör så men om man vill göra det så kan man använda sig av Make-målet som gör en utskriftsvänlig/bok PDF.

> Jag hade hellre sett en EPUB-variant

Såklart! Att jag inte tänkte på det. Vi måste ju definitivt generera en EPUB (och kanske andra digitala bokformat) av den här boken.

**Comment by sa0mad** [comment]
Jag har nu lagt till ett tryck-target 'make koncept-tryck-pdf' och ett online-target 'make koncept-online.pdf'.
Den existerande 'make koncept.pdf' får aggera en skrivar-vänlig variant.
Eftersom EPUB är utbruten till #55 så behandlas den aspekten separat.
Betraktar den här som färdig och avklarad.
