### ISSUE TITLE
Tabell A.1 sidan 294 prefixen fC och aC

### ISSUE THREAD

**Issue by SM7NTJ** [SverigesSandareamatorer/SSA-Akademin#534]
Tabell A.1 sidan 294 prefixen fC och aC.
Är det aktuellt att använda femto coulomb respektive atto coulomb?
Det vill säga laddningsmängden för en eller några enstaka elektroner?

**Comment by sikvall** [comment]
Har nog aldrog stött på det annat än esoteriskt. Inga sådana provfrågor
heller.

Den fre 22 nov. 2019 06:09SM7NTJ <notifications@github.com> skrev:
