### ISSUE TITLE
Ett par tryckfel i läsanvisningarna

### ISSUE THREAD

**Issue by SM7NTJ** [SverigesSandareamatorer/SSA-Akademin#535]
T5 ett ord fel, resistans.
T16 ett ord fel, signalbehandling

**Comment by sikvall** [comment]
Åtgärdat.


Den sön 8 dec. 2019 kl 20:12 skrev SM7NTJ <notifications@github.com>:

**Comment by SM7NTJ** [comment]
Tack för snabb fix. Tyvärr hittade jag nu ett par till i T8 mangetiska fäökt  
T8 två ord, magnetiska fält

**Comment by sikvall** [comment]
Fixar i morrn.

Den sön 8 dec. 2019 22:12SM7NTJ <notifications@github.com> skrev:
