### ISSUE TITLE
GitHub: "No description or website provided."

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#537]
Längst upp på projektsidan på GitHub står det "No description or website provided." istället för – en beskrivning och/eller länk till akademin.ssa.se.

**Comment by Lominean** [comment]
Relaterat så saknas även webbadressen i huvudet på [organisationen SverigesSandareamatorer](https://github.com/SverigesSandareamatorer).

**Comment by sm5phu** [comment]
Bra så? [https://github.com/SverigesSandareamatorer/SSA-Akademin](url)

**Comment by phieri** [comment]
Kan  https://github.com/SverigesSandareamatorer/ få `https://www.ssa.se/` också?
