### ISSUE TITLE
Solfläckscykel 25

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#538]
Lagom till nästa tryckning kommer (troligtvis) solfläckscykel 25 ha börjat. Boken behöver återspegla detta.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/50e259f3332d12e961a9c5ca8ce215ca7bb5f573/koncept/chapter8-4.tex#L48-L50

**Comment by sikvall** [comment]
Den kan faktiskt redan ha börjat, men det blir väl inte officiellt förrän i
juli månad om det är så. Omvänd polaritet har redan observerats.

Mvh,
*Täpp-Anders Sikvall*
PGP Key ID EF53EECE <anders@sikvall.se>
Fingerprint C226 1919 C442 3661 4A76  B749 C2D9 E688 EF53 EECE



Den lör 11 apr. 2020 kl 17:04 skrev Philip Eriksson <
notifications@github.com>:

**Comment by Lominean** [comment]
Idag (2020-09-15) har [NOAA/NASA tillkännagivit](https://www.weather.gov/news/201509-solar-cycle) att de anser att vi nu är i cykel 25. Någon som känner sig manad att skriva om texten?
