### ISSUE TITLE
GitHub-etiketter

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#54]
Projekt på GitHub kan få [Topics](https://help.github.com/articles/about-topics/) som läggs till via projektets förstasida för att enklare hitta andra projekt. Just nu saknar SSA-Akademin etiketter.

Jag föreslår att SSA-Akademin märks t.ex. `amateur-radio`, `ham-radio`, `latex` och/eller `teaching-materials`.

**Comment by fnadde42** [comment]
Jag yrkar för att vi (åtminstone tills vidare) använder de Topics som du föreslagit ovan

**Comment by sa0mad** [comment]
Lagt till.
