### ISSUE TITLE
Byta till GitHub Actions

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#542]
Snart kommer Travis CI att byta både [autentisering](https://blog.travis-ci.com/2021-02-22-switch) och [servermiljö](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/). Det är därför ett bra tillfälle att överväga om projektet ska byta till [GitHub Actions](https://github.com/SverigesSandareamatorer/SSA-Akademin/actions). Ett byte skulle kunna förenkla versionshanteringen.

Jag har testat på min fork och [det går bra](https://github.com/phieri/SSA-Akademin/actions/runs/421319253) att bygga PDF:en med Actions.

**Comment by StPiotir** [comment]
Kör hårt! Om det funkar så tycker jag att vi passar på att byta nu 👍

**Comment by sa0mad** [comment]
Nu när vi tryckt ut v2.4.0 är ett bra tillfälle.

**Comment by phieri** [comment]
Travis CI har nu bytt system för öppen källkod-projekt. [Det finns ett förklarande blogginlägg.](https://blog.travis-ci.com/2021-06-16-ibm-aws)
