### ISSUE TITLE
GitHub: Titeln försvinner i mörkt läge

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#545]
Readme-filen som visas på projektsidan på GitHub har en bild med titeln. Bilden har svart text på en transparent bakgrund. När GitHub visas i [mörkt läge](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/managing-your-theme-settings) så syns inte texten.

**Comment by phieri** [comment]
Det finns [stöd för att ha två olika bilder beroende på vilket färgtema som används](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) men jag tror att det är bättre att byta till en text.

**Comment by sikvall** [comment]
Ja, text är bättre där det fungerar.

Mvh,
*Täpp Anders*



Den tors 2 dec. 2021 kl 13:02 skrev Philip Eriksson <
***@***.***>:
