### ISSUE TITLE
Appendix on att skriva loggbok har en nivå section för mycket?

### ISSUE THREAD

**Issue by k7per** [SverigesSandareamatorer/SSA-Akademin#549]
Kan vi flytta upp subsubsection till subsection?

**Comment by phieri** [comment]
Menar du att ta bort
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/664a5149b36c74c0f297c9ab3280ed57e5a96f97/koncept/chapter15-1.tex#L3
och göra alla `subsection` till `section`?

**Comment by k7per** [comment]
Ja, tack för förtydling, ta bort nuvarande section som är samma som titeln, och sen subsection till section.

Jag gjorde om detta i min branch, kolla är du snäll vad du tycker.
