### ISSUE TITLE
Appendix om Måttenheter är kort...

### ISSUE THREAD

**Issue by k7per** [SverigesSandareamatorer/SSA-Akademin#551]
Kan vi göra något bättre med appendix om måttenheter?   Jag lyfte ur metallernas resistivitet, så det är inte så mycket kvar...

Kanske sampla ihop måttenheter och prefixomvandling?  Kanske inte en bra ide om kopia av prefixomvandling ges ut vid prov?

**Comment by sm5phu** [comment]
Lägg till avsnitt om signifikanta siffror.

**Comment by sm5phu** [comment]
Ja, flytta in Prefixomvandling (Appendix L) i Måttenheter (Appendix A)!
