### ISSUE TITLE
Drossel och glimmer, definition och till sakregistret...

### ISSUE THREAD

**Issue by k7per** [SverigesSandareamatorer/SSA-Akademin#555]
Termerna används, men kan nog definieras bättre och läggas till sakregister.

**Comment by k7per** [comment]
Kära språkvetare, kan man istället för drossel skriva induktor?  Om drossel är det vedertagna begreppet så ska vi använda det, fixa till definition och sakregister, men om vi inte behöver så...

per

chapter10-3.tex:etc. kan ofta stoppas med avkopplingskondensatorer och HF-drosslar.
chapter10-3.tex:Moderna avstörningsdrosslar innehåller oftast något ferritmaterial i form av
chapter10-4.tex:Om ledningen förses med till exempel en serieinduktans -- en drossel -- så dämpas
chapter10-4.tex:En drossel kan man göra till exempel genom att linda upp några varv av nätsladden
chapter10-4.tex:Detta kan undvikas genom koppla in HF-drosslar i ledningarna.
chapter10-4.tex:Dessa drosslar bör vara skärmade så att de inte verkar som antenner istället.
chapter10-4.tex:HF-avkopplas med kondensatorer och/eller HF-spärras med drosslar.
chapter10-4.tex:insvängningsförloppet bromsas med en drossel i serie med nycklingskontakten och
chapter12-3.tex:via HF-drosslar eller försedda med överspänningsavledare.
chapter2-3.tex:Utöver dessa finns elektromagneter, drosslar, induktorer för resonanskretsar,
chapter3-4.tex:Drosseln \(Dr\) och kondensatorn \(C\) fungerar som en HF-mässig avkoppling av
chapter3-4.tex:Drosslarna \(Dr\) spärrar HF och kondensatorerna \(C_1\), \(C_2\) och
chapter3-4.tex:Sådana så kallade parasitsvängningar kan stoppas/dämpas med UHF-drosslar (UHF
chapter3-7.tex:Drosseln \(D_r\) hindrar högfrekvenssignalen att överlagras på styrkretsens
chapter6-1.tex:Drosseln efter loop-filtret förhindrar att moduleringssignalen

**Comment by sm5phu** [comment]
En drossel är en variant av induktor. Alla drosslar är induktorer, men alla induktorer är inte drosslar.
