### ISSUE TITLE
Hans diskussionsunderlag

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#556]
Diskussionsunderlag för omdisponering av kursbok för amatörradio
==================================================
*Hans SM3UTY*
*Mellandagarna 2016*

  Här är mitt förslag till ny disposition av kursboken för amatör\-radio\-certifikat, ämnat som underlag för diskussioner.

  Det övergripande målet och syftet med den föreslagna förändring är att motivera läsaren att ta certet.

  Jag har med flit inte tagit med alla detaljer kring vilka kapitel och deras inbördes ordning, eftersom syftet med det här dokumentet är att vara underlag för vidare diskussioner.

  I vårt arbete att uppdatera SSAs utbildningsmaterial kommer även andra böcker tas fram (trafikbok, referensbok), dessa diskuterar jag inte i det här dokumentet.

# Inledning
## Vad är amatörradio?
Här visar vi upp vilken fantastisk hobby amatörradio är, med inspirerande foton och beskrivningar av vad man kan göra som radioamatör, t.ex:
* DX-ing på kortvåg, contesting
* Köra digitalmoder, morsetelegrafi
* Köra portabel kortvåg i skogen
* VHF/UHF - FM-repeater, tropo, $E_s$, $M_S$, NAC ``tisdagstesterna'', m.m.
* Satelliter, APRS
* Bygga själv - egna konstruktioner, byggsatser
* Bygga antenner och antennsystem
* Ragchewing, ``gubbringar''
* Sambandsuppdrag

Mål: Ge en bra överblick av bredden av amatörradiohobbyn, och skapa en känsla av \emph{vad kul det vore att ha amatörradiocertifikat!}

Syfte: Ge läsaren en anledning att bli radioamatör.

## Hur man blir radioamatör
Här beskriver vi hur man rent praktiskt blir radioamatör, dels rent kunskaps\-mässigt, och hur certifikatsprovet går till, hur man får certet, osv.

Mål: Läsaren förstår hur man tar certifikatet, och känner att det är möjligt.

Syfte: Få läsaren att bestämma sej för att bli radioamatör.

# Exempel på några amatörradiostationer
Handgriplig information (foton!) om hur några ``typiska'' amatörradiostationer är uppbyggda, och förklarar de grundläggande begreppen och vad de olika stationerna är ämnade för.

Exempel:
* Handapparat, repeatertrafik
* Portabel kortvågsstation
* Kortvåg med trådantenn eller beamar för DX-ing
* VHF/UHF med ``blindkäpp'' på radhustaket
* VHF/UHF med riktantenner.

Här är det nog smart om vi återkopplar till vad vi beskrivit i inledningen. Skillnaden mot inledningen är att vi beskriver mer detaljer kring kablage, jordning, kontakter, strömförsörjning, etc.

Mål: Läsaren ska få en bild av hur en amatörradiostation kan se ut, och varför det finns så många olika sätt att bygga en amatörradiostation.

Syfte: Bygga förståelse och motivation.

# Hur man bygger en amatörradiostation
Vi går igenom några schematiska stationer, ``tänket'' bakom, och för- och nackdelar med olika sätt att bygga stationen.

Läsaren introduceras till begrepp som:
* Antennsystem
* Blixtskydd, skyddsjordning, HF-jord, isolation
* Matarledningar, baluner
* EMC, EMF
* Sändare, mottagare, slutsteg

Vi pratar endast kortfattat om varje ``grunka'', men hänvisar till senare kapitel i boken, så att den som är särskilt intresserad av någon viss del direkt kan hoppa dit och läsa om sitt favoritämne.

Mål: Läsaren själv ska förstå \emph{varför} de ska lära sej allt som boken innehåller.

Syfte: Bygga kunskap och motivation. Uppfylla HAREC.

# Radiosystem
Vi går igenom radioteknik på ``apparatnivå'', och förklarar begrepp som:
* Frekvens, våglängd
* Radiohorisont, vågutbredning
* Antenner, länkbudget
* Effekt, effektförlust, decibel
* Transmissionsledningar, baluner, impedansmatchning, SWR
* Sändare, mottagare, transceiver
* Strömförsörjning
* Jordning, blixtskydd

Mål: Läsaren ska kunna planera sin egen framtida station.

Syfte: Motivera att läsa vidare. Uppfylla HAREC.

# Radioteknik
\label{radioteknik}
Här ``lyfter vi på locket'' och går igenom varje apparat mer i detalj.

Först introduceras grundläggande begrepp som *oscillator, blandare, filter, bandbredd , modulation, övertoner, distorion, m.fl.*

Därefter bygger vi ihop dessa block till mottagare, sändare, transceiver, slutsteg, osv.

Vi kan återanvända en hel del av Wibergs material, och komplettera med det vi känner kan förbättras.

Mål: Läsaren har god koll på hur de olika apparaterna fungerar, och kan själv leta information om de områden som är extra intressanta.

Syfte: Bygga kunskap. Uppfylla HAREC.

# Antenner
Vi kan återanvända Wibergs material mer eller mindre rakt av.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Likströmslära
Vi kan återanvända en hel del av Wibergs material, och komplettera med det vi känner kan förbättras.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Växelströmslära
Vi kan återanvända Wibergs material mer eller mindre rakt av.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Komponenter
Här går vi ner på komponentnivå, dvs resistor, kondensator, spole, diod, osv.

Vi kan återanvända Wibergs material mer eller mindre rakt av.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Kretsar
Här sätter vi ihop komponenterna till de radiobyggblock som beskrivits i avsnitt \ref{radioteknik}.

Exempel: vi beskriver hur en oscillator fungerar i detalj.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Mätning
Vi kan återanvända en hel del av Wibergs material, och komplettera med
det vi känner kan förbättras.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Elsäkerhet
Vi kan återanvända Wibergs material mer eller mindre rakt av.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Vågutbredning
Vi kan återanvända Wibergs material mer eller mindre rakt av.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Trafikmetoder
Vi kan återanvända en hel del av Wibergs material, och komplettera med det vi känner kan förbättras.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

# Regler \& lagar
Vi kan återanvända en hel del av Wibergs material, och komplettera med det vi känner kan förbättras.

Mål: Uppfylla HAREC.
Syfte: Bygga kunskap. Uppfylla HAREC.

**Comment by phieri** [comment]
Filen [hans-disp.tex](hans-disp.tex) har legat orörd i filträdet väldigt länge. Jag kopierar in innehållet som ett ärende så vi kan ta bort filen.

**Comment by phieri** [comment]
Filen har tagits bort med 2231e3bf8aee8c4cf93597ef21fe08eb20e2afa2

**Comment by sm5phu** [comment]
Överspelat
