### ISSUE TITLE
Ändra alla förekomster av "Radioamatörcertifikat" till  "Amatörradiocertifikat"

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#56]
I enlighet med #46. Vi låter den här vara öppen ända tills någon har gått igenom och sett till att det är fixat.

**Comment by sa0mad** [comment]
Åtgärdat i commit dee986a
Finns kvar på backpage där det är en historisk referens till gamla upplagan, som faktiskt heter som den gör.
