### ISSUE TITLE
Uppgradera paketet siunitx

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#560]
LaTeX-paketet [siunitx](https://ctan.org/pkg/siunitx) har släpps i version 3.0. Flera ändringar har gjorts som KonCEPT-koden behöver anpassas för.

**Comment by k7per** [comment]
Jag kollade dokumentationen från 18 november och det är rekommenderat att man ska sluta använda, till exempel SI.  Är det samma version du kollar på?

Jag föreslår att vi gör en separat pull request som bara har de ändringarna i sig.  Just nu skulle det bli stora merge problem med den gren jag jobbar med.

**Comment by phieri** [comment]
Separat PR låter bra. Om någon kan uppdatera texifiering.md med de tre vanligaste användningssätten också så vore det bra.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/664a5149b36c74c0f297c9ab3280ed57e5a96f97/texifiering.md#L63-L72

**Comment by phieri** [comment]
När jag tittar på loggarna i GitHub Actions så ser det ut som om vi kommer vara kvar på version 2.8 i en standardinstallation. Saken behöver undersökas närmare. Det kanske går att lägga ett alias så det går att bygga med båda versionerna.

**Comment by phieri** [comment]
Det finns [ett blogginlägg](https://www.texdev.net/2021/06/30/siunitx-v2-to-v3#working-with-overleaf) med förslag på kod för att använda både v2 och v3:

```latex
\usepackage{siunitx}
\ifdefined\qty\else
  \ifdefined\NewCommandCopy
    \NewCommandCopy\qty\SI
  \else
    \NewDocumentCommand\qty{O{}mm}{\SI[#1]{#2}{#3}}
  \fi
\fi
\ifdefined\unit\else
  \ifdefined\NewCommandCopy
    \NewCommandCopy\unit\si
  \else
    \NewDocumentCommand\unit{O{}m}{\si[#1]{#2}}
  \fi
\fi
```

**Comment by phieri** [comment]
Under [maj 2022 borde](https://github.com/actions/virtual-environments/discussions/5427) det gå att börja testa att [bygga med Ubuntu 22.04](https://github.com/actions/virtual-environments/issues/5428). Då [finns Tex Live 2021](https://packages.ubuntu.com/jammy/texlive) med.
