### ISSUE TITLE
Bellman kommentar på tabell 3.1

### ISSUE THREAD

**Issue by k7per** [SverigesSandareamatorer/SSA-Akademin#561]
![Screenshot 2021-12-05 at 17 05 07](https://user-images.githubusercontent.com/94111680/144754122-b65fdd6d-b06e-4ff6-a843-2f767f295c84.png)

Han undrar om Zut för kollektorkoppling ska vara 50ohm, inte 50kohm.

Vad var tanken med denna tabell?

**Comment by SM7NTJ** [comment]
Tabellen har ett värde för att indikera värdena och egenskaperna för de olika förstärkarkopplingarna. Det finns provfrågor egenskaperna för förstärkarkopplingar med transistorer.
Gemensam kollektor används normalt vid impedansanpassning mellan en hög ingångsimpedans och en låg utgångsimpedans. Detta medför att tabellvärdet för utgångsimpedansen borde vara 50 ohm.
Vi behöver justera texten om kollektorkoppling i avsnitt 3.4.3 sista stycket första meningen:
Kollektorkoppling används när hög ingångsimpedans och låg utgångsimpedans önskas.
