### ISSUE TITLE
Boken inte längre i två delar

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#564]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/664a5149b36c74c0f297c9ab3280ed57e5a96f97/koncept/tryckort.tex#L37

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/664a5149b36c74c0f297c9ab3280ed57e5a96f97/koncept/foreword.tex#L99

Det här påståendet stämmer inte längre. Det var länge sedan som uppdelningen i två distinkta halvor togs bort.

**Comment by k7per** [comment]
Kolla är du snäll på det jag la in i grenen.  Jag la samma text i tryckkort och foreword.

Om du har bättre ord, så tar jag dem gärna. :-)
