### ISSUE TITLE
Vissa kapitelnummer saknar mellanrum i innehållsförteckningen

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#567]
Det finns flera kapitel i innehållsförteckningen som har 2+2 siffror i kapitelnumret. Mellanrummet till höger till kapitelnamnet är sedan så litet att det ser ut som en oavbruten teckenföljd, t.ex. "16.18Beräkningavtakten".

**Comment by sikvall** [comment]
Har också lagt märke till det, föreslår att vi utökar avståndet i TOC:en.

Jag tror att en  \setlength\cftsubsectionnumwidth{4em} eller liknande på
rätt ställe kan fixa till det där.

Om makrot inte är deffat kanske man också måste riva in paketet
\usepackage{tocloft} eller liknande i preambeln.

Mvh,
*Täpp Anders*



Den mån 13 dec. 2021 kl 20:45 skrev Philip Eriksson <
***@***.***>:

**Comment by k7per** [comment]
Jag kan fixa det.

**Comment by k7per** [comment]
Titta på TOC-width grenen.
