### ISSUE TITLE
Två litteraturförteckningar

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#568]
Som det ser ut just nu så har boken två litteraturförteckningar: en nästan tom i appendix K (sida 327) och en efter sista appendixen (sida 339).

**Comment by k7per** [comment]
Vi sa att innehållet skulle tas bort, med ett tomt appendix, och jag gjorde
det i två steg. Ser ut som att andra steget kom på avvägar. Ska forska.

**Comment by k7per** [comment]
Den andra ändringen ligger som pull request.

**Comment by sm5phu** [comment]
Resolved by #550.

**Comment by phieri** [comment]
Jag öppnar den här igen för om man som förstagångsläsare ser på appendix K så är det inget som tyder på att man tittar på en tidigare litteraturförteckning _för första upplagan_.

**Comment by sm5phu** [comment]
Flytta litteraturförteckning till Appendix K.

**Comment by phieri** [comment]
Klar med #588 . Stänger.
