### ISSUE TITLE
Fel bokstäver för vissa appendix

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#569]
Från appendix G och framåt så stämmer inte bokstaven på appendix överens med filnamnet i koden.

**Comment by k7per** [comment]
Jag såg det också när jag började jobba med saker. Jag tycker vi låter det
vara till version 3, för filnamnbyte är struligt.

**Comment by sikvall** [comment]
Håller med, det har egentligen ingen betydelse förutom OCD-ryckningarna det
orsakar i vänsterögat.

Egentligen borde filnamnen vara utan bokstav och bara heta nått bra och sen
plockas in i rätt ordning ändå. Det är en kvarleva från när vi OCR:ade och
i första omgången ville ha samma namn och nummer på allt som i
originalboken för att kunna bocka av del för del vi rättade det OCR:ade
materialet.

/Anders

Mvh,
*Täpp Anders*



Den mån 13 dec. 2021 kl 21:27 skrev k7per ***@***.***>:

**Comment by phieri** [comment]
Några filer har fått nya namn med #570.
