### ISSUE TITLE
Rubriken på appendix J

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#574]
När jag stöter på appendix J så ser det ut som om rubriken är en särskrivning.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/20933a80488e689aeddc3cf3ac061162ee20c271/koncept/appendix-l.tex#L1

Mina idéer till alternativa rubriker:
- CEPT HAREC-krav
- CEPT HAREC:s krav
- Krav i CEPT HAREC

Synpunkter?

**Comment by k7per** [comment]
Kanske Kunskapskrav i CEPT HAREC?
