### ISSUE TITLE
Exempelsignaler är riktiga signaler

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#576]
I delen om anropssignaler finns det exempel. Två av exemplen är riktiga, aktiva signaler för två privatpersoner.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/8d5b07297f7fdce1ef79fbc7a3527b6bc0828a06/koncept/chapter13-5.tex#L112
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/8d5b07297f7fdce1ef79fbc7a3527b6bc0828a06/koncept/chapter13-5.tex#L115
Att just X används får mig att gissa att det är meningen att det ska visa på formatet utan att kopplas till en aktiv signal.

**Comment by SM7NTJ** [comment]
Ja, tanken var att X ska visa hur en anropssignal är uppbyggd.
Nu har vi tydligen nått ett läge där en av exempelsignalerna numera är anropssignal för en enskild radioamatör och en specialsignal har kommit till användning.
Om det inte dyker upp speciellt livliga protester tror jag att vi ska behålla de exempel vi har då några av exemplen nu har använts på samma sätt i över 25 år.
