### ISSUE TITLE
Andra upplagan är senaste upplagan i introduktionen

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#579]
Introduktionen är förvirrande när andra upplagan är senaste upplagan men det finns två texter.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/04d04e4be5dbc0243bf276e366012fd77a201923/koncept/foreword.tex#L116
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/04d04e4be5dbc0243bf276e366012fd77a201923/koncept/foreword.tex#L145

**Comment by SM7NTJ** [comment]
Jag det ser lite udda ut. Kan vi förenkla texten och ändra till femte tryckningen  så här?

\section*{Femte tryckningen}

Femte tryckningen av KonCEPT har bearbetats för att få ett bättre samspel mellan
bilders placering i förhållande till texten i syftet att göra texten enklare och
lättare att läsa.
Ett antal små fel i formler har justerats och några felstavade ord har rättats.
Några nya kommentarer och förklaringar av begrepp har lagts till.

Det finns med största sannolikhet fortfarande fel och vi vill fortsätta arbetet
med att se till att texten är korrekt och inkluderar relevant information.
Vi vill gärna att ni skickar in förslag på förbättringar, om ni tycker att något
är otydligt eller uppgifter om fel till oss.
Skicka mejl till \texttt{hq@ssa.se}.

**Comment by sm5phu** [comment]
Ja, det ser knasigt ut. Jag instämmer med lorentz förslag om att ändra rubriken till "Femte tryckningen", och texten i övrigt. Tyvärr finns en risk att mejl till hq kommer bort och aldrig når oss.

**Comment by k7per** [comment]
Vart ska mejl skickas?

[er

**Comment by sm5phu** [comment]
Det är nog ändå bäst att behålla hq-adressen.

**Comment by SM7NTJ** [comment]
Fixad av #584
