### ISSUE TITLE
Skriva om: "Förfarandet som beskrivs här för omvandling dB-spänning"?

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#58]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-c.tex#L34

**Comment by sa0mad** [comment]
@SM7NTJ Har lovat att titta på den och verkar ha en ide om hur han skall addressera den.

**Comment by sa0mad** [comment]
åtgärdad.
