### ISSUE TITLE
Titel för 1.12 bruten på två rader i innehållsförteckningen

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#582]
Titeln för delkapitlet "1.12 Sambandet mellan spänning och dBm" är brutet på två rader i innehållsförteckningen trots att det inte alls behövs.

**Comment by sm5phu** [comment]
Felet är i själva kapitelrubriken, där det ligger en extra radbrytning.

chapter1-9.tex, rad 286:
\section[Sambandet spänning och dBm]{Sambandet mellan spänning\newline och dBm}
