### ISSUE TITLE
Formattering saknas i Appendix F, G, H

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#59]

**Comment by Lominean** [comment]
Jag har börjat på Appendix I men eftersom jag inte har boken hos mig så kommer jag inte längre just nu. Den som vill fortsätta på det jag gjort får gärna göra det (fork eller PR): https://github.com/Lominean/SSA-Akademin/tree/appendix-i

**Comment by fnadde42** [comment]
@Lominean Gamla boken finns på PDF. Mejlar till dig.

**Comment by sa0mad** [comment]
Appendix H / Bilaga G åtgärdad.
Appendix G / Bilaga F kvarstår.

**Comment by sa0mad** [comment]
All formatering av F, G och H åtgärdad.
