### ISSUE TITLE
Vad man inte får göra enligt RED

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#591]
Någon har lyckats misstolka den fetstilade texten i [chapter12-2.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept/chapter12-2.tex):

_Detta innebär dock inte att du får göra följande:_

_\begin{itemize}
  \item Bygga en sändare för användning utanför amatörradiobanden.
  \item Modifiera en amatörradiosändare för användning utanför amatörradiobanden
  **\item Modifiera en CE-märkt sändare utanför amatörradiobanden.**
  \item Återställa en CE-märkt sändare till ursprunget efter modifiering till
    amatörradiosändare på amatörradiobanden.
  \item Montera avstörningsfilter inuti en CE-märkt apparat.
\end{itemize}_

Förslag till ändring: 

_\begin{itemize}
   \item Bygga en sändare för användning utanför amatörradiobanden.
   \item Modifiera en sändare **ursprungligen avsedd för användning på amatörradiobanden för användning även** utanför amatörradiobanden.
   \item Modifiera en CE-märkt sändare **ursprungligen avsedd för användning utanför amatörradiobanden för annan användning** utanför amatörradiobanden.
   \item Återställa en CE-märkt sändare till ursprunget efter modifiering till amatörradiosändare på amatörradiobanden.
   \item Montera avstörningsfilter inuti en CE-märkt apparat.
\end{itemize}_

Inte helt smidigt formulerat. Finns bättre förslag? Ska vi helt enkelt låta det vara som det är?

**Comment by kmjonsson** [comment]
Borde inte bara en ändring till räcka:

```
 \item Modifiera en CE-märkt sändare för användning utanför amatörradiobanden.
```

**Comment by sm5phu** [comment]
Förslagsställaren vill täcka in två förbjudna fall enligt dessa exempel:

* Man får inte modifiera en 28 MHz-transceiver för att användas på 27,555 MHz.
* Man får inte modifiera en 27 MHz-transceiver för att användas på 27,555 MHz.

**Comment by kmjonsson** [comment]
Punktlistan kanske bara är för övertydlig.

Tre första punkterna kanske bara ska sammanfattas med:

```
Man får inte bygga eller modifiera en sändare för användning utanför amatörradiobanden.
```

**Comment by k7per** [comment]
I såna här formuleringar så tycker jag inte att det är bra när negationen
bara finns innan listan.  Jag skulle hellre att vi skrev något som:

För X gäller följande:
- man för inte A
- man får inte B

Per

**Comment by SM7NTJ** [comment]
Texten är ursprungligen formulerad för att täcka in tillståndsmyndigheternas tolkning av lagtexten och därmed möjliggöra för en provavläggare att besvara provfrågor med godkänt resultat.

Den inledande texten i stycket berättar vad du som **radioamatör** får göra och sedan beskrivs begränsningarna

Ska vi ändra texten för att förtydliga tolkningen kan vi nog använda den förslagna mindre ändringen så att det blir så här.

Detta innebär att du som radioamatör, utöver vanlig elektronik, får bygga
och använda en radioutrustning.
Du är då ansvarig för att den utrustning du byggt är säker att använda och inte
orsakar störningar.
Detta innebär dock inte att du får göra följande:

\begin{itemize}
\item Bygga en sändare för användning utanför amatörradiobanden.
\item Modifiera en amatörradiosändare för användning utanför amatörradiobanden
\item Modifiera en CE-märkt sändare för användning utanför amatörradiobanden.
\item Återställa en CE-märkt sändare till ursprunget efter modifiering till
amatörradiosändare på amatörradiobanden.
\item Montera avstörningsfilter inuti en CE-märkt apparat.
\end{itemize}

p.s
Ordet "man" är inte lämpligt att använda i sådana här sammanhang då det kan misstolkas
Texten  "Man får modifiera en 27 MHz-transceiver för att användas på 28 MHz." riskerar att bli feltolkad då "man" kan betyda vem som helst.
Ändras texten lite blir den däremot riktig.
En radioamatör får modifiera en 27 MHz-transceiver för att användas på 28 MHz.
