### ISSUE TITLE
Saknad siffra i frekvens

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#599]
Den här raden i bilagan bandplaner verkar sakna en siffra i frekvensen.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/04d04e4be5dbc0243bf276e366012fd77a201923/koncept/appendix-bandplaner.tex#L103

**Comment by SM7NTJ** [comment]
Ja en etta har rymt, det ska stå 14,112 enligt nedan
14\,101 & 14 \,112 & 2700 & Alla moder & Digitala moder och obevakade Digimoder
