### ISSUE TITLE
Uppdatera "Förord" med utvecklingen

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#60]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/foreword.tex#L108

**Comment by sa0mad** [comment]
Jag förväntar mig att den här skall vara öppen fram till frysning. Har dock läst igenom och konstaterat att den har ändå en hel del av historien fram till nu, så den är inte helt inaktuell.

**Comment by sa0mad** [comment]
Nu åtgärdad.
