### ISSUE TITLE
LEK har gjorts om juni 2022

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#616]
[Lagen om elektronisk kommunikation](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-2022482-om-elektronisk-kommunikation_sfs-2022-482) (LEK) har gjorts om i juni 2022. Det kan finnas [ändringar](https://www.pts.se/sv/nya-lek/) som behöver göras i boken.

**Comment by sm5phu** [comment]
2003:389 ska ändras överallt till 2022:482
2003:396 ska ändras överallt till 2022:511
2020:5 ska ändras överallt till 2022:19
