### ISSUE TITLE
Illustration av period med pendel

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#62]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter1-6.tex#L143

**Comment by fnadde42** [comment]
Pendel-illustration finns senare i boken

**Comment by sa0mad** [comment]
@SM7NTJ har gjort bild i PNG-format.
Jag har konverterat den till PDF och lagt in den.
Ser bra ut, så jag deklarerar detta som åtgärdat.
