### ISSUE TITLE
Illustrationer till del om Brus

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#63]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter1-7.tex#L140-L144

**Comment by sa0mad** [comment]
Den första bilden är en klassisk bild för e_n och i_n brus-källor kring ett motstånd.
Se figuren på https://en.wikipedia.org/wiki/Johnson%E2%80%93Nyquist_noise

Den andra bilden skall illustrera vitt brus som hoppar fram och tillbaka, se illustrationer av vitt brus med Gaussisk egenskap. X axeln skall vara spänning och Y-axeln skall vara tid T.

Den tredje bilden skall illustrera att det är jämn amplitud med aveseende på frekvens, dvs. ett rakt horizontalt streck, med nivån e_n, där X axeln är spänning och Y-axeln är frekvens f.

**Comment by SM7NTJ** [comment]
Har ritat och skickat tre bilder om brus för granskning

**Comment by sa0mad** [comment]
åtgärdad av @SM7NTJ , jag har integrerat bilder och bildreferenser i texten, som fick lite extra formuleringar.
