### ISSUE TITLE
Konstig mening med parenteser

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#642]
Den här meningen med dess parenteser i 13.7.1 är konstig:

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/2ec2548954b3d23dd8cb874c1b4bcce09895cc77/koncept/chapter13-5.tex#L300-L301

**Comment by SM7NTJ** [comment]
De vanligaste sökträffarna på KN är come named station, invitation to send named station och adressed station only transmit.
Kan vi ersätts avslutande del med nedanstående?
(eng. \emph{come named station})

**Comment by phieri** [comment]
Är det så här du menar @SM7NTJ? 
```latex
Om man har en telegrafiförbindelse och bara vill tala med den stationen kan man
sända KN (eng. \emph{come named station}).
```

**Comment by SM7NTJ** [comment]
Ja det kan fungera. Meningen ser dock lite fortfarande konstig ut.
Kan det bli bättre så här? @phieri
 
Om man har en telegrafiförbindelse och bara vill att den station man har förbindelse med ska svara kan man sända KN (eng. \emph{come named station}).
