### ISSUE TITLE
Krångligt med halv duplex

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#643]
I 6.3.2 och 6.3.3 beskrivs _simplex_ respektive _halv duplex_. Texten för den sistnämnda blir onödigt svårförstådd när båda avsnitten börjar nästan likadant.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/2ec2548954b3d23dd8cb874c1b4bcce09895cc77/koncept/chapter6-2.tex#L36-L37

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/2ec2548954b3d23dd8cb874c1b4bcce09895cc77/koncept/chapter6-2.tex#L44-L46

**Comment by phieri** [comment]
Nationalencyklopedin använder ihopskrivningen [_halvduplex_](https://www.ne.se/uppslagsverk/encyklopedi/lång/halvduplex); ska vi också göra det?

**Comment by k7per** [comment]
Ja.
