### ISSUE TITLE
Kan inte generera epub

### ISSUE THREAD

**Issue by beltet** [SverigesSandareamatorer/SSA-Akademin#648]
När jag försöker generera epub genom make får man endast en massa felmeddelanden om att ebb inte kan hantera filtyper. Att vissa filer saknas etc.
Avslutar med fatal Error.

Har installerat alla beroenden
Kör Ubuntuderivatet POP! OS på en X260 Thinkpad.

**Comment by phieri** [comment]
Välkommen @beltet ! Det bygge som körs på GitHub har bara fem varningar för kommandot xbb. Får du fler?

**Comment by beltet** [comment]
Tack!
Jag lyckades inte att pipe:a någon bra loggfil, så jag fick kopiera från terminalen. Detta får jag efter att jag kör `make koncept.epub`:

https://pastebin.com/nAwDDrBH
[log.txt](https://github.com/SverigesSandareamatorer/SSA-Akademin/files/11255603/log.txt)

På rad 2464 blir jag promtad om input. Vet inte vad som ska in men kommer vidare om jag bekräftar med enter. Och jag blir promtad ett antal gånger till.

**Comment by phieri** [comment]
Aha! Hur man än gör så blir det inte felsäkert 🙂 När kommandot <kbd>make koncept.epub</kbd> körs igen så ligger .xbb filerna från föregående körning kvar och programmet försöker generera xbb-filer för xbb-filer. Detta syns inte på GitHub eftersom allt återställs mellan körningarna. Ska fundera på hur det kan undvikas.

**Comment by phieri** [comment]
Diskussionen kan fortsätta i ärende #55
