### ISSUE TITLE
Illustrationer till del "Sampling och kvantisering" & "Anti-vikningsfilter"

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#65]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter1-10.tex#L69

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter1-10.tex#L83

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter1-10.tex#L174

**Comment by sa0mad** [comment]
Första bilden skall visa en analog spänning och med jämnt tidsinterval skall "trapp-stegen" av nivåer visas för att representera de samplade nivåerna.

Den andra bilden skall visa hur dessa nivåer anpassas till kvantiserings-steg och visa PCM-koden för varje nivå, precis som klassisk 80-tals CD-reklam från Sony och Philips. Den standard-bilden.

Den tredje bilden är en klassisk vikninsdistorsionsbild. Man brukar illustrera ljud-spektrat som en rätvinklad triangel som har sin högsta punkt vid 0 Hz och lägsta punkt vid högsta frekvensen. Man brukar sedan visa hur vikningsfenomentet gör ett radband av sådana trianglar ömsom rättvända och ömsom spegelvända, där Nykvistfrekvensen är utmärkt för varje vikning. Den borde vara rätt lätt att hitta en förlaga man kan ha att utgå idemässigt från.

**Comment by sm5phu** [comment]
@sm5phu har originalillustration på MSW-format. Skicka till @sa0mad.

**Comment by sa0mad** [comment]
Åtgärdad.
