### ISSUE TITLE
Nostalgi om Ursigram

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#651]
Styckena om Ursigram i 8.3.12 blir mer nostalgi än användbar kunskap för blivande certifikatinnehavare.

Jag föreslår att vi tar bort, alternativt omformulerar kraftigt.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/2ec2548954b3d23dd8cb874c1b4bcce09895cc77/koncept/chapter8-3.tex#L273-L281

**Comment by sm5phu** [comment]
Kanske återanvända text från nya Trafikhandboken?

"Vågutbredningsprognoser 
Det finns numera ett brett utbud av program och webbsidor som ger vågutbredningsprognoser och observationer som underlättar för att förstå vilka frekvenser som kan vara aktuella för DX-trafik och när på dygnet som förhållandena är bäst. Verktygen är av två typer – långtidsprognoser och ”rymdväderobservationer”. Verktygen för långtidsprognoser har utvecklats under många decennier för att till exempel kunna ta fram frekvensscheman för utlandsprogrammen på kortvåg. Det mest kända verktyget är VOACAP, ursprungligen framtaget för Voice of America (VOA). VOACAP har fått ett fantastiskt fint webbgränssnitt [1] för radioamatörer av Jari/OH6BG. Verktygen fungerar så att man matar in solaktiviteten och tidpunkten. Baserat på en medeljonosfär beräknar verktyget en förväntad MUF och signalstyrka på olika band. Solaktiviteten uttrycks i form av solfläckstalet (Sun Spot Number, SSN). SSN får man fram genom att observera solen och räkna antalet fläckar. SSN publiceras på internet dagligen på många olika internetsidor. Ett annat mått, som är nära korrelerat med solfläckstalet är solflödet (solar flux) som antingen mäts i W/m2 eller med hjälp av ett index, SFI (Solar Flux Index). Ett SFI på 100 motsvarar en genomsnittlig solaktivitet."
