### ISSUE TITLE
Ner ska vara mer i kapitel 1.8

### ISSUE THREAD

**Issue by axiom** [SverigesSandareamatorer/SSA-Akademin#654]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/59d32b5ee3f00a2f116342398714913761673f61/koncept/chapter1-8.tex#L1410

Jag gissar att "ner" egentligen skall vara "mer":

>  Fördelen ska vara att överföringen blir **mer** robust samt att signaleringen är

**Comment by phieri** [comment]
Välkommen! Bra noterat! Då det är en så liten ändring så lade jag till den i min redan öppna PR med blandat.
