### ISSUE TITLE
beskrivning av hantering utlänska signaler ej i harmoni med PTS eller CEPT.

### ISSUE THREAD

**Issue by cicci44** [SverigesSandareamatorer/SSA-Akademin#656]
Ifrån version 2.6.0, ecb5edf, av en slump hittade jag under kap 13.5.1
"Utländsk radioamatör på besök i Sverige ska använda sin anropssignal från det egna landet, föregånget av SM/. Till exempel SM/LA9XX vilket låter som “S M streck L A nia X X” [14]."

i PTS bilaga C.
"2.1.2.2. För radioamatörer med HAREC-certifikat från annat land som besöker Sverige under en längre tid eller flyttar till Sverige ska en personlig anropssignal tilldelas. Den ska tilldelas ur prefixserien SA och ha tre bokstäver i suffixet. Anropssignalen får användas under vistelsen i Sverige."

i CEPTS T/R 61-01 – avsnitt 2.3, ref till sida 7
"SM, SA"

vad blir rätt då CEPTS är rekommenderande, gäller SA eller SM eller både och?

**Comment by sm5phu** [comment]
Det finns två CEPT-rekommendationer som behandlar det där.

T/R 61-01 handlar om tillfälliga besök.
T/R 61-02, även kallad HAREC, handlar om permanent flytt mellan länder.

Skrivningen i Bilaga C 2.1.2.2. syftar på T/R 61-02. Den som har ett utländskt certifikat som uppfyller HAREC och vistas i landet mer än tre månader ska tilldelas en permanent svensk anropssignal i SA-serien. Den tolkning som SSA fått godkänd av PTS är att man ska vara folkbokförd i Sverige för att kunna få en svensk anropssignal.

Skrivningen i KonCEPT 13.5.1 syftar däremot på T/R 61-01, "turistlicensen". Tyvärr har PTS handläggare fått saken om bakfoten när de lämnat det svenska underlaget till CEPT. Tabellen i T/R 61-01 ska ange vilket prefix utländska besökare ska använda framför sina utländska anropssignaler när de tillfälligt besöker Sverige. I stället har PTS uppgivit vilka prefix svenska amatörer kan ha i sina egna svenska anropssignaler. Därför står "SM, SA" i tabellen, istället för bara "SM".

**Comment by cicci44** [comment]
Då behöver svenska konCEPT boken uppdatera och följa aktuella T/R 61-01 tillsvidare? 
..och PTS får revidera/komplettera sin skrivmiss iochmed de lämnat in fel underlag tills dess det är nytt revideringstillfälle i CEPT? (hur ofta det nu är, var 5e år kanske?)

**Comment by sm5phu** [comment]
Informationen i KonCEPT (för övrigt inte 13.5.1 utan 13.5.3) är en korrekt tolkning av T/R 61-01. 

Den utländske tillfällige besökaren i exemplet bryter visserligen inte mot reglerna om han identifierar sig som SA/LA9XX istället för SM/LA9XX. Men detta är inget som vi uppmuntrar eller lär ut. SM är internationellt känt som ett svenskt prefix sedan 100 år tillbaka, medan SA bara använts i ett par decennier. 

Att SA numera tilldelas för svenska personliga anropssignaler beror på att SM-signalerna "tog slut". Däremot finns ingen risk att SM/LA9XX ska ta slut så att man också skulle behöva använda SA/LA9XX.

PTS lär inte lämna någon korrigering till T/R 61-01, det kan vi glömma. Däremot finns gott hopp om att så småningom få in ändringar i Bilaga C, om det skulle behövas.

**Comment by cicci44** [comment]
resume.
T/R 61-02 hänvisar på sida 25, CEPT REGULATIONS - Recommendation T/R 61-01; och här beskrivs "SM och SA" och det gör det inte i konCEPT.

De tillfälliga signalerna inom SM, administreras av SSA(?)
Medans tillfälliga inom SA administreras av...ingen(PTS?) 
.. Detta beskrivs i PTS bilaga C med klausun "längre tid" (vad det nu är för PTS, för mig är det tiden det tar innan popcornen blir brända i micron) och efter "längre tid" ska man registrera in sig.

så tillfälliga SA är en del av"...giltigt amatörradiocertifikat utfärdat eller erkänt av PTS..." medans tillfälliga under SM är något som SSA ska hantera. (?)

äsch, jag vet inte. Det känns fortfarande konstigt att utelämna vissa delar..

**Comment by sa0mad** [comment]
CEPT T/R 61-01 och T/R 62-02 är "Recommendations", dvs. det är rekommendationer. Det är standard-lingo för att det är ett ramverk som man kommit överens om, men det står inte över varje nations reglerande myndighets tolkning. Däremot brukar de vara det gemensamma ramverket man utgår ifrån. Så, precis som med allt som kommer från ITU så är det från CEPT i bästa fall en utgångspunkt som gör det enklare att harmonisera. Vad PTS sedan tolkar är en annan sak, men det blir deras tolkning som gäller här. Vad vi I KonCEPT kan göra är att beskriva vad som gäller i Sverige, och i förekommande fall komplicera det hela med den lite större bilden för att berätta vad som sedan gäller i Sverige.

Tillfälliga signaler av den här typen administreras inte, utan kan användas direkt givet att man har ett HAREC cert. Så om LA9AY kommer till Sverige så kan denne köra som SM/LA9AY utan någon registrering. Egentligen skall man alltid kolla med reglerande myndighet i det land man besöker exakt vad som gäller. Vad som står i någon CEPT-standard kan ge en vink av vad man har att vänta sig, men ersätter aldrig den riktiga kollen. Givetvis lyckas jag inte hitta något på PTS hemsida som hjälp till besökande radioamatörer, och aktuella undantagsföreskrifter säger inte heller något vad jag kunde hitta vid snabb titt.

**Comment by sm5phu** [comment]
Intressant diskussion :-)

Om man ska vara petnoga relaterar T/R 61-01 inte till HAREC (certifikatet), utan till "CEPT-licensen" (tillståndsbeviset). HAREC existerade inte när T/R 61-01 infördes, utan tillkom senare, i och med införandet av T/R 61-02. 

Sverige har som bekant avskaffat tillståndsbevisen i de flesta fall, och man kan säga att den svenska anropssignalen i praktiken utgör tillståndsbeviset. Om man har en anropssignal, har man ett också tillstånd. Därför finns ett brev "To whom it may concern" utfärdat av PTS, som svenska resenärer kan medföra i stället för tillståndsbevis vid resa utomlands. Tyvärr kan jag inte hitta det just nu, mitt gamla bokmärke leder till "404" på pts.se.

Varken SSA eller PTS "hanterar" tillfälliga anropssignaler. T/R 61-01 tillkom just med syfte att teleförvaltningarna skulle slippa den här hanteringen. Men vid eventuella tveksamheter är det här en fråga mellan den berörde utländske besökaren och PTS. Frågan ingår inte i den myndighetsutövning som PTS har delegerat till SSA. 

Det finns ett fåtal exempel på länder som tillämpar T/R 61-01 men inte T/R 61-02, och även tvärtom. En amatör från Bosnien-Herzegovina får tillfälligt besöka Sverige, men kan inte få en svensk anropssignal om han bosätter sig här. De högre amerikanska licensklasserna kvalificerar för tillfälliga besök, men duger inte vid permanent bosättning här. En japansk amatör kan få en svensk anropssignal om han bosätter sig här, men får däremot inte turista som SM/JA1XYZ.

Vad som menas med "längre tid" specificeras inte explicit för Sveriges del i T/R 61-01. Men en fotnot som gäller Estland hintar om att gränsen är tre månader. Men i T/R 61-02 sägs uttryckligen att tillämpningen gäller för vistelser som överstiger tre månader, vilken implicerar att T/R 61-02 inte längre gäller då. För svenska förhållanden har SSA och PTS kommit överens om en tolkning som överensstämmer med utlänningslagen och lagen om folkbokföring. Vi kräver att man är folkbokförd i Sverige för att dela ut en permanent svensk anropssignal.

Det finns även några få länder som varken omfattas av T/R 61-01 eller T/R 61-02, men som har urgamla bilaterala reciprokavtal med Sverige. Dessa är Venezuela, Equador och Brasilien.

Det mesta av det här är överkurs, och borde enligt min åsikt inte tynga ned KonCEPT-boken.

Vad gäller prefixen SA och SM i relation till T/R 61-01, så kan vi titta på hur det fungerar i andra länder. Norge använder båda prefixen LA och LB, men endast LA listas i tabellen. Storbritannien använder både G och M, men endast M listas i tabellen. Polackerna har däremot fått saken om bakfoten precis son Sverige, och listar en komplett meny med prefix att välja bland.

**Comment by sa0mad** [comment]
Går man in på "Frågor och svar" på PTS sida för amatörradio så hittar man det som sista frågan:
https://www.pts.se/sv/privat/radio/amatorradio/fragor-och-svar/
Där finns följebrevet på svenska och engelska.
Notera att även gamla CW-kompetenser beskrivs för jämförbarhetens skull. Här kan det eventuellt finnas lite gods att ta vara på för KonCEPT, för att motivera folk att kompletera upp med Morse.

Som historisk not är att Calle BF (i salig åminnelse) var väldigt aktiv för att minska den administrativa belastningen på PTS och ta bort själva tillståndsbevisprocessen för amatörradio och då enbart kräva amatörradiocertifikat, dvs. bevis på tillräcklig kunskap hos operatören. Då inget separat tillståndsbevis skulle behövas blev det rationellt att flytta in amatörradio in i undantagsföreskrifterna, för det är så man hanterar undantag från den generella tillståndsplikten. Där blev det dock lite styvmoderligt hanterat. Det hade kanske varit bättre att ha en separat undantagsföreskrift för amatörradio, och det har diskuterats. Det kanske kan vara värt att göra det ändå, men vi får se vad de i slutändan tycker på PTS.
