### ISSUE TITLE
Stavfel, 1igger ska vara ligger

### ISSUE THREAD

**Issue by axiom** [SverigesSandareamatorer/SSA-Akademin#657]
Här har det blivit en _etta_ `1` istället för bokstaven _L_ `l` i ordet _ligger_.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/59d32b5ee3f00a2f116342398714913761673f61/koncept/chapter3-8.tex#L105

**Comment by sa0mad** [comment]
Det kommer nog från OCRningen. Det var rätt mycket jobb att städa upp OCRningen, och att några saker är kvar kan man misstänka. Nästan förvånad att det inte är oftare. Bra fångat!

**Comment by phieri** [comment]
Det är välkommet om du vill göra en Pull Request för denna och #654, @axiom!
