### ISSUE TITLE
Rubriken Balanserade blandare bör lyftas upp en nivå

### ISSUE THREAD

**Issue by axiom** [SverigesSandareamatorer/SSA-Akademin#658]
Rubriken _Balanserade blandare_ (`subsubsection`) ligger **under** rubriken _Obalanserade blandare_ (`subsection`).

Misstänker att det blivit en `sub` för mycket för den. Tror den skall lyftas upp en nivå så den är på samma nivå som _Obalanserade blandare_.

---

Först har vi rubriken _Obalanserade blandare_:

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/59d32b5ee3f00a2f116342398714913761673f61/koncept/chapter3-8.tex#L38

![image](https://github.com/SverigesSandareamatorer/SSA-Akademin/assets/49829/2f1bedb5-f3de-4611-92a3-2808d8253541)

Följt av under-rubriken _Balanserade blandare_:

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/59d32b5ee3f00a2f116342398714913761673f61/koncept/chapter3-8.tex#L95

![image](https://github.com/SverigesSandareamatorer/SSA-Akademin/assets/49829/553d4cc5-7915-4e5c-809f-bef3d8f8d4a3)

**Comment by phieri** [comment]
Borde även gälla 3.8.2.2 Dubbelbalanserad blandare.
