### ISSUE TITLE
Utöka "LED" med 'moderna powerledar som kräver  konstantströmsmatning'

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#66]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter2-5.tex#L120-L122

**Comment by sa0mad** [comment]
Någorlunda åtgärdad. Har justerat hela lysdiodtexten så den är lite mer informativ.
