### ISSUE TITLE
Missvisande beskrivning av Q-punkt för GE-koppling

### ISSUE THREAD

**Issue by sebcat** [SverigesSandareamatorer/SSA-Akademin#663]
Hej!

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/0ca3bdcc4c89fbe88836bfe971822153dac243bf/koncept/chapter3-4.tex#L168

```
För att en förstärkare ska kunna arbeta på rätt sätt måste arbetspunkten, [...], ställas rätt.

[...]

I en emitterkopplad transistorförstärkare innebär det att basen ska
ges en viss positiv spänning i förhållande till emittern.
Det kan man göra till exempel med en separat spänningskälla eller vanligare med
en avkopplad resistor mellan emittern och minuspolen samt en resistiv
spänningsdelare mellan plus- och minuspolen.
```

Jag uppfattar det här stycket som lite missvisande. En gemensam emitterkoppling har inget emittermotstånd i grundutförande (odegenererad) och när det har det är det av mindre betydelse för arbetspunkten än kollektormotståndet. Kollektormotståndet borde väl nämnas här åtminstånde?

Det är inte heller så vanligt att prata om transkonduktans i ställandet av arbetsläget för bipolära transistorer. Ofta brukar man i alla fall inledningsvis beskriva en bipolär transistor som en strömförstärkare och bestämma arbetsläget efter basström (som kan sättas av två seriekopplade motstånd som beskrivet) och i fallet GE-koppling, kollektormotståndet. Om vi antar NPN och om det flyter en basström kommer basspänningen vara högre än spänningen vid emittern, så det är ju inte felaktigt men kanske inte riktigt så man brukar lära ut att tänka just för bipolära transistorer i en introducerande text.

Mvh,
Sebastian

**Comment by sm5phu** [comment]
Jag kan inte se att begreppet transkonduktans nämns explicit någonstans. Jag skickade avsnittet till professor Zetterling på KTH för kommentarer. Han menar att att avsnittet är korrekt, även om det inte ger en helt fullständig beskrivning.
