### ISSUE TITLE
Bild på transistor saknas

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#67]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter2-6.tex#L40

**Comment by sa0mad** [comment]
@SM7NTJ har gjort bilden i PNG.
Jag har konverterat bilden till PDF.
Jag har lagt till bilden.
Nu åtgärdat.
