### ISSUE TITLE
Ficklampor har bytt konstruktion

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#675]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/b4f67acafdd238290b79847ae2d23686a6cf241d/koncept/chapter7-5.tex#L109

Den här liknelsen är jag osäker på om den kan stå kvar så här. Det är inte längre vanligt i nya ficklampor med rundstrålande ljuskälla och ett reflekterande material bakom utan allt (?) är lysdioder med lins och/eller reflekterande kon _framför_ ljuskällan.

**Comment by sm5phu** [comment]
Finns någon bättre liknelse? Reflektorn i en strålkastare/bilstrålkastare?

**Comment by sikvall** [comment]
Bilstrålkastare är väl också LED vanligen numera. Jag tror dock de flesta
har fortfarande
sett en glödlampeficklampa så det kan nog fungera ett tag till. Det bästa
vore att iofs
snarare illustrera parabolisk reflektion än att hitta märkliga liknelser så
småningom.

Mvh,
*Täpp Anders*
PGP keys can be obtained from ***@***.***



Den mån 9 okt. 2023 kl 00:41 skrev sm5phu ***@***.***>:

**Comment by SM7NTJ** [comment]
Jo ficklampor har utvecklats kraftigt under senare tid. Dock har många tillverkare av ficklampor med LED gått tillbaka från linser/optik till "free form reflector (FF)" när de bygger med CoB LED som ska lysa långt. Detta gäller även för bilstrålkastare med LED inkluderat LED-ramper som numera nästan uteslutande har FF reflektor med dold ljuskälla.

Jag tror att vi tills vidare kan behålla reflektorn och att vi på sikt när vi börjar göra nya figurer och bilder till KonCEPT ser till att göra en bild av en parabolisk reflektor och infoga den i avsnittet.
