### ISSUE TITLE
Illustration av 'INTE ELLER-grind (NOR-gate)' är felaktig

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#68]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter2-8.tex#L149-L151

**Comment by sa0mad** [comment]
Åtgärdad av @SM7NTJ , commit av mig.
