### ISSUE TITLE
Morse antyds vara obligatoriskt

### ISSUE THREAD

**Issue by phieri** [SverigesSandareamatorer/SSA-Akademin#686]
Kapitlet om morsesignalering antyder att det är del av certifikatet, vilket det inte är. Det står inget som talar emot detta.

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/8b6e97c92d4ca17ea872f3a03edf65cc38e0462d/koncept/chapter16-1.tex#L321-L323

**Comment by SM7NTJ** [comment]
I de fall en person behöver ett intyg på färdighet i morsetelegrafi finns möjligheten att avlägga prov för ett frivilligt telegrafiintyg.
läs mer om detta här: https://www.ssa.se/utbildning-certifiering/utbildning/telegrafi/
Kan vi neutralt ändra första meningen till:
Vid ett prov i morsetelegrafering  bedöms läsbarheten av den sändningsstil som
uppvisas.

**Comment by sm5phu** [comment]
Vi kanske också kan komplettera avsnitt 16.2 (Morsesignalering inom amatörradion) med en mening där vi säger att kravet på färdigheter i morsesignalering är avskaffat i Sverige sedan 2004, men att det fortfarande finns kvar i ett fåtal länder. (Enligt T/R 61-02 verkar det vara Ryssland, Belarus, Ukraina, Estland, Irland och Portugal.)

**Comment by sm5phu** [comment]
Bryt ut kapitlet och lägg i en bilaga istället.
