### ISSUE TITLE
Fixa flöde runt bilder i kap. "Upp- och urladdning av en kondensator"

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#69]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter3-1.tex#L387

**Comment by sa0mad** [comment]
TODO borttagen eftersom vi tar hand om det i layout-fasen.
