### ISSUE TITLE
Kort om switchade nätaggregat

### ISSUE THREAD

**Issue by Lominean** [SverigesSandareamatorer/SSA-Akademin#7]
Switchade nätaggregat omnämns bara i ett stycke, trots att de är normen för hemelektronik sedan många år (utom just för drivning av amatörradioapparater).
> Senare utvecklingsformer är s.k. switchade aggregat…

i filen [chapter3-3.tex](https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/master/koncept/chapter3-3.tex).

**Comment by sikvall** [comment]
Ja det är en brist. I dag är det switchade aggregat man skaffar till även amatörradioapparater om man inte är puritan eller vill ha en 40 kg ringkärna i slutsteget. 

Vi spar detta till när det finns tid att skriva materialet. Jag föreslår prio ungefär 3/5 på detta där 1 är högsta prio.

**Comment by sa0mad** [comment]
Jag har absolut inget emot att vi skriver mer om switchade kraftaggregat. Noteras bör att det är inte enbart primär-switchade kraft-aggregat som vi ser, utan även de som finns i DC-DC omvandlare. Det är värt att nämna lite olika typer, t.ex. de som har fix switch-frekvens och de som varierar sin. Det finns även de switch-aggregat som man kan styra switch-frekvensen på för att därmed flytta övertons-spektrat med störningar som det ger ifrån sig. Det finns helt klart en poäng att göra i att de kan skapa störningar, men att dessa även kan hanteras med adekvat filtrering.

**Comment by sa0mad** [comment]
Jag tog  och fixade i form av en text som nu finns i 3.3.4, vilket också bockar av ett till av HAREC-kraven i listan. Det finns säkerligen anledning att se över texten och arbeta på den, men jag anser att den här punkten nu är åtgärdad.
