### ISSUE TITLE
Fokus på transistorförstärkare istället för rörförstärkare

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#70]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter3-4.tex#L8-L11

**Comment by sa0mad** [comment]
Åtgärdad.

En del av de föreslagna strykningarna går mot HAREC-kraven på rör-kunskap. Många av omarbetningsdelarna var egentligen OK. Kompletering med LDMOS transistor gjord. Vi får nog återkomma till ämnet, men för stunder får det nog anses duga.
