### ISSUE TITLE
Förtydliga att "Zepp-antennen och J-pole är olika namn  på samma sak"

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#72]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter6-3.tex#L27-L29

**Comment by sa0mad** [comment]
@sikvall Är det här något du vill bita i?

**Comment by sa0mad** [comment]
@SM7NTJ har åtgärdat med grundtext.
Jag har gjort smärre justering samt flyttat ut bokreferensen till koncept.bib.
För övrigt skall man inte ha citat-tecken i titeln på issues, det försvårar hanteringen.
Den här var egentligen RC1 nivå på, så jag taggar den som det.
Åtgärdad och stängs.
