### ISSUE TITLE
Fel i Appendix I, Tabell I.5.1

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#725]
Mottagarfrekvens gör ett större hopp mellan kanal RF89 och RF91. 
Sändarfrekvensen gör inte motsvarande hopp.
-> Olika duplexavstånd på olika kanaler.

Enligt bandplanen ska samtliga kanaler i bandet ha -600 kHz repeaterskift.
Mottagarfrekvens för kanalerna RF91–RF99 sa minskas med 1 MHz.

**Comment by phieri** [comment]
Det stod förut vilken repeaterskift som gällde men den raden är gjord till kodkommentar, även för övriga band.
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/dbefc18f179406033422000689fd2e7f16859d0e/koncept/appendix-repeatrar.tex#L206
