### ISSUE TITLE
Yagi-Uda istället för Yagi (credit where credit is due)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#73]
Det känns rätt att även nämna Uda i sammanhanget men antennen är ändå känd som Yagi så frågan är på vilka ställen man ska använda den mer formella och korrekta benämningen

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter6-5.tex#L68

[(credit where credit is due)](https://www.youtube.com/watch?v=dPtH2KPuQbs)

**Comment by Lominean** [comment]
Då tycker jag man gör som gjort på Wikipedia: "A Yagi–Uda antenna, commonly known as a Yagi antenna, is a…" Därefter skriver man konsekvent Yagi-Uda.

**Comment by fnadde42** [comment]
Jag håller med

**Comment by sa0mad** [comment]
Jag håller också med. Dessutom är det inte förbjudet att kasta med en länk till Wikipedia. När det blir onlinematerial så skall det vara pepprat med bra länkar för extra-referenser. Just nu är det inte tvärhögst på prio.

**Comment by sa0mad** [comment]
Åtgärdat i commit 0d85a1a
Orkade inte fixa en länk till Wikipedia denna gång.
Uda har fått lite kärlek och credit som han skall ha.

**Comment by sm5phu** [comment]
Ursäkta en senkommen kommentar, men...
Texten måste vara läsbar. Alla säger "yagi" i dagligt språkbruk. Ingen säger "yagi-uda". Det blir tjatigt om vi skriver "yagi-uda" överallt. Jag föreslår att vi första gången antenntypen nämns ger cred till professor Uda, och benämner antennen"yagi-uda", därefter konsekvent endast "yagi".

**Comment by sa0mad** [comment]
åtgärdat i commit 1b01843
