### ISSUE TITLE
Beskriv undantag för radiohorisontens begränsning på VHF (tropo, meteorscatter, m.m.)

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#76]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter7-6.tex#L136

**Comment by sa0mad** [comment]
Det här finns redan beskrivet tidigare i kapitlet, så det är bara att ta bort TODO.
Åtgärdad.
