### ISSUE TITLE
Uppdatera del om "Sändareffekt" och ta bort text om icke-existerande licenser

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#79]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter8-1.tex#L196

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter8-1.tex#L206

**Comment by sa0mad** [comment]
åtgärdad
