### ISSUE TITLE
Skriva om "Oscilloskop" och komplettera samt beskriva digitala och PC-baserade oscilloskop

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#81]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter8-2.tex#L359-L362

**Comment by sa0mad** [comment]
åtgärdad
