### ISSUE TITLE
Information om moderna litium-batterier

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#84]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter10-3.tex#L159

**Comment by sa0mad** [comment]
Vem känner för att skriva om detta? @sikvall @SM7NTJ ?

**Comment by sa0mad** [comment]
Jag kunde konstatatera att det inte krävdes någon tyngre kunskap än den jag besitter för att kunna skriva ihop något tillräckligt adekvat.
Därmed åtgärdad.
