### ISSUE TITLE
"Kunna visa hur man för en loggbok" saknar exempel på loggbok

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#86]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/chapter13-1.tex#L21

**Comment by sa0mad** [comment]
Enkelt logblad inlagt, borde vridas men lyckas inte.
