### ISSUE TITLE
Kolla upp status på SSA:s kurser på band och datadiskett

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#87]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/morse.tex#L121

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/morse.tex#L205

**Comment by sa0mad** [comment]
Enligt diskussion igår så kom vi fram till att det här med all säkerhet skall strykas. Däremot skall vi se om det här materialet kan tillhandahållas på något alternativt sätt. Vi behåller det som en öppen issue här så vi kan följa det.

**Comment by sa0mad** [comment]
Åtgärdad. Skrivit bort kassettband och SSAs program,, men nämner att det finns ljudfiler och program, metoden är i stort densamma.
