### ISSUE TITLE
"VHF/UHF/SHF/EHF bandplan" saknar referenser och har innehållsfel

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#88]
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-g.tex#L3
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-g.tex#L8
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-g.tex#L11
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-g.tex#L13
https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-g.tex#L42

**Comment by sa0mad** [comment]
Formatering åtgärdad.

Tabell-form unifiering ignoreras, den får brytas ut till fix på längre sikt.

Referens till nyare IARU dokument kvarstår.

**Comment by sa0mad** [comment]
åtgärdad.
