### ISSUE TITLE
Rapporter kommer i fel ordning i bilaga "Rapportkoder"

### ISSUE THREAD

**Issue by fnadde42** [SverigesSandareamatorer/SSA-Akademin#90]
I början av kapitlet kommer rapportera i rätt ordning (RST(M)) men när sektionerna i kapitlen kommer är modulation före ton (RS(M)T).

https://github.com/SverigesSandareamatorer/SSA-Akademin/blob/79dc456ccd7951e335ec06a2faf56c4ccdff1a37/koncept/appendix-j.tex#L11-L16

**Comment by sa0mad** [comment]
Det är bara att göra tycker jag.

**Comment by fnadde42** [comment]
Jag hade inte tid då det var så sent på kvällen så jag skrev upp den för att göra den senare

**Comment by sa0mad** [comment]
åtgärdad
