### ISSUE TITLE
HAREC a.3.1.3 Behaviour of real non-ideal resistor, capacitor and inductors at high frequency saknas

### ISSUE THREAD

**Issue by sa0mad** [SverigesSandareamatorer/SSA-Akademin#97]
Det kan vara så att detta är utspritt. Man kan fundera på om det skall finnas en snutt text på varje komponent och refereras separat eller om det skall samlas på ett ställe. Jag föreslår vid varje komponent.

**Comment by fnadde42** [comment]
Jag instämmer. Det är mest vettigt att lägga det vid komponenten i fråga så är man får upp det när man slår upp en komponent.

**Comment by sa0mad** [comment]
Jag kan hjälpa till så att uppmärkningen blir rätt.

**Comment by sa0mad** [comment]
åtgärdad
